-- ============================================
-- Family English Coach - 初始化脚本
-- 从 18章答案.pdf 提取, 18单元 (coordinate-based parser v2)
-- ============================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE word_tags;
TRUNCATE TABLE mastery_record;
TRUNCATE TABLE practice_record;
TRUNCATE TABLE practice_session;
TRUNCATE TABLE daily_task;
TRUNCATE TABLE plan_units;
TRUNCATE TABLE learning_plan;
TRUNCATE TABLE word;
TRUNCATE TABLE unit;
TRUNCATE TABLE member;

INSERT INTO member (id, name, avatar, created_at, updated_at) VALUES
  (1, '默认用户', NULL, NOW(), NOW());

INSERT INTO unit (id, title, sequence, created_at, updated_at) VALUES
  (1, 'Unit 1', 1, NOW(), NOW()),
  (2, 'Unit 2', 2, NOW(), NOW()),
  (3, 'Unit 3', 3, NOW(), NOW()),
  (4, 'Unit 4', 4, NOW(), NOW()),
  (5, 'Unit 5', 5, NOW(), NOW()),
  (6, 'Unit 6', 6, NOW(), NOW()),
  (7, 'Unit 7', 7, NOW(), NOW()),
  (8, 'Unit 8', 8, NOW(), NOW()),
  (9, 'Unit 9', 9, NOW(), NOW()),
  (10, 'Unit 10', 10, NOW(), NOW()),
  (11, 'Unit 11', 11, NOW(), NOW()),
  (12, 'Unit 12', 12, NOW(), NOW()),
  (13, 'Unit 13', 13, NOW(), NOW()),
  (14, 'Unit 14', 14, NOW(), NOW()),
  (15, 'Unit 15', 15, NOW(), NOW()),
  (16, 'Unit 16', 16, NOW(), NOW()),
  (17, 'Unit 17', 17, NOW(), NOW()),
  (18, 'Unit 18', 18, NOW(), NOW());

INSERT INTO word (id, unit_id, english, chinese, type, created_at, updated_at) VALUES
  (1, 1, 'would', '会', 'word', NOW(), NOW()),
  (2, 1, 'world', '世界', 'word', NOW(), NOW()),
  (3, 1, 'if', '如果 1 是否 2', 'word', NOW(), NOW()),
  (4, 1, 'human', '人类', 'word', NOW(), NOW()),
  (5, 1, 'paragraph', '段落', 'word', NOW(), NOW()),
  (6, 1, 'such', '如此的', 'word', NOW(), NOW()),
  (7, 1, 'should', '应该', 'word', NOW(), NOW()),
  (8, 1, 'social', '社会的 1 社交的 2', 'word', NOW(), NOW()),
  (9, 1, 'state', '国家 1 州 2 状态 3 说 4', 'word', NOW(), NOW()),
  (10, 1, 'work', '工作 1 作品 2 起作用 3', 'word', NOW(), NOW()),
  (11, 1, 'time', '时间 1 次数 2 倍数 3', 'word', NOW(), NOW()),
  (12, 1, 'company', '公司 1 陪伴 2', 'word', NOW(), NOW()),
  (13, 1, 'author', '作者', 'word', NOW(), NOW()),
  (14, 1, 'become', '变成', 'word', NOW(), NOW()),
  (15, 1, 'even', '甚至', 'word', NOW(), NOW()),
  (16, 1, 'way', '道路 1 方式 2', 'word', NOW(), NOW()),
  (17, 1, 'science', '科学', 'word', NOW(), NOW()),
  (18, 1, 'research', '研究', 'word', NOW(), NOW()),
  (19, 1, 'search', '搜索', 'word', NOW(), NOW()),
  (20, 1, 'into', '进入', 'word', NOW(), NOW()),
  (21, 1, 'life', '生活 1 生命 2', 'word', NOW(), NOW()),
  (22, 1, 'according to', '根据', 'word', NOW(), NOW()),
  (23, 1, 'because', '因为', 'word', NOW(), NOW()),
  (24, 1, 'also', '也，还', 'word', NOW(), NOW()),
  (25, 1, 'mean', '意味着', 'word', NOW(), NOW()),
  (26, 1, 'means', '方式；方法', 'word', NOW(), NOW()),
  (27, 1, 'need', '需要', 'word', NOW(), NOW()),
  (28, 1, 'seem', '似乎', 'word', NOW(), NOW()),
  (29, 1, 'over/under', '在...之上／ 之下；过了；', 'word', NOW(), NOW()),
  (30, 1, 'between', '两者之间 商业 1', 'word', NOW(), NOW()),
  (31, 1, 'business', '商家 2 事 3', 'word', NOW(), NOW()),
  (32, 1, 'like', '喜欢 1 像 2', 'word', NOW(), NOW()),
  (33, 1, 'likely', '很有可能的', 'word', NOW(), NOW()),
  (34, 1, 'find', '找到 1 发现 2', 'word', NOW(), NOW()),
  (35, 1, 'just', '仅仅 1 就 2 公平的 3', 'word', NOW(), NOW()),
  (36, 1, 'last', '最后 1 持续 2', 'word', NOW(), NOW()),
  (37, 1, '-less', '没有', 'word', NOW(), NOW()),
  (38, 1, 'less', '较少的', 'word', NOW(), NOW()),
  (39, 1, 'result', '结果', 'word', NOW(), NOW()),
  (40, 1, 'result in/lead to', '导致', 'word', NOW(), NOW()),
  (41, 1, 'few', '几乎没有', 'word', NOW(), NOW()),
  (42, 1, 'a few', '一些', 'word', NOW(), NOW()),
  (43, 1, 'follow', '跟随', 'word', NOW(), NOW()),
  (44, 1, 'live', '活／居住 1 直播的 2', 'word', NOW(), NOW()),
  (45, 1, 'adj. own v.', '自己的 拥有', 'word', NOW(), NOW()),
  (46, 1, 'however', '然而；但是', 'word', NOW(), NOW()),
  (47, 1, 'show', '展现', 'word', NOW(), NOW()),
  (48, 1, 'child', '孩子', 'word', NOW(), NOW()),
  (49, 1, 'see', '看见 1 明白 2', 'word', NOW(), NOW()),
  (50, 1, 'study', '学习 1 研究 2', 'word', NOW(), NOW()),
  (51, 1, 'education', '教育', 'word', NOW(), NOW()),
  (52, 1, 'learn', '学习 1 了解 2', 'word', NOW(), NOW()),
  (53, 1, 'scientific', '科学的', 'word', NOW(), NOW()),
  (54, 1, 'test', '测试', 'word', NOW(), NOW()),
  (55, 1, 'example', '例子', 'word', NOW(), NOW()),
  (56, 1, 'large', '大', 'word', NOW(), NOW()),
  (57, 1, 'law', '法律；规则', 'word', NOW(), NOW()),
  (58, 1, 'pass', '通过 1 传递 2', 'word', NOW(), NOW()),
  (59, 1, 'too', '也', 'word', NOW(), NOW()),
  (60, 1, 'increase', '增加', 'word', NOW(), NOW()),
  (61, 1, 'market', '市场', 'word', NOW(), NOW()),
  (62, 1, 'yet', '不过', 'word', NOW(), NOW()),
  (63, 1, 'any', '任何', 'word', NOW(), NOW()),
  (64, 1, 'early', '早', 'word', NOW(), NOW()),
  (65, 1, 'part', '部分 理性', 'word', NOW(), NOW()),
  (66, 1, 'reason', '1 原因 2 推理 3', 'word', NOW(), NOW()),
  (67, 1, 'century', '世纪', 'word', NOW(), NOW()),
  (68, 1, 'family', '家族', 'word', NOW(), NOW()),
  (69, 1, 'before', '在...之前', 'word', NOW(), NOW()),
  (70, 1, 'country', '国家', 'word', NOW(), NOW()),
  (71, 1, 'high', '高', 'word', NOW(), NOW()),
  (72, 1, 'might', '可能', 'word', NOW(), NOW()),
  (73, 1, 'often', '经常', 'word', NOW(), NOW()),
  (74, 1, 'scientist', '科学家', 'word', NOW(), NOW()),
  (75, 1, 'culture', '文化', 'word', NOW(), NOW()),
  (76, 1, 'economic', '经济的', 'word', NOW(), NOW()),
  (77, 1, 'federal', '联邦', 'word', NOW(), NOW()),
  (78, 1, 'keep', '保持 1 留下 2', 'word', NOW(), NOW()),
  (79, 1, 'price', '价格 成本 1', 'word', NOW(), NOW()),
  (80, 1, 'cost', '花费 2 代价 3', 'word', NOW(), NOW()),
  (81, 2, 'idea', '主意；观点', 'word', NOW(), NOW()),
  (82, 2, 'influence/impac', '影响', 'word', NOW(), NOW()),
  (83, 2, 'language', '语言', 'word', NOW(), NOW()),
  (84, 2, 'line', '线', 'word', NOW(), NOW()),
  (85, 2, 'process', '1 过程 2 处理', 'word', NOW(), NOW()),
  (86, 2, 'word', '单词', 'word', NOW(), NOW()),
  (87, 2, 'begin', '开始', 'word', NOW(), NOW()),
  (88, 2, 'power', '权力；能力', 'word', NOW(), NOW()),
  (89, 2, 'society', '1 社会 2 协会；社团', 'word', NOW(), NOW()),
  (90, 2, 'still', '仍然', 'word', NOW(), NOW()),
  (91, 2, 'different', '不同的', 'word', NOW(), NOW()),
  (92, 2, 'kind', '1 慈善的 2 种类', 'word', NOW(), NOW()),
  (93, 2, 'rate', '1 速率 2 比例 3 打分评级', 'word', NOW(), NOW()),
  (94, 2, 'suggest', '1 建议 2 暗示', 'word', NOW(), NOW()),
  (95, 2, 'theory', '理论', 'word', NOW(), NOW()),
  (96, 2, 'control', '管控 1 伟大的', 'word', NOW(), NOW()),
  (97, 2, 'great', '2 好的 3 大的', 'word', NOW(), NOW()),
  (98, 2, 'number', '数字', 'word', NOW(), NOW()),
  (99, 2, 'thing', '事情', 'word', NOW(), NOW()),
  (100, 2, 'question', '1 问题 2 质疑', 'word', NOW(), NOW()),
  (101, 2, 'right', '1 正确的 2 权利 3 右边', 'word', NOW(), NOW()),
  (102, 2, 'very', '非常', 'word', NOW(), NOW()),
  (103, 2, 'want', '想', 'word', NOW(), NOW()),
  (104, 2, 'industry', '1 工业 2 行业；产业', 'word', NOW(), NOW()),
  (105, 2, 'information', '信息', 'word', NOW(), NOW()),
  (106, 2, 'look', '1 看 2 外表', 'word', NOW(), NOW()),
  (107, 2, 'man', '1 人 2 男人', 'word', NOW(), NOW()),
  (108, 2, 'media', '媒体', 'word', NOW(), NOW()),
  (109, 2, 'through', '通过', 'word', NOW(), NOW()),
  (110, 2, 'though', '尽管', 'word', NOW(), NOW()),
  (111, 2, 'write', '写 1 反对', 'word', NOW(), NOW()),
  (112, 2, 'against', '2 面对 3 针对', 'word', NOW(), NOW()),
  (113, 2, 'believe', '1 相信 2 认为', 'word', NOW(), NOW()),
  (114, 2, 'government', '政府 1 兴趣', 'word', NOW(), NOW()),
  (115, 2, 'interest', '2 利息 3 利益', 'word', NOW(), NOW()),
  (116, 2, 'system', '系统', 'word', NOW(), NOW()),
  (117, 2, 'both', '两者都 1 然后', 'word', NOW(), NOW()),
  (118, 2, 'then', '2 那么 3 那时', 'word', NOW(), NOW()),
  (119, 2, 'case', '1 箱子 2 案例 3 情况', 'word', NOW(), NOW()),
  (120, 2, 'develop', '1 发展 2 开发', 'word', NOW(), NOW()),
  (121, 2, 'late', '迟到；晚了', 'word', NOW(), NOW()),
  (122, 2, 'v. mind n.', '在意 思维', 'word', NOW(), NOW()),
  (123, 2, 'text', '文本', 'word', NOW(), NOW()),
  (124, 2, 'v. view n.', '看 观点', 'word', NOW(), NOW()),
  (125, 2, 'important', '重要的', 'word', NOW(), NOW()),
  (126, 2, 'tend to', '倾向于；往往', 'word', NOW(), NOW()),
  (127, 2, 'another', '另一个', 'word', NOW(), NOW()),
  (128, 2, 'n. book v.', '书本 预定', 'word', NOW(), NOW()),
  (129, 2, 'data', '数据', 'word', NOW(), NOW()),
  (130, 2, 'drug', '1 药 2 毒品', 'word', NOW(), NOW()),
  (131, 2, 'effect', '效果；效应', 'word', NOW(), NOW()),
  (132, 2, 'affect', '影响', 'word', NOW(), NOW()),
  (133, 2, 'n. point v.', '观点；点 指', 'word', NOW(), NOW()),
  (134, 2, 'require', '要求', 'word', NOW(), NOW()),
  (135, 2, 'since', '1 自从 2 由于', 'word', NOW(), NOW()),
  (136, 2, 'n. value v.', '价值；价值观 重视；珍视', 'word', NOW(), NOW()),
  (137, 2, 'create', '创造', 'word', NOW(), NOW()),
  (138, 2, 'economy', '经济', 'word', NOW(), NOW()),
  (139, 2, 'future', '将来', 'word', NOW(), NOW()),
  (140, 2, 'grow', '1 成长 2 变得', 'word', NOW(), NOW()),
  (141, 2, 'growth', '增长；成长', 'word', NOW(), NOW()),
  (142, 2, 'intellectual', '有学识的', 'word', NOW(), NOW()),
  (143, 2, 'turn', '转', 'word', NOW(), NOW()),
  (144, 2, 'university', '大学', 'word', NOW(), NOW()),
  (145, 2, 'without', '没有', 'word', NOW(), NOW()),
  (146, 2, 'claim', '1 声称 2 索取', 'word', NOW(), NOW()),
  (147, 2, 'end', '结束；终结', 'word', NOW(), NOW()),
  (148, 2, 'group', '群体', 'word', NOW(), NOW()),
  (149, 2, 'lead', '指引', 'word', NOW(), NOW()),
  (150, 2, 'leave', '离开；留下', 'word', NOW(), NOW()),
  (151, 2, 'national', '国家的', 'word', NOW(), NOW()),
  (152, 2, 'pay', '支付；工资', 'word', NOW(), NOW()),
  (153, 2, 'rather than', '而不是', 'word', NOW(), NOW()),
  (154, 2, 'same', '相同的', 'word', NOW(), NOW()),
  (155, 2, 'support', '支持', 'word', NOW(), NOW()),
  (156, 2, 'cause', '1 导致；引起 2 原因', 'word', NOW(), NOW()),
  (157, 2, 'computer', '电脑', 'word', NOW(), NOW()),
  (158, 2, 'every', '每一个', 'word', NOW(), NOW()),
  (159, 2, 'percent', '百分比', 'word', NOW(), NOW()),
  (160, 2, 'n. place v.', '地方；地点 放置', 'word', NOW(), NOW()),
  (161, 2, 'probably', '可能地', 'word', NOW(), NOW()),
  (162, 2, 'report', '报告', 'word', NOW(), NOW()),
  (163, 2, 'three', '三', 'word', NOW(), NOW()),
  (164, 2, 'true', '真实的 1 当...时', 'word', NOW(), NOW()),
  (165, 2, 'while', '2 尽管 3 然而', 'word', NOW(), NOW()),
  (166, 3, 'account', '账户', 'word', NOW(), NOW()),
  (167, 3, 'among', '在...中间', 'word', NOW(), NOW()),
  (168, 3, 'certain', '1 一些 2 肯定的', 'word', NOW(), NOW()),
  (169, 3, 'customer', '顾客', 'word', NOW(), NOW()),
  (170, 3, 'far', '1 远的 2 相当的', 'word', NOW(), NOW()),
  (171, 3, 'v. form n.', '形成 形式', 'word', NOW(), NOW()),
  (172, 3, 'issue', '1 问题 2 发布', 'word', NOW(), NOW()),
  (173, 3, 'public', '公众的', 'word', NOW(), NOW()),
  (174, 3, 'researcher', '研究员', 'word', NOW(), NOW()),
  (175, 3, 'rise', '上升', 'word', NOW(), NOW()),
  (176, 3, 'rule', '1 统治 2 判决', 'word', NOW(), NOW()),
  (177, 3, 'technology', '技术', 'word', NOW(), NOW()),
  (178, 3, 'where', '在...地方', 'word', NOW(), NOW()),
  (179, 3, 'argue', '1 争吵争论 2 认为；主张', 'word', NOW(), NOW()),
  (180, 3, 'call', '打电话', 'word', NOW(), NOW()),
  (181, 3, 'community', '1 社区 2 团体', 'word', NOW(), NOW()),
  (182, 3, 'consider', '1 考虑 2 认为', 'word', NOW(), NOW()),
  (183, 3, 'consumer', '消费者', 'word', NOW(), NOW()),
  (184, 3, 'court', '法院', 'word', NOW(), NOW()),
  (185, 3, 'each', '每个', 'word', NOW(), NOW()),
  (186, 3, 'off', '离开；分开', 'word', NOW(), NOW()),
  (187, 3, 'political', '政治的', 'word', NOW(), NOW()),
  (188, 3, 'provide', '提供', 'word', NOW(), NOW()),
  (189, 3, 'service', '服务', 'word', NOW(), NOW()),
  (190, 3, 'bring', '带来', 'word', NOW(), NOW()),
  (191, 3, 'feel', '感觉', 'word', NOW(), NOW()),
  (192, 3, 'n. fund v.', '基金 资助', 'word', NOW(), NOW()),
  (193, 3, 'improve', '改善提高', 'word', NOW(), NOW()),
  (194, 3, 'little', '几乎没有', 'word', NOW(), NOW()),
  (195, 3, 'a little', '一点点', 'word', NOW(), NOW()),
  (196, 3, 'offer', '提供', 'word', NOW(), NOW()),
  (197, 3, 'continue', '继续', 'word', NOW(), NOW()),
  (198, 3, 'v. stress n.', '强调 压力', 'word', NOW(), NOW()),
  (199, 3, 'during', '在...期间', 'word', NOW(), NOW()),
  (200, 3, 'fact', '事实', 'word', NOW(), NOW()),
  (201, 3, 'in fact', '事实上', 'word', NOW(), NOW()),
  (202, 3, 'history', '历史', 'word', NOW(), NOW()),
  (203, 3, 'internet', '互联网', 'word', NOW(), NOW()),
  (204, 3, 'million', '百万', 'word', NOW(), NOW()),
  (205, 3, 'billion', '十亿', 'word', NOW(), NOW()),
  (206, 3, 'old', '1 旧的 2 年老的', 'word', NOW(), NOW()),
  (207, 3, 'paper', '1 纸 2 论文', 'word', NOW(), NOW()),
  (208, 3, 'passage', '文章', 'word', NOW(), NOW()),
  (209, 3, 'start', '开始', 'word', NOW(), NOW()),
  (210, 3, 'populationn.', '人口', 'word', NOW(), NOW()),
  (211, 3, 'n. program n.v.', '节目 程序', 'word', NOW(), NOW()),
  (212, 3, 'v. whether', '编程 是否', 'word', NOW(), NOW()),
  (213, 3, 'behavior', '行为', 'word', NOW(), NOW()),
  (214, 3, 'common', '常见的；共同的', 'word', NOW(), NOW()),
  (215, 3, 'dream', '梦想', 'word', NOW(), NOW()),
  (216, 3, 'limit', '限制', 'word', NOW(), NOW()),
  (217, 3, 'v. move n.', '移动 行动', 'word', NOW(), NOW()),
  (218, 3, 'online', '在线的', 'word', NOW(), NOW()),
  (219, 3, 'role', '角色', 'word', NOW(), NOW()),
  (220, 3, 'adj. patient n.', '耐心的 病人', 'word', NOW(), NOW()),
  (221, 3, 'put', '1 放；放置 2 说', 'word', NOW(), NOW()),
  (222, 3, 'share v.', '分享', 'word', NOW(), NOW()),
  (223, 3, 'share n.', '股份', 'word', NOW(), NOW()),
  (224, 3, 'why', '为什么', 'word', NOW(), NOW()),
  (225, 3, 'woman', '女人', 'word', NOW(), NOW()),
  (226, 3, 'always', '总是', 'word', NOW(), NOW()),
  (227, 3, 'average', '1 平均的 2 普通的', 'word', NOW(), NOW()),
  (228, 3, 'bank', '1 银行 2 河岸', 'word', NOW(), NOW()),
  (229, 3, 'skill', '技能', 'word', NOW(), NOW()),
  (230, 3, 'development', '发展', 'word', NOW(), NOW()),
  (231, 3, 'n. experience v.v.', '经验 经历', 'word', NOW(), NOW()),
  (232, 3, 'v. set v.n.', '设置 下降', 'word', NOW(), NOW()),
  (233, 3, 'n. smallv.', '一套 小的', 'word', NOW(), NOW()),
  (234, 3, 'v. act v.n.', '行动 表现 法案', 'word', NOW(), NOW()),
  (235, 3, 'appear', '1 出现 2 显得', 'word', NOW(), NOW()),
  (236, 3, 'deal', '交易', 'word', NOW(), NOW()),
  (237, 3, 'deal with', '处理', 'word', NOW(), NOW()),
  (238, 3, 'a geart deal o', '大量', 'word', NOW(), NOW()),
  (239, 3, 'decade', '十年', 'word', NOW(), NOW()),
  (240, 3, 'decision', '决定', 'word', NOW(), NOW()),
  (241, 3, 'evidence', '证据', 'word', NOW(), NOW()),
  (242, 3, 'food', '食物', 'word', NOW(), NOW()),
  (243, 3, 'health', '健康', 'word', NOW(), NOW()),
  (244, 3, 'him', '他', 'word', NOW(), NOW()),
  (245, 3, 'individual', '个人的', 'word', NOW(), NOW()),
  (246, 3, 'instead', '反而', 'word', NOW(), NOW()),
  (247, 3, 'likely', '很可能的', 'word', NOW(), NOW()),
  (248, 3, 'lose', '1 失去 2 输', 'word', NOW(), NOW()),
  (249, 3, 'medical', '医学的', 'word', NOW(), NOW()),
  (250, 4, 'patent', '专利', 'word', NOW(), NOW()),
  (251, 4, 'play', '玩', 'word', NOW(), NOW()),
  (252, 4, 'professional', '专业的', 'word', NOW(), NOW()),
  (253, 4, 'search', '搜索', 'word', NOW(), NOW()),
  (254, 4, 'though', '虽然', 'word', NOW(), NOW()),
  (255, 4, 'try', '试图', 'word', NOW(), NOW()),
  (256, 4, 'understand', '理解', 'word', NOW(), NOW()),
  (257, 4, 'n. age v.', '年龄 变老', 'word', NOW(), NOW()),
  (258, 4, 'concern', '担心', 'word', NOW(), NOW()),
  (259, 4, 'fall', '下降', 'word', NOW(), NOW()),
  (260, 4, 'function', '功能', 'word', NOW(), NOW()),
  (261, 4, 'half', '一半', 'word', NOW(), NOW()),
  (262, 4, 'hold', '1 持有 2 认为', 'word', NOW(), NOW()),
  (263, 4, 'infer', '推断', 'word', NOW(), NOW()),
  (264, 4, 'least', '最少的', 'word', NOW(), NOW()),
  (265, 4, 'at least', '至少', 'word', NOW(), NOW()),
  (266, 4, 'once', '1 一旦 2 一次 3 曾经', 'word', NOW(), NOW()),
  (267, 4, 'attitude', '态度', 'word', NOW(), NOW()),
  (268, 4, 'back', '1 后面 2 后背', 'word', NOW(), NOW()),
  (269, 4, 'basic', '3 支持 基础的', 'word', NOW(), NOW()),
  (270, 4, 'n. benefit v.', '利益 对 有益', 'word', NOW(), NOW()),
  (271, 4, 'care', '1 关怀照料 2 在乎', 'word', NOW(), NOW()),
  (272, 4, 'death', '死亡', 'word', NOW(), NOW()),
  (273, 4, 'decline', '1 下降 2 谢绝', 'word', NOW(), NOW()),
  (274, 4, 'describe', '描述', 'word', NOW(), NOW()),
  (275, 4, 'financial', '金融的', 'word', NOW(), NOW()),
  (276, 4, 'force', '1 力量 2 强迫', 'word', NOW(), NOW()),
  (277, 4, 'happen', '发生', 'word', NOW(), NOW()),
  (278, 4, 'including', '包括', 'word', NOW(), NOW()),
  (279, 4, 'intelligence', '1 智力 2 情报', 'word', NOW(), NOW()),
  (280, 4, 'journal', '刊物', 'word', NOW(), NOW()),
  (281, 4, 'moral', '道德的', 'word', NOW(), NOW()),
  (282, 4, 'practice', '1 实践 2 练习', 'word', NOW(), NOW()),
  (283, 4, 'produce', '生产', 'word', NOW(), NOW()),
  (284, 4, 'productivity', '生产力', 'word', NOW(), NOW()),
  (285, 4, 'subject', '1 科目 2 主题', 'word', NOW(), NOW()),
  (286, 4, 'ago', '以前的', 'word', NOW(), NOW()),
  (287, 4, 'ask', '问', 'word', NOW(), NOW()),
  (288, 4, 'brain', '头脑', 'word', NOW(), NOW()),
  (289, 4, 'build', '建造', 'word', NOW(), NOW()),
  (290, 4, 'clone', '克隆', 'word', NOW(), NOW()),
  (291, 4, 'doctor', '医生', 'word', NOW(), NOW()),
  (292, 4, 'expect', '1 期待 2 预料', 'word', NOW(), NOW()),
  (293, 4, 'knowledge', '知识', 'word', NOW(), NOW()),
  (294, 4, 'legal', '合法的', 'word', NOW(), NOW()),
  (295, 4, 'adj. major n.', '重大的 专业', 'word', NOW(), NOW()),
  (296, 4, 'music', '音乐', 'word', NOW(), NOW()),
  (297, 4, 'my', '我的', 'word', NOW(), NOW()),
  (298, 4, 'nation', '国家', 'word', NOW(), NOW()),
  (299, 4, 'nature', '1 自然 2 本质本性', 'word', NOW(), NOW()),
  (300, 4, 'possible', '可能的', 'word', NOW(), NOW()),
  (301, 4, 'under', '在……之下', 'word', NOW(), NOW()),
  (302, 4, 'unite', '团结联合', 'word', NOW(), NOW()),
  (303, 4, 'young', '年轻的', 'word', NOW(), NOW()),
  (304, 4, 'environment', '环境', 'word', NOW(), NOW()),
  (305, 4, 'evolution', '进化', 'word', NOW(), NOW()),
  (306, 4, 'revolution', '革命', 'word', NOW(), NOW()),
  (307, 4, 'fail', '失败', 'word', NOW(), NOW()),
  (308, 4, 'fail to', '未能做没做', 'word', NOW(), NOW()),
  (309, 4, 'fashion', '1 时尚 2 方式', 'word', NOW(), NOW()),
  (310, 4, 'inflation', '通货膨胀', 'word', NOW(), NOW()),
  (311, 4, 'intend', '打算', 'word', NOW(), NOW()),
  (312, 4, 'oil', '油', 'word', NOW(), NOW()),
  (313, 4, 'plan', '计划', 'word', NOW(), NOW()),
  (314, 4, 'potential', '1 潜能', 'word', NOW(), NOW()),
  (315, 4, 'potential', '2 潜在的', 'word', NOW(), NOW()),
  (316, 4, 'publish', '出版 1 提高', 'word', NOW(), NOW()),
  (317, 4, 'raise', '2 提出 3 筹集', 'word', NOW(), NOW()),
  (318, 4, 'risk', '4 抚养饲养 风险', 'word', NOW(), NOW()),
  (319, 4, 'run', '1 跑 2 经营', 'word', NOW(), NOW()),
  (320, 4, 'she', '她', 'word', NOW(), NOW()),
  (321, 4, 'species', '物种', 'word', NOW(), NOW()),
  (322, 4, 'structure', '结构', 'word', NOW(), NOW()),
  (323, 4, 'student', '学生', 'word', NOW(), NOW()),
  (324, 4, 'trend', '趋势', 'word', NOW(), NOW()),
  (325, 4, 'substance', '物质', 'word', NOW(), NOW()),
  (326, 4, 'term', '1 术语 2 学期', 'word', NOW(), NOW()),
  (327, 4, 'n. train v.', '火车 培训', 'word', NOW(), NOW()),
  (328, 4, 'until', '直到', 'word', NOW(), NOW()),
  (329, 4, 'within', '在……之内', 'word', NOW(), NOW()),
  (330, 4, 'worker', '工人', 'word', NOW(), NOW()),
  (331, 4, 'ambition', '雄心野心', 'word', NOW(), NOW()),
  (332, 4, 'around', '在……周围', 'word', NOW(), NOW()),
  (333, 4, 'course', '1 过程 2 课程', 'word', NOW(), NOW()),
  (334, 4, 'demand', '需求', 'word', NOW(), NOW()),
  (335, 4, 'discovery', '发现', 'word', NOW(), NOW()),
  (336, 4, 'enough', '足够的', 'word', NOW(), NOW()),
  (337, 4, 'ever', '从来永远', 'word', NOW(), NOW()),
  (338, 4, 'experiment', '试验', 'word', NOW(), NOW()),
  (339, 4, 'explain', '解释', 'word', NOW(), NOW()),
  (340, 4, 'involve', '涉及到', 'word', NOW(), NOW()),
  (341, 4, 'low', '低', 'word', NOW(), NOW()),
  (342, 4, 'pattern', '模式', 'word', NOW(), NOW()),
  (343, 4, 'pressure', '压力', 'word', NOW(), NOW()),
  (344, 4, 'read', '读', 'word', NOW(), NOW()),
  (345, 4, 'reduce', '减少', 'word', NOW(), NOW()),
  (346, 4, 'remain', '1 保持 2 留下', 'word', NOW(), NOW()),
  (347, 5, 'add', '增加', 'word', NOW(), NOW()),
  (348, 5, 'almost', '几乎', 'word', NOW(), NOW()),
  (349, 5, 'attention', '注意力', 'word', NOW(), NOW()),
  (350, 5, 'body', '身体', 'word', NOW(), NOW()),
  (351, 5, 'condition', '条件', 'word', NOW(), NOW()),
  (352, 5, 'dam', '大坝', 'word', NOW(), NOW()),
  (353, 5, 'difference', '不同', 'word', NOW(), NOW()),
  (354, 5, 'down', '下', 'word', NOW(), NOW()),
  (355, 5, 'especially', '尤其', 'word', NOW(), NOW()),
  (356, 5, 'generally', '通常来说', 'word', NOW(), NOW()),
  (357, 5, 'generation', '代', 'word', NOW(), NOW()),
  (358, 5, 'home', '家', 'word', NOW(), NOW()),
  (359, 5, 'humanity', '人性', 'word', NOW(), NOW()),
  (360, 5, 'kid', '孩子', 'word', NOW(), NOW()),
  (361, 5, 'loss', '失去', 'word', NOW(), NOW()),
  (362, 5, 'monkey', '猴子', 'word', NOW(), NOW()),
  (363, 5, 'natural', '自然的', 'word', NOW(), NOW()),
  (364, 5, 'policy', '政策', 'word', NOW(), NOW()),
  (365, 5, 'several', '一些', 'word', NOW(), NOW()),
  (366, 5, 'talk', '谈论', 'word', NOW(), NOW()),
  (367, 5, 'television', '电视', 'word', NOW(), NOW()),
  (368, 5, 'web', '网络', 'word', NOW(), NOW()),
  (369, 5, 'writer', '作家', 'word', NOW(), NOW()),
  (370, 5, 'ability', '能力', 'word', NOW(), NOW()),
  (371, 5, 'accept', '接受', 'word', NOW(), NOW()),
  (372, 5, 'agree', '同意', 'word', NOW(), NOW()),
  (373, 5, 'available', '1 可用的 2 可得到的', 'word', NOW(), NOW()),
  (374, 5, 'casino', '赌场', 'word', NOW(), NOW()),
  (375, 5, 'class', '1 阶级 2 等级', 'word', NOW(), NOW()),
  (376, 5, 'compare', '3 班级 比较', 'word', NOW(), NOW()),
  (377, 5, 'consequence', '结果', 'word', NOW(), NOW()),
  (378, 5, 'cultural', '文化的', 'word', NOW(), NOW()),
  (379, 5, 'depend on', '1 依靠 2 取决于', 'word', NOW(), NOW()),
  (380, 5, 'easy', '1 容易的 2 轻松的', 'word', NOW(), NOW()),
  (381, 5, 'n. firm adj.', '公司 坚固的', 'word', NOW(), NOW()),
  (382, 5, 'hot', '热的', 'word', NOW(), NOW()),
  (383, 5, 'justice', '1 正义 2 大法官', 'word', NOW(), NOW()),
  (384, 5, 'news', '新闻', 'word', NOW(), NOW()),
  (385, 5, 'newspaper', '报纸', 'word', NOW(), NOW()),
  (386, 5, 'open', '打开', 'word', NOW(), NOW()),
  (387, 5, 'seek', '寻找', 'word', NOW(), NOW()),
  (388, 5, 'send', '发送', 'word', NOW(), NOW()),
  (389, 5, 'single', '单个的', 'word', NOW(), NOW()),
  (390, 5, 'standard', '标准', 'word', NOW(), NOW()),
  (391, 5, 'together', '一起', 'word', NOW(), NOW()),
  (392, 5, 'week', '周', 'word', NOW(), NOW()),
  (393, 5, 'although', '尽管', 'word', NOW(), NOW()),
  (394, 5, 'v. advocate n.', '拥护提倡 拥护者', 'word', NOW(), NOW()),
  (395, 5, 'concept', '概念', 'word', NOW(), NOW()),
  (396, 5, 'house', '房子', 'word', NOW(), NOW()),
  (397, 5, 'influential', '有影响力的', 'word', NOW(), NOW()),
  (398, 5, 'management', '管理', 'word', NOW(), NOW()),
  (399, 5, 'member', '成员', 'word', NOW(), NOW()),
  (400, 5, 'message', '信息', 'word', NOW(), NOW()),
  (401, 5, 'note', '1 笔记 2 注意到', 'word', NOW(), NOW()),
  (402, 5, 'opportunity', '3 氛围 机会', 'word', NOW(), NOW()),
  (403, 5, 'parent', '家长', 'word', NOW(), NOW()),
  (404, 5, 'plate', '1 盘子 2 牌子', 'word', NOW(), NOW()),
  (405, 5, 'present', '1 礼物 2 现在的 3 出席的', 'word', NOW(), NOW()),
  (406, 5, 'production', '4 呈现 生产', 'word', NOW(), NOW()),
  (407, 5, 'receive', '接收', 'word', NOW(), NOW()),
  (408, 5, 'v. regard n.', '认为 问候', 'word', NOW(), NOW()),
  (409, 5, 'second', '1 第二 3', 'word', NOW(), NOW()),
  (410, 5, 'second thus', '2 秒 因此', 'word', NOW(), NOW()),
  (411, 5, 'top', '顶端', 'word', NOW(), NOW()),
  (412, 5, 'union', '联盟', 'word', NOW(), NOW()),
  (413, 5, 'war', '战争', 'word', NOW(), NOW()),
  (414, 5, 'whose', '谁的', 'word', NOW(), NOW()),
  (415, 5, 'advantage', '优势', 'word', NOW(), NOW()),
  (416, 5, 'already', '已经', 'word', NOW(), NOW()),
  (417, 5, 'art', '艺术', 'word', NOW(), NOW()),
  (418, 5, 'asset', '资产', 'word', NOW(), NOW()),
  (419, 5, 'billion', '十亿', 'word', NOW(), NOW()),
  (420, 5, 'million', '百万', 'word', NOW(), NOW()),
  (421, 5, 'carry', '携带', 'word', NOW(), NOW()),
  (422, 5, 'challenge', '挑战', 'word', NOW(), NOW()),
  (423, 5, 'difficult', '困难的', 'word', NOW(), NOW()),
  (424, 5, 'earn', '挣得', 'word', NOW(), NOW()),
  (425, 5, 'focus/concentra', '集中', 'word', NOW(), NOW()),
  (426, 5, 'habit', '习惯', 'word', NOW(), NOW()),
  (427, 5, 'happiness', '幸福', 'word', NOW(), NOW()),
  (428, 5, 'introduce', '介绍', 'word', NOW(), NOW()),
  (429, 5, 'leader', '领导', 'word', NOW(), NOW()),
  (430, 5, 'lot', '许多', 'word', NOW(), NOW()),
  (431, 5, 'n. matter v.', '事情 要紧', 'word', NOW(), NOW()),
  (432, 5, 'modern', '现代的', 'word', NOW(), NOW()),
  (433, 5, 'order', '1 命令 2 订', 'word', NOW(), NOW()),
  (434, 5, 'personal', '1 个人的 2 人际的', 'word', NOW(), NOW()),
  (435, 5, 'poor', '1 贫穷的 2 可怜的', 'word', NOW(), NOW()),
  (436, 5, 'product', '产品', 'word', NOW(), NOW()),
  (437, 5, 'real', '真实的', 'word', NOW(), NOW()),
  (438, 5, 'reveal', '揭示', 'word', NOW(), NOW()),
  (439, 5, 'sell', '卖 1 感官', 'word', NOW(), NOW()),
  (440, 5, 'sense', '2 察觉 3 感（抽象） 4 意义', 'word', NOW(), NOW()),
  (441, 6, 'situation', '情况', 'word', NOW(), NOW()),
  (442, 6, 'smell', '闻', 'word', NOW(), NOW()),
  (443, 6, 'success', '成功', 'word', NOW(), NOW()),
  (444, 6, 'suffer', '遭受', 'word', NOW(), NOW()),
  (445, 6, 'towards', '朝着', 'word', NOW(), NOW()),
  (446, 6, 'able', '能够', 'word', NOW(), NOW()),
  (447, 6, 'achieve', '成就，达成', 'word', NOW(), NOW()),
  (448, 6, 'action', '行动', 'word', NOW(), NOW()),
  (449, 6, 'activity', '活动', 'word', NOW(), NOW()),
  (450, 6, 'adult', '成人', 'word', NOW(), NOW()),
  (451, 6, 'advance', '前进', 'word', NOW(), NOW()),
  (452, 6, 'agent', '代理', 'word', NOW(), NOW()),
  (453, 6, 'anything', '任何事', 'word', NOW(), NOW()),
  (454, 6, 'approach', '1 接近 2 方式方法', 'word', NOW(), NOW()),
  (455, 6, 'area', '地区', 'word', NOW(), NOW()),
  (456, 6, 'base', '基地', 'word', NOW(), NOW()),
  (457, 6, 'close', '1 关闭 2 近的', 'word', NOW(), NOW()),
  (458, 6, 'critic/criticize/ critical/criticism', '批评', 'word', NOW(), NOW()),
  (459, 6, 'essential', '基本的', 'word', NOW(), NOW()),
  (460, 6, 'freedom', '自由', 'word', NOW(), NOW()),
  (461, 6, 'gamble', '赌博', 'word', NOW(), NOW()),
  (462, 6, 'general', '通用的', 'word', NOW(), NOW()),
  (463, 6, 'goal', '目标 1 困难的', 'word', NOW(), NOW()),
  (464, 6, 'hard', '2 坚硬的 3 努力的', 'word', NOW(), NOW()),
  (465, 6, 'immigrant', '移民', 'word', NOW(), NOW()),
  (466, 6, 'international', '国际的', 'word', NOW(), NOW()),
  (467, 6, 'investment', '投资', 'word', NOW(), NOW()),
  (468, 6, 'IQ', '智商', 'word', NOW(), NOW()),
  (469, 6, 'v. list n.', '列出 清单', 'word', NOW(), NOW()),
  (470, 6, 'machine', '机器', 'word', NOW(), NOW()),
  (471, 6, 'meet', '1 遇见', 'word', NOW(), NOW()),
  (472, 6, 'meet method', '2 满足 方法', 'word', NOW(), NOW()),
  (473, 6, 'necessary', '必要的', 'word', NOW(), NOW()),
  (474, 6, 'never', '绝不从不', 'word', NOW(), NOW()),
  (475, 6, 'pain', '痛', 'word', NOW(), NOW()),
  (476, 6, 'peer(pressure)', '同辈压力', 'word', NOW(), NOW()),
  (477, 6, 'prove', '证明', 'word', NOW(), NOW()),
  (478, 6, 'n. score v.', '分数 得分', 'word', NOW(), NOW()),
  (479, 6, 'something', '某事', 'word', NOW(), NOW()),
  (480, 6, 'spot', '点', 'word', NOW(), NOW()),
  (481, 6, 'tell', '1 告诉 2 分辨', 'word', NOW(), NOW()),
  (482, 6, 'trade', '贸易', 'word', NOW(), NOW()),
  (483, 6, 'v. wonder n.', '想知道 神奇', 'word', NOW(), NOW()),
  (484, 6, 'baby', '婴儿', 'word', NOW(), NOW()),
  (485, 6, 'beyond', '超过', 'word', NOW(), NOW()),
  (486, 6, 'clear', '清楚的', 'word', NOW(), NOW()),
  (487, 6, 'fast', '快', 'word', NOW(), NOW()),
  (488, 6, 'competition', '竞争', 'word', NOW(), NOW()),
  (489, 6, 'conduct', '实施', 'word', NOW(), NOW()),
  (490, 6, 'define', '下定义', 'word', NOW(), NOW()),
  (491, 6, 'effort', '努力', 'word', NOW(), NOW()),
  (492, 6, 'face', '1 脸 2 面对', 'word', NOW(), NOW()),
  (493, 6, 'feature', '特征', 'word', NOW(), NOW()),
  (494, 6, 'genetic', '基因的', 'word', NOW(), NOW()),
  (495, 6, 'include', '包括', 'word', NOW(), NOW()),
  (496, 6, 'itself', '它自己', 'word', NOW(), NOW()),
  (497, 6, 'labor', '劳动', 'word', NOW(), NOW()),
  (498, 6, 'lack', '缺乏', 'word', NOW(), NOW()),
  (499, 6, 'level', '水平', 'word', NOW(), NOW()),
  (500, 6, 'next', '接下来', 'word', NOW(), NOW()),
  (501, 6, 'outside', '在外面', 'word', NOW(), NOW()),
  (502, 6, 'particular', '特别', 'word', NOW(), NOW()),
  (503, 6, 'particularly', '尤其·', 'word', NOW(), NOW()),
  (504, 6, 'perhaps', '也许', 'word', NOW(), NOW()),
  (505, 6, 'physical', '1 身体的 2 实体的', 'word', NOW(), NOW()),
  (506, 6, 'mental', '1 心理的 2 精神的', 'word', NOW(), NOW()),
  (507, 6, 'president', '1 总统 2 校长总裁', 'word', NOW(), NOW()),
  (508, 6, 'publication', '出版', 'word', NOW(), NOW()),
  (509, 6, 'quality', '品质', 'word', NOW(), NOW()),
  (510, 6, 'reach', '到达', 'word', NOW(), NOW()),
  (511, 6, 'record', '记录', 'word', NOW(), NOW()),
  (512, 6, 'site', '地点', 'word', NOW(), NOW()),
  (513, 6, 'slave', '奴隶', 'word', NOW(), NOW()),
  (514, 6, 'story', '故事', 'word', NOW(), NOW()),
  (515, 6, 'teach', '教', 'word', NOW(), NOW()),
  (516, 6, 'traditional', '传统的', 'word', NOW(), NOW()),
  (517, 6, 'usually', '通常', 'word', NOW(), NOW()),
  (518, 6, 'amateur', '业余', 'word', NOW(), NOW()),
  (519, 6, 'avoid', '避免', 'word', NOW(), NOW()),
  (520, 6, 'bear/stand/end', '忍受', 'word', NOW(), NOW()),
  (521, 6, 'buy', '1 买 2 相信', 'word', NOW(), NOW()),
  (522, 6, 'capacity', '容量', 'word', NOW(), NOW()),
  (523, 6, 'choose', '选择', 'word', NOW(), NOW()),
  (524, 6, 'commercial', '商业的', 'word', NOW(), NOW()),
  (525, 6, 'creative', '有创造力的', 'word', NOW(), NOW()),
  (526, 6, 'database', '数据库', 'word', NOW(), NOW()),
  (527, 6, 'debate', '辩论争论', 'word', NOW(), NOW()),
  (528, 6, 'die', '死', 'word', NOW(), NOW()),
  (529, 6, 'directly', '直接地', 'word', NOW(), NOW()),
  (530, 6, 'discipline', '纪律', 'word', NOW(), NOW()),
  (531, 6, 'DNA', '脱氧核糖核酸', 'word', NOW(), NOW()),
  (532, 6, 'either', '也不', 'word', NOW(), NOW()),
  (533, 6, 'else', '其他的', 'word', NOW(), NOW()),
  (534, 6, 'emerge', '出现，新兴', 'word', NOW(), NOW()),
  (535, 7, 'encourage', '鼓励', 'word', NOW(), NOW()),
  (536, 7, 'energy', '能量，精力', 'word', NOW(), NOW()),
  (537, 7, 'except', '除...以外', 'word', NOW(), NOW()),
  (538, 7, 'expert', '专家', 'word', NOW(), NOW()),
  (539, 7, 'expect', '期待', 'word', NOW(), NOW()),
  (540, 7, 'exist', '存在', 'word', NOW(), NOW()),
  (541, 7, 'expression', '表达', 'word', NOW(), NOW()),
  (542, 7, 'fear', '害怕', 'word', NOW(), NOW()),
  (543, 7, 'feeling', '感受', 'word', NOW(), NOW()),
  (544, 7, 'foreign', '外国的', 'word', NOW(), NOW()),
  (545, 7, 'global', '全球的', 'word', NOW(), NOW()),
  (546, 7, 'hand', '1 .手 2 传递', 'word', NOW(), NOW()),
  (547, 7, 'happy', '快乐', 'word', NOW(), NOW()),
  (548, 7, 'homeless', '无家可归的', 'word', NOW(), NOW()),
  (549, 7, 'increasingly', '越来越的', 'word', NOW(), NOW()),
  (550, 7, 'industrial', '工业的', 'word', NOW(), NOW()),
  (551, 7, 'journalist', '新闻工作者', 'word', NOW(), NOW()),
  (552, 7, 'middle', '中间', 'word', NOW(), NOW()),
  (553, 7, 'money', '钱', 'word', NOW(), NOW()),
  (554, 7, 'name', 'n.名字 V.命名', 'word', NOW(), NOW()),
  (555, 7, 'nothing', '没什么', 'word', NOW(), NOW()),
  (556, 7, 'period', '时期', 'word', NOW(), NOW()),
  (557, 7, 'poetry', '诗歌艺术', 'word', NOW(), NOW()),
  (558, 7, 'predict', '预测', 'word', NOW(), NOW()),
  (559, 7, 'principle', '原则原理', 'word', NOW(), NOW()),
  (560, 7, 'reality', '现实', 'word', NOW(), NOW()),
  (561, 7, 'recent/recently', '最近', 'word', NOW(), NOW()),
  (562, 7, 'response', '回应', 'word', NOW(), NOW()),
  (563, 7, 'return', '返回', 'word', NOW(), NOW()),
  (564, 7, 'shift', '转换', 'word', NOW(), NOW()),
  (565, 7, 'similar', '相似的', 'word', NOW(), NOW()),
  (566, 7, 'speak', '说', 'word', NOW(), NOW()),
  (567, 7, 'spend', '花费', 'word', NOW(), NOW()),
  (568, 7, 'strong', '强大的/强壮的', 'word', NOW(), NOW()),
  (569, 7, 'therefore', '因此', 'word', NOW(), NOW()),
  (570, 7, 'above', '在...之上', 'word', NOW(), NOW()),
  (571, 7, 'advertisement', '广告', 'word', NOW(), NOW()),
  (572, 7, 'advertiser', '广告客户', 'word', NOW(), NOW()),
  (573, 7, 'allow', '允许', 'word', NOW(), NOW()),
  (574, 7, 'analysis', '分析', 'word', NOW(), NOW()),
  (575, 7, 'attempt', '企图 1 板子', 'word', NOW(), NOW()),
  (576, 7, 'board', '2 董事会 3 登交通工具', 'word', NOW(), NOW()),
  (577, 7, 'break', '打破', 'word', NOW(), NOW()),
  (578, 7, 'car', '汽车', 'word', NOW(), NOW()),
  (579, 7, 'conclude', '下结论', 'word', NOW(), NOW()),
  (580, 7, 'cover', '覆盖', 'word', NOW(), NOW()),
  (581, 7, 'degree', '度数/学位', 'word', NOW(), NOW()),
  (582, 7, 'desire', '欲望', 'word', NOW(), NOW()),
  (583, 7, 'determine', '下决心', 'word', NOW(), NOW()),
  (584, 7, 'educate', '教育', 'word', NOW(), NOW()),
  (585, 7, 'enjoy', '享受', 'word', NOW(), NOW()),
  (586, 7, 'establish', '建立', 'word', NOW(), NOW()),
  (587, 7, 'fair', '公平的', 'word', NOW(), NOW()),
  (588, 7, 'hardly', '几乎不', 'word', NOW(), NOW()),
  (589, 7, 'himself', '他自己', 'word', NOW(), NOW()),
  (590, 7, 'historian', '历史学家', 'word', NOW(), NOW()),
  (591, 7, 'identify', '辨认', 'word', NOW(), NOW()),
  (592, 7, 'ignore', '忽略', 'word', NOW(), NOW()),
  (593, 7, 'immigration', '移民', 'word', NOW(), NOW()),
  (594, 7, 'institution', '机构制度', 'word', NOW(), NOW()),
  (595, 7, 'key', 'n.钥匙 adj.关键的', 'word', NOW(), NOW()),
  (596, 7, 'largely', '大大地', 'word', NOW(), NOW()),
  (597, 7, 'local', '当地的', 'word', NOW(), NOW()),
  (598, 7, 'majority', '大多数', 'word', NOW(), NOW()),
  (599, 7, 'mass', '1 质量 2 大量', 'word', NOW(), NOW()),
  (600, 7, 'measure', 'v.测量 n.措施', 'word', NOW(), NOW()),
  (601, 7, 'model', '1 模特 2 模型 3 模范', 'word', NOW(), NOW()),
  (602, 7, 'movement', '1 移动 2 运动', 'word', NOW(), NOW()),
  (603, 7, 'nuclear', '核能的', 'word', NOW(), NOW()),
  (604, 7, 'plant', '1 种植 2 植物', 'word', NOW(), NOW()),
  (605, 7, 'position', '位置职位', 'word', NOW(), NOW()),
  (606, 7, 'push', '1 推 2 逼', 'word', NOW(), NOW()),
  (607, 7, 'railroad', '铁路', 'word', NOW(), NOW()),
  (608, 7, 'reader', '读者', 'word', NOW(), NOW()),
  (609, 7, 'really', '真实地', 'word', NOW(), NOW()),
  (610, 7, 'refer', '涉及', 'word', NOW(), NOW()),
  (611, 7, 'reflect', '1 反映反射 2 深思', 'word', NOW(), NOW()),
  (612, 7, 'relate', '相关', 'word', NOW(), NOW()),
  (613, 7, 'relationship', '关系', 'word', NOW(), NOW()),
  (614, 7, 'respect', '1 尊重 2 方面，', 'word', NOW(), NOW()),
  (615, 7, 'responsible', '负责的', 'word', NOW(), NOW()),
  (616, 7, 'rich', '1 有钱的 2 丰富的', 'word', NOW(), NOW()),
  (617, 7, 'sentence', 'n.句子 V.宣判', 'word', NOW(), NOW()),
  (618, 7, 'sign', 'V.签署 n.符号', 'word', NOW(), NOW()),
  (619, 7, 'simply', '仅仅', 'word', NOW(), NOW()),
  (620, 7, 'stand', '1 站立 2 忍受', 'word', NOW(), NOW()),
  (621, 7, 'stop', '停止', 'word', NOW(), NOW()),
  (622, 7, 'third', '第三', 'word', NOW(), NOW()),
  (623, 7, 'threat', '威胁', 'word', NOW(), NOW()),
  (624, 7, 'threaten', '威胁', 'word', NOW(), NOW()),
  (625, 7, 'title', '标题', 'word', NOW(), NOW()),
  (626, 7, 'track', 'n.轨迹 V.追踪', 'word', NOW(), NOW()),
  (627, 7, 'unique', '独特的', 'word', NOW(), NOW()),
  (628, 7, 'various/variation/ variable/variety', '不同 多样', 'word', NOW(), NOW()),
  (629, 7, 'affect', '影响', 'word', NOW(), NOW()),
  (630, 7, 'effect', '效果', 'word', NOW(), NOW()),
  (631, 7, 'agency', '机构', 'word', NOW(), NOW()),
  (632, 7, 'alone', '独自的', 'word', NOW(), NOW()),
  (633, 7, 'capital', '1 首都 2 资本', 'word', NOW(), NOW()),
  (634, 7, 'career', '事业', 'word', NOW(), NOW()),
  (635, 7, 'complex', '复杂', 'word', NOW(), NOW()),
  (636, 7, 'current', '现在的', 'word', NOW(), NOW()),
  (637, 8, 'deep', '深的', 'word', NOW(), NOW()),
  (638, 8, 'design', '设计', 'word', NOW(), NOW()),
  (639, 8, 'doubt', '怀疑', 'word', NOW(), NOW()),
  (640, 8, 'draw', '1 画 2 引起 吸引', 'word', NOW(), NOW()),
  (641, 8, 'drive', '1 驾驶 2 驱动', 'word', NOW(), NOW()),
  (642, 8, 'everything —', '切', 'word', NOW(), NOW()),
  (643, 8, 'executive', '管理者 执行者', 'word', NOW(), NOW()),
  (644, 8, 'father', '爸爸', 'word', NOW(), NOW()),
  (645, 8, 'friend', '朋友', 'word', NOW(), NOW()),
  (646, 8, 'further', '更远', 'word', NOW(), NOW()),
  (647, 8, 'gain', '获得', 'word', NOW(), NOW()),
  (648, 8, 'height', '高度', 'word', NOW(), NOW()),
  (649, 8, 'imply', '暗示', 'word', NOW(), NOW()),
  (650, 8, 'importance', '重要性', 'word', NOW(), NOW()),
  (651, 8, 'judgment', '判断', 'word', NOW(), NOW()),
  (652, 8, 'lawyer', '律师', 'word', NOW(), NOW()),
  (653, 8, 'link adj.', '链接', 'word', NOW(), NOW()),
  (654, 8, 'light n. v.', '轻的 光', 'word', NOW(), NOW()),
  (655, 8, 'mainly', '点燃 主要的', 'word', NOW(), NOW()),
  (656, 8, 'manager', '经理', 'word', NOW(), NOW()),
  (657, 8, 'near', '附近', 'word', NOW(), NOW()),
  (658, 8, 'net', '网', 'word', NOW(), NOW()),
  (659, 8, 'network', '网络', 'word', NOW(), NOW()),
  (660, 8, 'observe', '观察', 'word', NOW(), NOW()),
  (661, 8, 'obvious', '明显的', 'word', NOW(), NOW()),
  (662, 8, 'occur', '发生', 'word', NOW(), NOW()),
  (663, 8, 'organization', '组织', 'word', NOW(), NOW()),
  (664, 8, 'n. project v.', '项目 投射', 'word', NOW(), NOW()),
  (665, 8, 'promise', '承诺', 'word', NOW(), NOW()),
  (666, 8, 'promote', '1 促进 2 推销', 'word', NOW(), NOW()),
  (667, 8, 'pursuit', '追求', 'word', NOW(), NOW()),
  (668, 8, 'realize', '1 意识到 2 实现', 'word', NOW(), NOW()),
  (669, 8, 'religion', '宗教', 'word', NOW(), NOW()),
  (670, 8, 'religious', '宗教的', 'word', NOW(), NOW()),
  (671, 8, 'review', '1 复习 2 评论', 'word', NOW(), NOW()),
  (672, 8, 'robot', '机器人', 'word', NOW(), NOW()),
  (673, 8, 'slavery', '奴隶制', 'word', NOW(), NOW()),
  (674, 8, 'tradition', '传统', 'word', NOW(), NOW()),
  (675, 8, 'upon', '在 之上', 'word', NOW(), NOW()),
  (676, 8, 'soon', '一会儿', 'word', NOW(), NOW()),
  (677, 8, 'spread', '散播', 'word', NOW(), NOW()),
  (678, 8, 'stay', '逗留', 'word', NOW(), NOW()),
  (679, 8, 'street', '街道', 'word', NOW(), NOW()),
  (680, 8, 'technological', '技术的', 'word', NOW(), NOW()),
  (681, 8, 'tool', '工具', 'word', NOW(), NOW()),
  (682, 8, 'variety', '多样', 'word', NOW(), NOW()),
  (683, 8, 'west', '西方', 'word', NOW(), NOW()),
  (684, 8, 'academic', '学术的', 'word', NOW(), NOW()),
  (685, 8, 'n. aim v.', '目的 瞄准', 'word', NOW(), NOW()),
  (686, 8, 'alter', '改变', 'word', NOW(), NOW()),
  (687, 8, 'amount', '数量', 'word', NOW(), NOW()),
  (688, 8, 'anti-', '反', 'word', NOW(), NOW()),
  (689, 8, 'anyone', '任何人', 'word', NOW(), NOW()),
  (690, 8, 'apply', '1 应用 2 申请', 'word', NOW(), NOW()),
  (691, 8, 'argument', '争论', 'word', NOW(), NOW()),
  (692, 8, 'aspect', '方面 1', 'word', NOW(), NOW()),
  (693, 8, 'authority', '权威 2 权力 3', 'word', NOW(), NOW()),
  (694, 8, 'away', '当局 离去', 'word', NOW(), NOW()),
  (695, 8, 'belief', '信念', 'word', NOW(), NOW()),
  (696, 8, 'below', '在 之下', 'word', NOW(), NOW()),
  (697, 8, 'chance', '1 机会 2 概率', 'word', NOW(), NOW()),
  (698, 8, 'church', '1 教堂 2 教会', 'word', NOW(), NOW()),
  (699, 8, 'communication', '交流', 'word', NOW(), NOW()),
  (700, 8, 'conscious', '1 清醒的 2 有意识的', 'word', NOW(), NOW()),
  (701, 8, 'consumption', '消费', 'word', NOW(), NOW()),
  (702, 8, 'contribute', '贡献', 'word', NOW(), NOW()),
  (703, 8, 'corporation', '大公司', 'word', NOW(), NOW()),
  (704, 8, 'discover', '发现', 'word', NOW(), NOW()),
  (705, 8, 'divide', '划分', 'word', NOW(), NOW()),
  (706, 8, 'drop', '落', 'word', NOW(), NOW()),
  (707, 8, 'easily', '容易地', 'word', NOW(), NOW()),
  (708, 8, 'element', '元素', 'word', NOW(), NOW()),
  (709, 8, 'everyone', '每一个人', 'word', NOW(), NOW()),
  (710, 8, 'express', '1 表达 2 快递', 'word', NOW(), NOW()),
  (711, 8, 'eye', '眼睛', 'word', NOW(), NOW()),
  (712, 8, 'factor', '因素', 'word', NOW(), NOW()),
  (713, 8, 'favor', '偏爱 帮忙', 'word', NOW(), NOW()),
  (714, 8, 'figure', '数字 计算', 'word', NOW(), NOW()),
  (715, 8, 'former', '前者', 'word', NOW(), NOW()),
  (716, 8, 'fully', '完全地', 'word', NOW(), NOW()),
  (717, 8, 'game', '游戏', 'word', NOW(), NOW()),
  (718, 8, 'garden', '花园', 'word', NOW(), NOW()),
  (719, 8, 'grant', '授予', 'word', NOW(), NOW()),
  (720, 8, 'hear', '听到', 'word', NOW(), NOW()),
  (721, 8, 'here', '这', 'word', NOW(), NOW()),
  (722, 8, 'humor', '幽默', 'word', NOW(), NOW()),
  (723, 9, 'hundred', '—百', 'word', NOW(), NOW()),
  (724, 9, 'ill', '生病的', 'word', NOW(), NOW()),
  (725, 9, 'label', 'n.标签 v.打标签', 'word', NOW(), NOW()),
  (726, 9, 'mental', '1 心理的 2 精神的', 'word', NOW(), NOW()),
  (727, 9, 'physical', '1 身体的 2 实体的', 'word', NOW(), NOW()),
  (728, 9, 'mention', '提到', 'word', NOW(), NOW()),
  (729, 9, 'month', '月份', 'word', NOW(), NOW()),
  (730, 9, 'negative', '否定的', 'word', NOW(), NOW()),
  (731, 9, 'positive', '肯定的', 'word', NOW(), NOW()),
  (732, 9, 'original', '原始的', 'word', NOW(), NOW()),
  (733, 9, 'panel', '面板', 'word', NOW(), NOW()),
  (734, 9, 'phenomenon', '现象', 'word', NOW(), NOW()),
  (735, 9, 'politic', '政治', 'word', NOW(), NOW()),
  (736, 9, 'powerful', '强大的', 'word', NOW(), NOW()),
  (737, 9, 'private', '私人的', 'word', NOW(), NOW()),
  (738, 9, 'sale', '销售', 'word', NOW(), NOW()),
  (739, 9, 'progress', '进步', 'word', NOW(), NOW()),
  (740, 9, 'range', '范围', 'word', NOW(), NOW()),
  (741, 9, 'relation', '关系', 'word', NOW(), NOW()),
  (742, 9, 'respond', '反应', 'word', NOW(), NOW()),
  (743, 9, 'root', '根', 'word', NOW(), NOW()),
  (744, 9, 'security', '安全', 'word', NOW(), NOW()),
  (745, 9, 'shareholder', '股东', 'word', NOW(), NOW()),
  (746, 9, 'shop', 'n.商店 V.购物', 'word', NOW(), NOW()),
  (747, 9, 'sort', 'n.种类 v.分类', 'word', NOW(), NOW()),
  (748, 9, 'source', '来源', 'word', NOW(), NOW()),
  (749, 9, 'south', '南方', 'word', NOW(), NOW()),
  (750, 9, 'special', '特别的', 'word', NOW(), NOW()),
  (751, 9, 'status', '地位', 'word', NOW(), NOW()),
  (752, 9, 'stick', 'n•棍子', 'word', NOW(), NOW()),
  (753, 9, 'stick to', 'v.粘连 坚持', 'word', NOW(), NOW()),
  (754, 9, 'stock', '股份', 'word', NOW(), NOW()),
  (755, 9, 'store', 'n.商店 v.储存', 'word', NOW(), NOW()),
  (756, 9, 'teacher', 'n.老师', 'word', NOW(), NOW()),
  (757, 9, 'type', 'n.种类 v.打字', 'word', NOW(), NOW()),
  (758, 9, 'universe', '宇宙', 'word', NOW(), NOW()),
  (759, 9, 'usual', '通常', 'word', NOW(), NOW()),
  (760, 9, 'wave/trend/tide', '潮流', 'word', NOW(), NOW()),
  (761, 9, 'whole', '整个的', 'word', NOW(), NOW()),
  (762, 9, 'wide/?', '宽的', 'word', NOW(), NOW()),
  (763, 9, 'access', '进入', 'word', NOW(), NOW()),
  (764, 9, 'actually', '其实', 'word', NOW(), NOW()),
  (765, 9, 'along', '沿着', 'word', NOW(), NOW()),
  (766, 9, 'anthropology', '人类学', 'word', NOW(), NOW()),
  (767, 9, 'appeal', '恳求', 'word', NOW(), NOW()),
  (768, 9, 'behavioral', '行为的', 'word', NOW(), NOW()),
  (769, 9, 'bill', '1 账单 2 钞票', 'word', NOW(), NOW()),
  (770, 9, 'celebrity', '名人', 'word', NOW(), NOW()),
  (771, 9, 'comment', '评论', 'word', NOW(), NOW()),
  (772, 9, 'confuse', '使困惑', 'word', NOW(), NOW()),
  (773, 9, 'continent', '大陆大洲', 'word', NOW(), NOW()),
  (774, 9, 'credibility', '可信性', 'word', NOW(), NOW()),
  (775, 9, 'cure', '治愈', 'word', NOW(), NOW()),
  (776, 9, 'daily', '日常的', 'word', NOW(), NOW()),
  (777, 9, 'decide', '决定', 'word', NOW(), NOW()),
  (778, 9, 'despite', '尽管', 'word', NOW(), NOW()),
  (779, 9, 'draft', '草稿', 'word', NOW(), NOW()),
  (780, 9, 'earth', '地球', 'word', NOW(), NOW()),
  (781, 9, 'emotional', '情绪的', 'word', NOW(), NOW()),
  (782, 9, 'emphasize', '强调', 'word', NOW(), NOW()),
  (783, 9, 'exercise', '练习', 'word', NOW(), NOW()),
  (784, 9, 'fill', '填充', 'word', NOW(), NOW()),
  (785, 9, 'fish', '鱼', 'word', NOW(), NOW()),
  (786, 9, 'fishery', '渔业', 'word', NOW(), NOW()),
  (787, 9, 'formal/former', '正式的/前任的', 'word', NOW(), NOW()),
  (788, 9, 'four', '四', 'word', NOW(), NOW()),
  (789, 9, 'highly', '咼度地', 'word', NOW(), NOW()),
  (790, 9, 'historical', '历史的', 'word', NOW(), NOW()),
  (791, 9, 'hope', '希望', 'word', NOW(), NOW()),
  (792, 9, 'income', '收入', 'word', NOW(), NOW()),
  (793, 9, 'indeed', '确实', 'word', NOW(), NOW()),
  (794, 9, 'independent', '独立的', 'word', NOW(), NOW()),
  (795, 9, 'invention', '发明', 'word', NOW(), NOW()),
  (796, 9, 'justify', '证明', 'word', NOW(), NOW()),
  (797, 9, 'material', '物质的', 'word', NOW(), NOW()),
  (798, 9, 'me', '我', 'word', NOW(), NOW()),
  (799, 9, 'medicine', '药', 'word', NOW(), NOW()),
  (800, 9, 'moreover', '而且', 'word', NOW(), NOW()),
  (801, 9, 'nearly', '几乎', 'word', NOW(), NOW()),
  (802, 9, 'neglect/ignore', '忽视', 'word', NOW(), NOW()),
  (803, 9, 'observer', '观察者', 'word', NOW(), NOW()),
  (804, 9, 'official', '官方的', 'word', NOW(), NOW()),
  (805, 9, 'oppose', '反对', 'word', NOW(), NOW()),
  (806, 9, 'particularly', '尤其', 'word', NOW(), NOW()),
  (807, 9, 'philosopher', '哲学家', 'word', NOW(), NOW()),
  (808, 9, 'picture', '图画', 'word', NOW(), NOW()),
  (809, 9, 'player', '玩家', 'word', NOW(), NOW()),
  (810, 9, 'press', 'v.按压 n.新闻', 'word', NOW(), NOW()),
  (811, 9, 'prospect', '前景', 'word', NOW(), NOW()),
  (812, 9, 'protection', '保护', 'word', NOW(), NOW()),
  (813, 9, 'province', '省', 'word', NOW(), NOW()),
  (814, 9, 'recognize', '认出', 'word', NOW(), NOW()),
  (815, 9, 'rely', '依赖', 'word', NOW(), NOW()),
  (816, 9, 'remember', '记得', 'word', NOW(), NOW()),
  (817, 9, 'replace', '代替', 'word', NOW(), NOW()),
  (818, 9, 'resource', '资源', 'word', NOW(), NOW()),
  (819, 9, 'retailer', '零售商', 'word', NOW(), NOW()),
  (820, 9, 'safety', '安全', 'word', NOW(), NOW()),
  (821, 9, 'secure', '安全的', 'word', NOW(), NOW()),
  (822, 9, 'senior', '年长的', 'word', NOW(), NOW()),
  (823, 9, 'serve', '服务', 'word', NOW(), NOW()),
  (824, 9, 'side', '边', 'word', NOW(), NOW()),
  (825, 9, 'sleep', '睡觉', 'word', NOW(), NOW()),
  (826, 10, 'specific', '明确的，具体的', 'word', NOW(), NOW()),
  (827, 10, 'statement', '陈述，声明', 'word', NOW(), NOW()),
  (828, 10, 'successful', '成功的', 'word', NOW(), NOW()),
  (829, 10, 'sure', '当然，确信的', 'word', NOW(), NOW()),
  (830, 10, 'surprise', '惊喜，惊讶', 'word', NOW(), NOW()),
  (831, 10, 'survive', '幸存', 'word', NOW(), NOW()),
  (832, 10, 'technical', '工艺的，技术的', 'word', NOW(), NOW()),
  (833, 10, 'travel', '旅行', 'word', NOW(), NOW()),
  (834, 10, 'visit', '拜访', 'word', NOW(), NOW()),
  (835, 10, 'warn', '警告', 'word', NOW(), NOW()),
  (836, 10, 'white', '白的', 'word', NOW(), NOW()),
  (837, 10, 'widely', '宽泛的', 'word', NOW(), NOW()),
  (838, 10, 'win', '赢得', 'word', NOW(), NOW()),
  (839, 10, 'wrong', '错的', 'word', NOW(), NOW()),
  (840, 10, 'achievement', '成就', 'word', NOW(), NOW()),
  (841, 10, 'administratio', '管理', 'word', NOW(), NOW()),
  (842, 10, 'answer', '回答', 'word', NOW(), NOW()),
  (843, 10, 'arise', '产生，出现', 'word', NOW(), NOW()),
  (844, 10, 'association', '协会', 'word', NOW(), NOW()),
  (845, 10, 'behind', '在……后面', 'word', NOW(), NOW()),
  (846, 10, 'bias', '偏斜的，偏见', 'word', NOW(), NOW()),
  (847, 10, 'boom', '激增', 'word', NOW(), NOW()),
  (848, 10, 'broad', '辽阔的', 'word', NOW(), NOW()),
  (849, 10, 'catch', '捉住，追上', 'word', NOW(), NOW()),
  (850, 10, 'center', '中心', 'word', NOW(), NOW()),
  (851, 10, 'CEO', '首席执行官', 'word', NOW(), NOW()),
  (852, 10, 'chairman', '主席', 'word', NOW(), NOW()),
  (853, 10, 'chemical', '化学的', 'word', NOW(), NOW()),
  (854, 10, 'chief', '主要的', 'word', NOW(), NOW()),
  (855, 10, 'city', '城市', 'word', NOW(), NOW()),
  (856, 10, 'climate', '气候', 'word', NOW(), NOW()),
  (857, 10, 'congress', '国会', 'word', NOW(), NOW()),
  (858, 10, 'convince', '说服', 'word', NOW(), NOW()),
  (859, 10, 'crime', '犯罪', 'word', NOW(), NOW()),
  (860, 10, 'cut', '切割', 'word', NOW(), NOW()),
  (861, 10, 'description', '描述', 'word', NOW(), NOW()),
  (862, 10, 'detail', '细节', 'word', NOW(), NOW()),
  (863, 10, 'direct', 'v.指方向 adj.直接的', 'word', NOW(), NOW()),
  (864, 10, 'direction', '方向', 'word', NOW(), NOW()),
  (865, 10, 'director', '董事、主任、主管', 'word', NOW(), NOW()),
  (866, 10, 'disease', '疾病', 'word', NOW(), NOW()),
  (867, 10, 'drink', 'n.饮料 v.喝', 'word', NOW(), NOW()),
  (868, 10, 'economist', '经济学家', 'word', NOW(), NOW()),
  (869, 10, 'educational', '教育的', 'word', NOW(), NOW()),
  (870, 10, 'emphasis', '重点', 'word', NOW(), NOW()),
  (871, 10, 'entirely', '完全地', 'word', NOW(), NOW()),
  (872, 10, 'escape', '逃跑', 'word', NOW(), NOW()),
  (873, 10, 'event', '事件', 'word', NOW(), NOW()),
  (874, 10, 'exchange', '交换', 'word', NOW(), NOW()),
  (875, 10, 'explanation', '解释', 'word', NOW(), NOW()),
  (876, 10, 'female', '女性', 'word', NOW(), NOW()),
  (877, 10, 'join', '加入，参加', 'word', NOW(), NOW()),
  (878, 10, 'fit', '合适的', 'word', NOW(), NOW()),
  (879, 10, 'five', '五', 'word', NOW(), NOW()),
  (880, 10, 'flow', '流动', 'word', NOW(), NOW()),
  (881, 10, 'frequently', '频繁地', 'word', NOW(), NOW()),
  (882, 10, 'full', '满的', 'word', NOW(), NOW()),
  (883, 10, 'futurist', '未来主义者', 'word', NOW(), NOW()),
  (884, 10, 'heavy', '厚重的', 'word', NOW(), NOW()),
  (885, 10, 'illustrate', '阐明', 'word', NOW(), NOW()),
  (886, 10, 'immediate', '立即的', 'word', NOW(), NOW()),
  (887, 10, 'impact', '影响', 'word', NOW(), NOW()),
  (888, 10, 'inevitable', '不可避免的', 'word', NOW(), NOW()),
  (889, 10, 'innovation', '革新', 'word', NOW(), NOW()),
  (890, 10, 'intellect', '智力，才华', 'word', NOW(), NOW()),
  (891, 10, 'journalism', '新闻业', 'word', NOW(), NOW()),
  (892, 10, 'judge', 'v.判断 v.评头论足', 'word', NOW(), NOW()),
  (893, 10, 'jump', 'n.法官 跳', 'word', NOW(), NOW()),
  (894, 10, 'kill', '杀', 'word', NOW(), NOW()),
  (895, 10, 'letter', '字母，信', 'word', NOW(), NOW()),
  (896, 10, 'lie', '1 躺 2 谎言', 'word', NOW(), NOW()),
  (897, 10, 'magazine', '杂志', 'word', NOW(), NOW()),
  (898, 10, 'maintain', '维持，保养', 'word', NOW(), NOW()),
  (899, 10, 'manner', '1 方式 2 礼貌', 'word', NOW(), NOW()),
  (900, 10, 'objective', '客观的，目标', 'word', NOW(), NOW()),
  (901, 10, 'optimistic', '乐观的', 'word', NOW(), NOW()),
  (902, 10, 'otherwise', '否则', 'word', NOW(), NOW()),
  (903, 10, 'overall', '总共', 'word', NOW(), NOW()),
  (904, 10, 'payment', '支付', 'word', NOW(), NOW()),
  (905, 10, 'planet', '星球', 'word', NOW(), NOW()),
  (906, 10, 'poverty', '贫困', 'word', NOW(), NOW()),
  (907, 10, 'prevent', '预防', 'word', NOW(), NOW()),
  (908, 10, 'publisher', '出版商', 'word', NOW(), NOW()),
  (909, 10, 'quit', '离开，停止', 'word', NOW(), NOW()),
  (910, 10, 'radical', '激进的', 'word', NOW(), NOW()),
  (911, 10, 'reform', '改革', 'word', NOW(), NOW()),
  (912, 10, 'reject', '拒绝', 'word', NOW(), NOW()),
  (913, 10, 'remove', '消除', 'word', NOW(), NOW()),
  (914, 10, 'responsibilit', '责任', 'word', NOW(), NOW()),
  (915, 10, 'rest', '休息', 'word', NOW(), NOW()),
  (916, 10, 'safe', '安全', 'word', NOW(), NOW()),
  (917, 10, 'separate', '使分离', 'word', NOW(), NOW()),
  (918, 10, 'serious', '1 严重的 2 严肃的', 'word', NOW(), NOW()),
  (919, 10, 'shape', 'n.形状 v.塑造', 'word', NOW(), NOW()),
  (920, 10, 'soccer', '足球', 'word', NOW(), NOW()),
  (921, 10, 'sometimes', '有时', 'word', NOW(), NOW()),
  (922, 11, 'speed', '速度', 'word', NOW(), NOW()),
  (923, 11, 'step', '1 步子 2 走', 'word', NOW(), NOW()),
  (924, 11, 'suicide', '自杀', 'word', NOW(), NOW()),
  (925, 11, 'supply', '供应', 'word', NOW(), NOW()),
  (926, 11, 'suppose', '假定，认为', 'word', NOW(), NOW()),
  (927, 11, 'user', '用户', 'word', NOW(), NOW()),
  (928, 11, 'treatment', '治疗，对待', 'word', NOW(), NOW()),
  (929, 11, 'trouble', '麻烦', 'word', NOW(), NOW()),
  (930, 11, 'unless', '除非', 'word', NOW(), NOW()),
  (931, 11, 'urge', '力劝，渴望', 'word', NOW(), NOW()),
  (932, 11, 'wealth', '财富', 'word', NOW(), NOW()),
  (933, 11, 'wholesale', '批发', 'word', NOW(), NOW()),
  (934, 11, 'workforce', '劳动力', 'word', NOW(), NOW()),
  (935, 11, 'abuse', '1 滥用 2 虐待', 'word', NOW(), NOW()),
  (936, 11, 'acquire', '获得，购得', 'word', NOW(), NOW()),
  (937, 11, 'advertise', '广告', 'word', NOW(), NOW()),
  (938, 11, 'again', '再一次', 'word', NOW(), NOW()),
  (939, 11, 'agreement', '共识，协定', 'word', NOW(), NOW()),
  (940, 11, 'anthropologist', '人类学家', 'word', NOW(), NOW()),
  (941, 11, 'appropriate', '恰当的，合适的', 'word', NOW(), NOW()),
  (942, 11, 'assume', '假设', 'word', NOW(), NOW()),
  (943, 11, 'attract', '吸引', 'word', NOW(), NOW()),
  (944, 11, 'ban', '禁止，禁令', 'word', NOW(), NOW()),
  (945, 11, 'audience', '听众，观众', 'word', NOW(), NOW()),
  (946, 11, 'background', '背景', 'word', NOW(), NOW()),
  (947, 11, 'biological', '生物的', 'word', NOW(), NOW()),
  (948, 11, 'birth', '出生', 'word', NOW(), NOW()),
  (949, 11, 'bite', '咬', 'word', NOW(), NOW()),
  (950, 11, 'category', '种类', 'word', NOW(), NOW()),
  (951, 11, 'channel', '频道，途径', 'word', NOW(), NOW()),
  (952, 11, 'characteristic', '特征', 'word', NOW(), NOW()),
  (953, 11, 'characterize', '具有……特征', 'word', NOW(), NOW()),
  (954, 11, 'check', '1 检查 2 制止', 'word', NOW(), NOW()),
  (955, 11, 'circuit', '电路，环线', 'word', NOW(), NOW()),
  (956, 11, 'circumstance', '状况，情形', 'word', NOW(), NOW()),
  (957, 11, 'colleague', '同事', 'word', NOW(), NOW()),
  (958, 11, 'commit', '1 承诺 2 犯下', 'word', NOW(), NOW()),
  (959, 11, 'competitive', '竞争的', 'word', NOW(), NOW()),
  (960, 11, 'complete', '完成，完整的', 'word', NOW(), NOW()),
  (961, 11, 'completely', '完全地，彻底地', 'word', NOW(), NOW()),
  (962, 11, 'conflict', '冲突，矛盾', 'word', NOW(), NOW()),
  (963, 11, 'conventional', '惯例的', 'word', NOW(), NOW()),
  (964, 11, 'creation', '创造，作品', 'word', NOW(), NOW()),
  (965, 11, 'crucial', '关键的', 'word', NOW(), NOW()),
  (966, 11, 'crude', '粗略的', 'word', NOW(), NOW()),
  (967, 11, 'department', '部门', 'word', NOW(), NOW()),
  (968, 11, 'digital', '数码的', 'word', NOW(), NOW()),
  (969, 11, 'direction', '方向', 'word', NOW(), NOW()),
  (970, 11, 'distribution', '分配，分布', 'word', NOW(), NOW()),
  (971, 11, 'dollar', '美元', 'word', NOW(), NOW()),
  (972, 11, 'due to', '由于', 'word', NOW(), NOW()),
  (973, 11, 'eat', '吃', 'word', NOW(), NOW()),
  (974, 11, 'electronic', '电子的', 'word', NOW(), NOW()),
  (975, 11, 'e-mail', '电子邮件', 'word', NOW(), NOW()),
  (976, 11, 'embryo', '胚胎', 'word', NOW(), NOW()),
  (977, 11, 'emotion', '情绪', 'word', NOW(), NOW()),
  (978, 11, 'employ', '雇佣，采取', 'word', NOW(), NOW()),
  (979, 11, 'employment', '就业', 'word', NOW(), NOW()),
  (980, 11, 'enable', '使……能够', 'word', NOW(), NOW()),
  (981, 11, 'engage', '参与', 'word', NOW(), NOW()),
  (982, 11, 'equal', '平等的，等于', 'word', NOW(), NOW()),
  (983, 11, 'examine', '检查', 'word', NOW(), NOW()),
  (984, 11, 'expose', '暴露，接触', 'word', NOW(), NOW()),
  (985, 11, 'fight', '斗争，打', 'word', NOW(), NOW()),
  (986, 11, 'finally', '终于', 'word', NOW(), NOW()),
  (987, 11, 'generate', '产生', 'word', NOW(), NOW()),
  (988, 11, 'geological', '地质学的', 'word', NOW(), NOW()),
  (989, 11, 'health-care', '医疗服务', 'word', NOW(), NOW()),
  (990, 11, 'ideal', '理想', 'word', NOW(), NOW()),
  (991, 11, 'implication', '影响，后果，暗示', 'word', NOW(), NOW()),
  (992, 11, 'indicate', '表明', 'word', NOW(), NOW()),
  (993, 11, 'infrastructure', '基础设施', 'word', NOW(), NOW()),
  (994, 11, 'insist', '坚持', 'word', NOW(), NOW()),
  (995, 11, 'insurance', '保险', 'word', NOW(), NOW()),
  (996, 11, 'land', '土地', 'word', NOW(), NOW()),
  (997, 11, 'laugh', '笑', 'word', NOW(), NOW()),
  (998, 11, 'lifestyle', '生活方式', 'word', NOW(), NOW()),
  (999, 11, 'love', '爱', 'word', NOW(), NOW()),
  (1000, 11, 'literature', '文学', 'word', NOW(), NOW()),
  (1001, 11, 'manage', '1 管理 2 应对，处理', 'word', NOW(), NOW()),
  (1002, 11, 'mark', '标记', 'word', NOW(), NOW()),
  (1003, 11, 'mechanical', '机械的', 'word', NOW(), NOW()),
  (1004, 11, 'memory', '记忆', 'word', NOW(), NOW()),
  (1005, 11, 'sit', '坐', 'word', NOW(), NOW()),
  (1006, 11, 'mostly', '大多', 'word', NOW(), NOW()),
  (1007, 11, 'native', '土生土长的', 'word', NOW(), NOW()),
  (1008, 11, 'night', '夜', 'word', NOW(), NOW()),
  (1009, 11, 'notion', '观念', 'word', NOW(), NOW()),
  (1010, 11, 'object', '物体，反对', 'word', NOW(), NOW()),
  (1011, 11, 'obtain', '获得', 'word', NOW(), NOW()),
  (1012, 11, 'office', '办公室', 'word', NOW(), NOW()),
  (1013, 11, 'opposite', '相反的', 'word', NOW(), NOW()),
  (1014, 11, 'parallel', '平行的', 'word', NOW(), NOW()),
  (1015, 11, 'performance', '1 表现，性能 2 表演', 'word', NOW(), NOW()),
  (1016, 11, 'physician', '医生', 'word', NOW(), NOW()),
  (1017, 11, 'popularity', '受欢迎度', 'word', NOW(), NOW()),
  (1018, 11, 'positive/ negative', '正/负', 'word', NOW(), NOW()),
  (1019, 11, 'possibility', '可能性', 'word', NOW(), NOW()),
  (1020, 11, 'practical', '实际的，实用的', 'word', NOW(), NOW()),
  (1021, 11, 'presence', '到场，存在', 'word', NOW(), NOW()),
  (1022, 11, 'primary', '首要的，初级的', 'word', NOW(), NOW()),
  (1023, 11, 'professor', '教授', 'word', NOW(), NOW()),
  (1024, 11, 'propose', '提议', 'word', NOW(), NOW()),
  (1025, 11, 'purchase', '购买', 'word', NOW(), NOW()),
  (1026, 11, 'purpose', '目的', 'word', NOW(), NOW()),
  (1027, 11, 'quickly', '快', 'word', NOW(), NOW()),
  (1028, 11, 'quite', '相当的', 'word', NOW(), NOW()),
  (1029, 12, 'ready', '准备好的', 'word', NOW(), NOW()),
  (1030, 12, 'requirement', '要求', 'word', NOW(), NOW()),
  (1031, 12, 'retail', '零售', 'word', NOW(), NOW()),
  (1032, 12, 'revival', '复兴', 'word', NOW(), NOW()),
  (1033, 12, 'reward', '回报', 'word', NOW(), NOW()),
  (1034, 12, 'scale', '规模', 'word', NOW(), NOW()),
  (1035, 12, 'scholar', '学者', 'word', NOW(), NOW()),
  (1036, 12, 'sensitive', '敏感的', 'word', NOW(), NOW()),
  (1037, 12, 'shock', '震惊', 'word', NOW(), NOW()),
  (1038, 12, 'short', '短，缺', 'word', NOW(), NOW()),
  (1039, 12, 'significant', '重大的', 'word', NOW(), NOW()),
  (1040, 12, 'size', '尺寸，规模', 'word', NOW(), NOW()),
  (1041, 12, 'smile', '笑', 'word', NOW(), NOW()),
  (1042, 12, 'smoke', '烟，抽', 'word', NOW(), NOW()),
  (1043, 12, 'sound', 'n.声音 adj.好的', 'word', NOW(), NOW()),
  (1044, 12, 'statistic', '统计', 'word', NOW(), NOW()),
  (1045, 12, 'supreme', '最高', 'word', NOW(), NOW()),
  (1046, 12, 'theater', '剧院', 'word', NOW(), NOW()),
  (1047, 12, 'thousand', '千', 'word', NOW(), NOW()),
  (1048, 12, 'town', '城镇', 'word', NOW(), NOW()),
  (1049, 12, 'townsfolk', '市民', 'word', NOW(), NOW()),
  (1050, 12, 'tree', '树', 'word', NOW(), NOW()),
  (1051, 12, 'trust', '信任', 'word', NOW(), NOW()),
  (1052, 12, 'truth', '真相', 'word', NOW(), NOW()),
  (1053, 12, 'universal', '普遍的', 'word', NOW(), NOW()),
  (1054, 12, 'wait', '等', 'word', NOW(), NOW()),
  (1055, 12, 'unlikely', '不太可能的', 'word', NOW(), NOW()),
  (1056, 12, 'wake', '醒', 'word', NOW(), NOW()),
  (1057, 12, 'wish', '希望', 'word', NOW(), NOW()),
  (1058, 12, 'witness', '1 见证 2 目睹', 'word', NOW(), NOW()),
  (1059, 12, 'worth', '价值，值', 'word', NOW(), NOW()),
  (1060, 12, 'abandon', '抛弃，放弃', 'word', NOW(), NOW()),
  (1061, 12, 'afford', '负担得起', 'word', NOW(), NOW()),
  (1062, 12, 'alphabetically', '字母顺序的', 'word', NOW(), NOW()),
  (1063, 12, 'apparently', '显然的', 'word', NOW(), NOW()),
  (1064, 12, 'attractive', '有吸引力的', 'word', NOW(), NOW()),
  (1065, 12, 'biomass', '生物总量', 'word', NOW(), NOW()),
  (1066, 12, 'blame', '责怪', 'word', NOW(), NOW()),
  (1067, 12, 'blueprint', '蓝图', 'word', NOW(), NOW()),
  (1068, 12, 'buyer', '买家', 'word', NOW(), NOW()),
  (1069, 12, 'campaign', '活动', 'word', NOW(), NOW()),
  (1070, 12, 'capable', '能够的', 'word', NOW(), NOW()),
  (1071, 12, 'cell', '细胞', 'word', NOW(), NOW()),
  (1072, 12, 'charge', '管理，收费，控告，充', 'word', NOW(), NOW()),
  (1073, 12, 'choice', '选择', 'word', NOW(), NOW()),
  (1074, 12, 'clearly', '清晰的', 'word', NOW(), NOW()),
  (1075, 12, 'code', 'n.代码 v.编码', 'word', NOW(), NOW()),
  (1076, 12, 'collection', '收集', 'word', NOW(), NOW()),
  (1077, 12, 'conservation', '保护', 'word', NOW(), NOW()),
  (1078, 12, 'conservative', '保守的', 'word', NOW(), NOW()),
  (1079, 12, 'content', '1 内容 2 满意的', 'word', NOW(), NOW()),
  (1080, 12, 'convention', '大会，惯例', 'word', NOW(), NOW()),
  (1081, 12, 'cope', '处理', 'word', NOW(), NOW()),
  (1082, 12, 'creationism', '创造论', 'word', NOW(), NOW()),
  (1083, 12, 'creationist', '创造论者', 'word', NOW(), NOW()),
  (1084, 12, 'creativity', '创造力', 'word', NOW(), NOW()),
  (1085, 12, 'critical', '1 批评的 2 关键的', 'word', NOW(), NOW()),
  (1086, 12, 'danger', '3 审慎的，有判断力的 危险', 'word', NOW(), NOW()),
  (1087, 12, 'definition', '定义', 'word', NOW(), NOW()),
  (1088, 12, 'demonstrate', '证明，表现', 'word', NOW(), NOW()),
  (1089, 12, 'deny', '否认', 'word', NOW(), NOW()),
  (1090, 12, 'dependent', '依赖的', 'word', NOW(), NOW()),
  (1091, 12, 'domestic', '国内的', 'word', NOW(), NOW()),
  (1092, 12, 'dominant', '主宰的，统治的', 'word', NOW(), NOW()),
  (1093, 12, 'duty', '1 义务职责 2 税', 'word', NOW(), NOW()),
  (1094, 12, 'dynamic', '动态的', 'word', NOW(), NOW()),
  (1095, 12, 'employer/employee', '老板/员工', 'word', NOW(), NOW()),
  (1096, 12, 'enforcement', '执行，实施', 'word', NOW(), NOW()),
  (1097, 12, 'enter', '1 进入', 'word', NOW(), NOW()),
  (1098, 12, 'enter', '2 输入', 'word', NOW(), NOW()),
  (1099, 12, 'equally', '均等的', 'word', NOW(), NOW()),
  (1100, 12, 'error', '错误', 'word', NOW(), NOW()),
  (1101, 12, 'estimate', '估计', 'word', NOW(), NOW()),
  (1102, 12, 'eventually', '最终地', 'word', NOW(), NOW()),
  (1103, 12, 'everyday', 'adj.日常的', 'word', NOW(), NOW()),
  (1104, 12, 'evolutionary', '进化的', 'word', NOW(), NOW()),
  (1105, 12, 'evolve', '进化', 'word', NOW(), NOW()),
  (1106, 12, 'existence', '存在', 'word', NOW(), NOW()),
  (1107, 12, 'explore', '探索', 'word', NOW(), NOW()),
  (1108, 12, 'extend', '延伸，延续，扩大', 'word', NOW(), NOW()),
  (1109, 12, 'extent', '程度', 'word', NOW(), NOW()),
  (1110, 12, 'extremely', '极度地', 'word', NOW(), NOW()),
  (1111, 12, 'forget', '忘记', 'word', NOW(), NOW()),
  (1112, 12, 'fulfill', '1 满足 2 实现', 'word', NOW(), NOW()),
  (1113, 12, 'gather', '聚集', 'word', NOW(), NOW()),
  (1114, 12, 'giant', '巨大的', 'word', NOW(), NOW()),
  (1115, 12, 'harmful', '有害的', 'word', NOW(), NOW()),
  (1116, 12, 'head', '1 头 2 朝……行进', 'word', NOW(), NOW()),
  (1117, 12, 'hijack', '劫持', 'word', NOW(), NOW()),
  (1118, 12, 'hour', '小时', 'word', NOW(), NOW()),
  (1119, 12, 'imagine', '想象', 'word', NOW(), NOW()),
  (1120, 12, 'injury', '外伤', 'word', NOW(), NOW()),
  (1121, 12, 'for instance', '举例', 'word', NOW(), NOW()),
  (1122, 12, 'integrate', '合并，融合', 'word', NOW(), NOW()),
  (1123, 12, 'invite', '邀请', 'word', NOW(), NOW()),
  (1124, 12, 'laughter', '笑', 'word', NOW(), NOW()),
  (1125, 12, 'let', '让', 'word', NOW(), NOW()),
  (1126, 12, 'liability', '负担', 'word', NOW(), NOW()),
  (1127, 12, 'marketermatch##', '市场营销者 1 比赛 2 配对 3 火柴', 'word', NOW(), NOW()),
  (1128, 13, 'mere', '仅仅', 'word', NOW(), NOW()),
  (1129, 13, 'merger', '合并', 'word', NOW(), NOW()),
  (1130, 13, 'mode', '模式', 'word', NOW(), NOW()),
  (1131, 13, 'moment', '时刻，瞬间', 'word', NOW(), NOW()),
  (1132, 13, 'motion', '移动，运动', 'word', NOW(), NOW()),
  (1133, 13, 'narrow', '窄', 'word', NOW(), NOW()),
  (1134, 13, 'negotiate', '谈判，协商', 'word', NOW(), NOW()),
  (1135, 13, 'newly', '新近', 'word', NOW(), NOW()),
  (1136, 13, 'nineteenth', '第十九', 'word', NOW(), NOW()),
  (1137, 13, 'none', '没有', 'word', NOW(), NOW()),
  (1138, 13, 'ocean', '海', 'word', NOW(), NOW()),
  (1139, 13, 'odd', '奇怪', 'word', NOW(), NOW()),
  (1140, 13, 'officer', '官员', 'word', NOW(), NOW()),
  (1141, 13, 'operate', '1 操作 2 运转', 'word', NOW(), NOW()),
  (1142, 13, 'page', '页面', 'word', NOW(), NOW()),
  (1143, 13, 'partner', '搭档，合伙人', 'word', NOW(), NOW()),
  (1144, 13, 'performer', '表演者', 'word', NOW(), NOW()),
  (1145, 13, 'phrase', '短语；习语', 'word', NOW(), NOW()),
  (1146, 13, 'politician', '政客', 'word', NOW(), NOW()),
  (1147, 13, 'possibly', '可能的', 'word', NOW(), NOW()),
  (1148, 13, 'post preserve', 'n.邮政 v.发帖 保护；维持', 'word', NOW(), NOW()),
  (1149, 13, 'previous', '先前的', 'word', NOW(), NOW()),
  (1150, 13, 'properly', '正确地', 'word', NOW(), NOW()),
  (1151, 13, 'property', '财产', 'word', NOW(), NOW()),
  (1152, 13, 'psychology', '心理学', 'word', NOW(), NOW()),
  (1153, 13, 'puzzle', '困惑；谜题', 'word', NOW(), NOW()),
  (1154, 13, 'regulation', '规章制度', 'word', NOW(), NOW()),
  (1155, 13, 'remark', '评论', 'word', NOW(), NOW()),
  (1156, 13, 'represent', '代表', 'word', NOW(), NOW()),
  (1157, 13, 'reputation', '名誉；声望', 'word', NOW(), NOW()),
  (1158, 13, 'revenue/income', '收入', 'word', NOW(), NOW()),
  (1159, 13, 'revolution', '革命', 'word', NOW(), NOW()),
  (1160, 13, 'royal', '皇室的', 'word', NOW(), NOW()),
  (1161, 13, 'loyal', '忠诚的', 'word', NOW(), NOW()),
  (1162, 13, 'satisfy', '满足', 'word', NOW(), NOW()),
  (1163, 13, 'sector', '领域', 'word', NOW(), NOW()),
  (1164, 13, 'select', '选择', 'word', NOW(), NOW()),
  (1165, 13, 'selection', '选择', 'word', NOW(), NOW()),
  (1166, 13, 'series', '一系列', 'word', NOW(), NOW()),
  (1167, 13, 'seven', '七', 'word', NOW(), NOW()),
  (1168, 13, 'significance', '重要性', 'word', NOW(), NOW()),
  (1169, 13, 'slow', '慢的', 'word', NOW(), NOW()),
  (1170, 13, 'solve', '解决', 'word', NOW(), NOW()),
  (1171, 13, 'someone', '某人', 'word', NOW(), NOW()),
  (1172, 13, 'sport', '体育运动', 'word', NOW(), NOW()),
  (1173, 13, 'spy', '间谍', 'word', NOW(), NOW()),
  (1174, 13, 'strain', '损伤', 'word', NOW(), NOW()),
  (1175, 13, 'strategy', '策略；战略', 'word', NOW(), NOW()),
  (1176, 13, 'struggle', '1 奋斗 2 挣扎', 'word', NOW(), NOW()),
  (1177, 13, 'sustain', '持续；维持', 'word', NOW(), NOW()),
  (1178, 13, 'task', '任务', 'word', NOW(), NOW()),
  (1179, 13, 'mission', '任务', 'word', NOW(), NOW()),
  (1180, 13, 'teenager', '青少年', 'word', NOW(), NOW()),
  (1181, 13, 'thought', '想法', 'word', NOW(), NOW()),
  (1182, 13, 'topic', '话题', 'word', NOW(), NOW()),
  (1183, 13, 'toward', '朝着；向着', 'word', NOW(), NOW()),
  (1184, 13, 'trace', '查找；追溯', 'word', NOW(), NOW()),
  (1185, 13, 'transaction', '交易', 'word', NOW(), NOW()),
  (1186, 13, 'unlike', '不像', 'word', NOW(), NOW()),
  (1187, 13, 'upset', '烦恼', 'word', NOW(), NOW()),
  (1188, 13, 'version', '版本', 'word', NOW(), NOW()),
  (1189, 13, 'vote', '投票', 'word', NOW(), NOW()),
  (1190, 13, 'warm', '温暖的 1 提防', 'word', NOW(), NOW()),
  (1191, 13, 'watch', '2 观看 3 手表', 'word', NOW(), NOW()),
  (1192, 13, 'wear', '穿戴', 'word', NOW(), NOW()),
  (1193, 13, 'addict', 'n.上瘾的人 v.上瘾', 'word', NOW(), NOW()),
  (1194, 13, 'air', '空气 1 应对处理', 'word', NOW(), NOW()),
  (1195, 13, 'address', '2 说', 'word', NOW(), NOW()),
  (1196, 13, 'admire', '3 地址 钦佩欣赏', 'word', NOW(), NOW()),
  (1197, 13, 'admission', '准入；录取', 'word', NOW(), NOW()),
  (1198, 13, 'admit', '1 承认 2 准入', 'word', NOW(), NOW()),
  (1199, 13, 'alphabet', '字母表', 'word', NOW(), NOW()),
  (1200, 13, 'amaze', '使吃惊', 'word', NOW(), NOW()),
  (1201, 13, 'ancestor', '祖先', 'word', NOW(), NOW()),
  (1202, 13, 'application', '应用；申请', 'word', NOW(), NOW()),
  (1203, 13, 'arrival', '到达', 'word', NOW(), NOW()),
  (1204, 13, 'arrive', '到达', 'word', NOW(), NOW()),
  (1205, 13, 'artificial', '人造的', 'word', NOW(), NOW()),
  (1206, 13, 'artist', '艺术家', 'word', NOW(), NOW()),
  (1207, 13, 'assert', '坚称断言', 'word', NOW(), NOW()),
  (1208, 13, 'assess', '评估', 'word', NOW(), NOW()),
  (1209, 13, 'access', '进入使用', 'word', NOW(), NOW()),
  (1210, 13, 'attack', '攻击', 'word', NOW(), NOW()),
  (1211, 13, 'attend', '参加', 'word', NOW(), NOW()),
  (1212, 13, 'on behalf', '代表', 'word', NOW(), NOW()),
  (1213, 13, 'besides', '除了...之外；还', 'word', NOW(), NOW()),
  (1214, 13, 'bird', '鸟', 'word', NOW(), NOW()),
  (1215, 13, 'brief', '简短的', 'word', NOW(), NOW()),
  (1216, 13, 'broadcast', '广播', 'word', NOW(), NOW()),
  (1217, 13, 'broadly', '大体上', 'word', NOW(), NOW()),
  (1218, 13, 'budget', '预算', 'word', NOW(), NOW()),
  (1219, 13, 'businessman', '商人', 'word', NOW(), NOW()),
  (1220, 13, 'candidate', '候选人', 'word', NOW(), NOW()),
  (1221, 13, 'census', '人口普查', 'word', NOW(), NOW()),
  (1222, 13, 'central', '中央的 1 性格', 'word', NOW(), NOW()),
  (1223, 13, 'character', '2 特点 3 人品 4 角色', 'word', NOW(), NOW()),
  (1224, 13, 'collect', '1 收集 2 领取', 'word', NOW(), NOW()),
  (1225, 13, 'college', '大学', 'word', NOW(), NOW()),
  (1226, 13, 'combine', '结合；组合', 'word', NOW(), NOW()),
  (1227, 13, 'commission', '1 委员会 2 佣金', 'word', NOW(), NOW()),
  (1228, 13, 'commodity', '商品', 'word', NOW(), NOW()),
  (1229, 13, 'crisis', '危机', 'word', NOW(), NOW()),
  (1230, 13, 'compete', '竞争', 'word', NOW(), NOW()),
  (1231, 13, 'connect', '连接', 'word', NOW(), NOW()),
  (1232, 13, 'consistently', '一贯的', 'word', NOW(), NOW()),
  (1233, 13, 'contrary', '相反', 'word', NOW(), NOW()),
  (1234, 13, 'cooperation', '合作', 'word', NOW(), NOW()),
  (1235, 13, 'criticize', '批评', 'word', NOW(), NOW()),
  (1236, 14, 'corporate', '公司的', 'word', NOW(), NOW()),
  (1237, 14, 'couple', '一对', 'word', NOW(), NOW()),
  (1238, 14, 'cry', '1 哭 2 喊叫', 'word', NOW(), NOW()),
  (1239, 14, 'cycle', '1 循环 2 周期', 'word', NOW(), NOW()),
  (1240, 14, 'dedicate to', '致力于', 'word', NOW(), NOW()),
  (1241, 14, 'deserve', '应得', 'word', NOW(), NOW()),
  (1242, 14, 'difficulty', '困难', 'word', NOW(), NOW()),
  (1243, 14, 'discrimination', '歧视', 'word', NOW(), NOW()),
  (1244, 14, 'discuss', '探讨', 'word', NOW(), NOW()),
  (1245, 14, 'display', '显示', 'word', NOW(), NOW()),
  (1246, 14, 'distinction', '区别；卓越', 'word', NOW(), NOW()),
  (1247, 14, 'distinguish', '区分', 'word', NOW(), NOW()),
  (1248, 14, 'diversity', '多样', 'word', NOW(), NOW()),
  (1249, 14, 'downshift', '放慢', 'word', NOW(), NOW()),
  (1250, 14, 'editor', '编辑', 'word', NOW(), NOW()),
  (1251, 14, 'elite', '精英', 'word', NOW(), NOW()),
  (1252, 14, 'enhance', '增强；提高', 'word', NOW(), NOW()),
  (1253, 14, 'enormous', '巨大的', 'word', NOW(), NOW()),
  (1254, 14, 'ensure', '确保', 'word', NOW(), NOW()),
  (1255, 14, 'epidemic', '流行病', 'word', NOW(), NOW()),
  (1256, 14, 'euthanasia', '安乐死', 'word', NOW(), NOW()),
  (1257, 14, 'exactly', '1 准确地 2 到底', 'word', NOW(), NOW()),
  (1258, 14, 'exclude', '不包括', 'word', NOW(), NOW()),
  (1259, 14, 'expand', '扩张', 'word', NOW(), NOW()),
  (1260, 14, 'factory', '工厂', 'word', NOW(), NOW()),
  (1261, 14, 'failure', '失败', 'word', NOW(), NOW()),
  (1262, 14, 'field', '1 地 2 领域', 'word', NOW(), NOW()),
  (1263, 14, 'fly', '飞', 'word', NOW(), NOW()),
  (1264, 14, 'finding', '发现', 'word', NOW(), NOW()),
  (1265, 14, 'folk', '1 民间的 2 人们', 'word', NOW(), NOW()),
  (1266, 14, 'forward', '向前', 'word', NOW(), NOW()),
  (1267, 14, 'free', '1 自由的 2 免费的', 'word', NOW(), NOW()),
  (1268, 14, 'friendly', '友好的', 'word', NOW(), NOW()),
  (1269, 14, 'fundamental', '根本的', 'word', NOW(), NOW()),
  (1270, 14, 'greatly', '大大地', 'word', NOW(), NOW()),
  (1271, 14, 'ground', '地面', 'word', NOW(), NOW()),
  (1272, 14, 'guard', 'n. 守卫者 v. 保护', 'word', NOW(), NOW()),
  (1273, 14, 'heart', '心', 'word', NOW(), NOW()),
  (1274, 14, 'hence', '因此', 'word', NOW(), NOW()),
  (1275, 14, 'host', 'n. 主人 v. 主办', 'word', NOW(), NOW()),
  (1276, 14, 'huge', '大的', 'word', NOW(), NOW()),
  (1277, 14, 'independence', '独立', 'word', NOW(), NOW()),
  (1278, 14, 'inquiry', '调查；询问', 'word', NOW(), NOW()),
  (1279, 14, 'intelligent', '1 聪明的 2 智能的', 'word', NOW(), NOW()),
  (1280, 14, 'introduction', '1 介绍 2 引入', 'word', NOW(), NOW()),
  (1281, 14, 'laboratory', '实验室', 'word', NOW(), NOW()),
  (1282, 14, 'main', '主要的', 'word', NOW(), NOW()),
  (1283, 14, 'male/female', '男性／女性', 'word', NOW(), NOW()),
  (1284, 14, 'minister', '官员', 'word', NOW(), NOW()),
  (1285, 14, 'misery', '苦难悲惨', 'word', NOW(), NOW()),
  (1286, 14, 'mix', '混合', 'word', NOW(), NOW()),
  (1287, 14, 'mom/mother', '妈', 'word', NOW(), NOW()),
  (1288, 14, 'oblige', '强迫', 'word', NOW(), NOW()),
  (1289, 14, 'not necessarily', '不一定', 'word', NOW(), NOW()),
  (1290, 14, 'nervous', '1 紧张的 2 神经的', 'word', NOW(), NOW()),
  (1291, 14, 'openly', '公开地', 'word', NOW(), NOW()),
  (1292, 14, 'opinion', '看法', 'word', NOW(), NOW()),
  (1293, 14, 'option', '选项', 'word', NOW(), NOW()),
  (1294, 14, 'organization', '组织', 'word', NOW(), NOW()),
  (1295, 14, 'original', '起初地', 'word', NOW(), NOW()),
  (1296, 14, 'originate', '起源', 'word', NOW(), NOW()),
  (1297, 14, 'owe', '欠', 'word', NOW(), NOW()),
  (1298, 14, 'partly', '部分地', 'word', NOW(), NOW()),
  (1299, 14, 'party', '1 党 2 派对', 'word', NOW(), NOW()),
  (1300, 14, 'passionate', '热情的', 'word', NOW(), NOW()),
  (1301, 14, 'peculiar', '特有的；奇怪的', 'word', NOW(), NOW()),
  (1302, 14, 'people', '1 人 2 民族', 'word', NOW(), NOW()),
  (1303, 14, 'perfect', 'adj. 完美 v. 使完美的', 'word', NOW(), NOW()),
  (1304, 14, 'pick', '选', 'word', NOW(), NOW()),
  (1305, 14, 'personality', '个性', 'word', NOW(), NOW()),
  (1306, 14, 'philosophy', '哲学', 'word', NOW(), NOW()),
  (1307, 14, 'precede', '发生在….前', 'word', NOW(), NOW()),
  (1308, 14, 'precisely', '准确地', 'word', NOW(), NOW()),
  (1309, 14, 'prepare', '准备', 'word', NOW(), NOW()),
  (1310, 14, 'quick', '快', 'word', NOW(), NOW()),
  (1311, 14, 'print', '打印', 'word', NOW(), NOW()),
  (1312, 14, 'privilege', '1 优待 2 荣幸', 'word', NOW(), NOW()),
  (1313, 14, 'procedure', '手续流程', 'word', NOW(), NOW()),
  (1314, 14, 'profession', '行业', 'word', NOW(), NOW()),
  (1315, 14, 'psychological', '心理学的', 'word', NOW(), NOW()),
  (1316, 14, 'professionalizat', '职业化的', 'word', NOW(), NOW()),
  (1317, 14, 'pursue', '追求', 'word', NOW(), NOW()),
  (1318, 14, 'quote', '引用', 'word', NOW(), NOW()),
  (1319, 14, 'race', '1 比赛 2 种族', 'word', NOW(), NOW()),
  (1320, 14, 'radically', '激进地', 'word', NOW(), NOW()),
  (1321, 15, 'rail', '铁轨', 'word', NOW(), NOW()),
  (1322, 15, 'railway', '铁路', 'word', NOW(), NOW()),
  (1323, 15, 'random', '随机的', 'word', NOW(), NOW()),
  (1324, 15, 'reaction', '反应', 'word', NOW(), NOW()),
  (1325, 15, 'reasonable', '合理的', 'word', NOW(), NOW()),
  (1326, 15, 'recommend', '推荐', 'word', NOW(), NOW()),
  (1327, 15, 'recommendatio', '推荐', 'word', NOW(), NOW()),
  (1328, 15, 'reduction', '减少', 'word', NOW(), NOW()),
  (1329, 15, 'reference', '参考', 'word', NOW(), NOW()),
  (1330, 15, 'repeat', '重复', 'word', NOW(), NOW()),
  (1331, 15, 'request', '请求', 'word', NOW(), NOW()),
  (1332, 15, 'signal', '信号', 'word', NOW(), NOW()),
  (1333, 15, 'simple', '简单', 'word', NOW(), NOW()),
  (1334, 15, 'skeptical', '怀疑的', 'word', NOW(), NOW()),
  (1335, 15, 'solution', '解决办法', 'word', NOW(), NOW()),
  (1336, 15, 'southern', '南方的', 'word', NOW(), NOW()),
  (1337, 15, 'strength', '力量', 'word', NOW(), NOW()),
  (1338, 15, 'strike', '打击', 'word', NOW(), NOW()),
  (1339, 15, 'succeed', '成功', 'word', NOW(), NOW()),
  (1340, 15, 'suddenly', '突然地', 'word', NOW(), NOW()),
  (1341, 15, 'sufficient', '充足的', 'word', NOW(), NOW()),
  (1342, 15, 'suit', '1 适合 2 诉讼', 'word', NOW(), NOW()),
  (1343, 15, 'supportive', '3 正装 支持的', 'word', NOW(), NOW()),
  (1344, 15, 'systematic', '系统的', 'word', NOW(), NOW()),
  (1345, 15, 'target', '1 目标 2 瞄准', 'word', NOW(), NOW()),
  (1346, 15, 'team', '团队', 'word', NOW(), NOW()),
  (1347, 15, 'technique', '技术', 'word', NOW(), NOW()),
  (1348, 15, 'temporary', '临时的', 'word', NOW(), NOW()),
  (1349, 15, 'transform', '转变', 'word', NOW(), NOW()),
  (1350, 15, 'treat', '1 治疗 2 对待', 'word', NOW(), NOW()),
  (1351, 15, 'uniform', '制服', 'word', NOW(), NOW()),
  (1352, 15, 'upload', '上传', 'word', NOW(), NOW()),
  (1353, 15, 'valuable', '宝贵的', 'word', NOW(), NOW()),
  (1354, 15, 'vary', '不同', 'word', NOW(), NOW()),
  (1355, 15, 'visitor', '来访者', 'word', NOW(), NOW()),
  (1356, 15, 'wall', '墙', 'word', NOW(), NOW()),
  (1357, 15, 'welcome', '欢迎', 'word', NOW(), NOW()),
  (1358, 15, 'whatever', '无论什么', 'word', NOW(), NOW()),
  (1359, 15, 'whereas', '然而', 'word', NOW(), NOW()),
  (1360, 15, 'widespread', '广泛的', 'word', NOW(), NOW()),
  (1361, 15, 'workman', '工匠', 'word', NOW(), NOW()),
  (1362, 15, 'worm', '虫', 'word', NOW(), NOW()),
  (1363, 15, 'acceptable', '可接受的', 'word', NOW(), NOW()),
  (1364, 15, 'accident', '事故', 'word', NOW(), NOW()),
  (1365, 15, 'across', '穿过', 'word', NOW(), NOW()),
  (1366, 15, 'active', '活跃的', 'word', NOW(), NOW()),
  (1367, 15, 'actor', '演员', 'word', NOW(), NOW()),
  (1368, 15, 'in addition', '另外', 'word', NOW(), NOW()),
  (1369, 15, 'adjust', '调整', 'word', NOW(), NOW()),
  (1370, 15, 'adopt', '1 采用 2 收养', 'word', NOW(), NOW()),
  (1371, 15, 'aggressive', '大胆激进的', 'word', NOW(), NOW()),
  (1372, 15, 'alcohol', '酒精', 'word', NOW(), NOW()),
  (1373, 15, 'analyze', '分析', 'word', NOW(), NOW()),
  (1374, 15, 'annual', '年度的', 'word', NOW(), NOW()),
  (1375, 15, 'anti-intellectua', '反智主义', 'word', NOW(), NOW()),
  (1376, 15, 'anywhere', '任何地方', 'word', NOW(), NOW()),
  (1377, 15, 'apple', '苹果', 'word', NOW(), NOW()),
  (1378, 15, 'approve', '1 赞同 2 批准', 'word', NOW(), NOW()),
  (1379, 15, 'article', '1 文章 2 物品', 'word', NOW(), NOW()),
  (1380, 15, 'atmosphere', '氛围', 'word', NOW(), NOW()),
  (1381, 15, 'aware', '知道；明白', 'word', NOW(), NOW()),
  (1382, 15, 'balance', '平衡', 'word', NOW(), NOW()),
  (1383, 15, 'barely', '几乎不', 'word', NOW(), NOW()),
  (1384, 15, 'bargain', 'n.便宜货 n.交易 v.讲价', 'word', NOW(), NOW()),
  (1385, 15, 'basis', '1 基本原则 2 基础', 'word', NOW(), NOW()),
  (1386, 15, 'biology', '生物学', 'word', NOW(), NOW()),
  (1387, 15, 'blind', '瞎的', 'word', NOW(), NOW()),
  (1388, 15, 'boss', 'n. 老板 v.指手画脚', 'word', NOW(), NOW()),
  (1389, 15, 'branch', '分支', 'word', NOW(), NOW()),
  (1390, 15, 'brand', 'n.品牌', 'word', NOW(), NOW()),
  (1391, 15, 'busy', '忙的', 'word', NOW(), NOW()),
  (1392, 15, 'cancer', '癌症', 'word', NOW(), NOW()),
  (1393, 15, 'cancel', '取消', 'word', NOW(), NOW()),
  (1394, 15, 'captive', '被监禁的', 'word', NOW(), NOW()),
  (1395, 15, 'casual', '随意的', 'word', NOW(), NOW()),
  (1396, 15, 'cater', 'v.承办宴席', 'word', NOW(), NOW()),
  (1397, 15, 'cite', '引用', 'word', NOW(), NOW()),
  (1398, 15, 'citizen', '公民', 'word', NOW(), NOW()),
  (1399, 15, 'classical', '经典的', 'word', NOW(), NOW()),
  (1400, 15, 'classroom', '教室', 'word', NOW(), NOW()),
  (1401, 15, 'clean', '干净的', 'word', NOW(), NOW()),
  (1402, 15, 'closely', '紧密地', 'word', NOW(), NOW()),
  (1403, 15, 'complain', '抱怨', 'word', NOW(), NOW()),
  (1404, 15, 'complementary', '互补的', 'word', NOW(), NOW()),
  (1405, 15, 'comply', '服从', 'word', NOW(), NOW()),
  (1406, 15, 'compromise', '妥协', 'word', NOW(), NOW()),
  (1407, 15, 'concentration', '集中', 'word', NOW(), NOW()),
  (1408, 15, 'conclusion', '结论', 'word', NOW(), NOW()),
  (1409, 15, 'constitution', '宪法', 'word', NOW(), NOW()),
  (1410, 15, 'constitutional', '宪法的', 'word', NOW(), NOW()),
  (1411, 15, 'contempt', '轻视', 'word', NOW(), NOW()),
  (1412, 15, 'contract', 'n. 合同', 'word', NOW(), NOW()),
  (1413, 15, 'contrast', 'v. 收缩 对比', 'word', NOW(), NOW()),
  (1414, 15, 'contribution', '贡献', 'word', NOW(), NOW()),
  (1415, 15, 'convey', '传达', 'word', NOW(), NOW()),
  (1416, 15, 'cooperate', '合作', 'word', NOW(), NOW()),
  (1417, 15, 'count', '算术', 'word', NOW(), NOW()),
  (1418, 15, 'creature', '生物', 'word', NOW(), NOW()),
  (1419, 15, 'criminal', 'adj. 犯罪的', 'word', NOW(), NOW()),
  (1420, 15, 'dangerous', 'n. 罪犯 危险的', 'word', NOW(), NOW()),
  (1421, 15, 'date', '1 日期 2 约会', 'word', NOW(), NOW()),
  (1422, 15, 'default', '默认', 'word', NOW(), NOW()),
  (1423, 16, 'defend', '保卫 辩护', 'word', NOW(), NOW()),
  (1424, 16, 'democracy', '民主', 'word', NOW(), NOW()),
  (1425, 16, 'democratic', '民主的', 'word', NOW(), NOW()),
  (1426, 16, 'desirable', '理想的', 'word', NOW(), NOW()),
  (1427, 16, 'destroy', '毁灭', 'word', NOW(), NOW()),
  (1428, 16, 'device', '设备', 'word', NOW(), NOW()),
  (1429, 16, 'director', '董事，总监，主任', 'word', NOW(), NOW()),
  (1430, 16, 'disappear', '消失', 'word', NOW(), NOW()),
  (1431, 16, 'discussion', '探讨', 'word', NOW(), NOW()),
  (1432, 16, 'disorder', '失调，混乱', 'word', NOW(), NOW()),
  (1433, 16, 'distinctly', '明显', 'word', NOW(), NOW()),
  (1434, 16, 'economics', '经济学', 'word', NOW(), NOW()),
  (1435, 16, 'effectively', '有效地', 'word', NOW(), NOW()),
  (1436, 16, 'efficiency', '效率', 'word', NOW(), NOW()),
  (1437, 16, 'elsewhere', '别处', 'word', NOW(), NOW()),
  (1438, 16, 'emergence', '兴起', 'word', NOW(), NOW()),
  (1439, 16, 'employee', '员工', 'word', NOW(), NOW()),
  (1440, 16, 'endure', '忍受', 'word', NOW(), NOW()),
  (1441, 16, 'engineer', '工程师', 'word', NOW(), NOW()),
  (1442, 16, 'enlarge', '扩大', 'word', NOW(), NOW()),
  (1443, 16, 'adj. equivalent n.', '对等的 对等物', 'word', NOW(), NOW()),
  (1444, 16, 'excess', '过多', 'word', NOW(), NOW()),
  (1445, 16, 'excessive', '过多的', 'word', NOW(), NOW()),
  (1446, 16, 'extent', '程度', 'word', NOW(), NOW()),
  (1447, 16, 'external', '外部的', 'word', NOW(), NOW()),
  (1448, 16, 'extra', '额外的', 'word', NOW(), NOW()),
  (1449, 16, 'extreme', '极度的', 'word', NOW(), NOW()),
  (1450, 16, 'fairly', '相当地', 'word', NOW(), NOW()),
  (1451, 16, 'famous', '著名的', 'word', NOW(), NOW()),
  (1452, 16, 'faith', '1 信心 2 信仰', 'word', NOW(), NOW()),
  (1453, 16, 'far-reaching', '深远的', 'word', NOW(), NOW()),
  (1454, 16, 'formation', '建立形成', 'word', NOW(), NOW()),
  (1455, 16, 'fortune', '1 幸运 2 财富', 'word', NOW(), NOW()),
  (1456, 16, 'frustration', '沮丧', 'word', NOW(), NOW()),
  (1457, 16, 'fun', '乐趣', 'word', NOW(), NOW()),
  (1458, 16, 'garment', '衣服', 'word', NOW(), NOW()),
  (1459, 16, 'graduate', '毕业 毕业生', 'word', NOW(), NOW()),
  (1460, 16, 'grammar', '语法', 'word', NOW(), NOW()),
  (1461, 16, 'grape', '葡萄', 'word', NOW(), NOW()),
  (1462, 16, 'guarantee', '确保', 'word', NOW(), NOW()),
  (1463, 16, 'guide', '指引', 'word', NOW(), NOW()),
  (1464, 16, 'handle', '应对处理', 'word', NOW(), NOW()),
  (1465, 16, 'healthy', '健康的', 'word', NOW(), NOW()),
  (1466, 16, 'helmet', '头盔', 'word', NOW(), NOW()),
  (1467, 16, 'hospitality', '热情款待', 'word', NOW(), NOW()),
  (1468, 16, 'hotel', '酒店', 'word', NOW(), NOW()),
  (1469, 16, 'illegal', '非法的', 'word', NOW(), NOW()),
  (1470, 16, 'image', '1 形象 2 图像', 'word', NOW(), NOW()),
  (1471, 16, 'immediately', '立刻地', 'word', NOW(), NOW()),
  (1472, 16, 'impulse', '冲动', 'word', NOW(), NOW()),
  (1473, 16, 'initial', '最初的', 'word', NOW(), NOW()),
  (1474, 16, 'initiative', '积极性', 'word', NOW(), NOW()),
  (1475, 16, 'intense', '强烈的', 'word', NOW(), NOW()),
  (1476, 16, 'interaction', '互动', 'word', NOW(), NOW()),
  (1477, 16, 'interpret', '理解', 'word', NOW(), NOW()),
  (1478, 16, 'interview', '1 采访 2 面试', 'word', NOW(), NOW()),
  (1479, 16, 'joy', '欢乐', 'word', NOW(), NOW()),
  (1480, 16, 'the latter', '后者', 'word', NOW(), NOW()),
  (1481, 16, 'the former', '前者', 'word', NOW(), NOW()),
  (1482, 16, 'launch', '发射 2 发起', 'word', NOW(), NOW()),
  (1483, 16, 'leadership', '领导力', 'word', NOW(), NOW()),
  (1484, 16, 'leakage', '泄漏', 'word', NOW(), NOW()),
  (1485, 16, 'legislation', '立法', 'word', NOW(), NOW()),
  (1486, 16, 'liberal', '自由开明的', 'word', NOW(), NOW()),
  (1487, 16, 'migration', '移居', 'word', NOW(), NOW()),
  (1488, 16, 'military', '军事的', 'word', NOW(), NOW()),
  (1489, 16, 'nevertheless', '然而', 'word', NOW(), NOW()),
  (1490, 16, 'nor', '也不', 'word', NOW(), NOW()),
  (1491, 16, 'normal', '正常的', 'word', NOW(), NOW()),
  (1492, 16, 'north', '北', 'word', NOW(), NOW()),
  (1493, 16, 'v. notice n.', '注意到 通知', 'word', NOW(), NOW()),
  (1494, 16, 'objection', '反对', 'word', NOW(), NOW()),
  (1495, 16, 'observation', '观察', 'word', NOW(), NOW()),
  (1496, 16, 'obviously', '明显地', 'word', NOW(), NOW()),
  (1497, 16, 'ourselves', '我们自己', 'word', NOW(), NOW()),
  (1498, 16, 'outcome', '结果', 'word', NOW(), NOW()),
  (1499, 16, 'outlook', '世界观人生观', 'word', NOW(), NOW()),
  (1500, 16, 'pace', '步伐节奏', 'word', NOW(), NOW()),
  (1501, 16, 'painful', '痛苦的', 'word', NOW(), NOW()),
  (1502, 16, 'paycheck', '薪水', 'word', NOW(), NOW()),
  (1503, 16, 'percentage', '百分比', 'word', NOW(), NOW()),
  (1504, 16, 'permission', '许可', 'word', NOW(), NOW()),
  (1505, 16, 'physics', '物理学', 'word', NOW(), NOW()),
  (1506, 16, 'piece', '一块 片 点 段', 'word', NOW(), NOW()),
  (1507, 16, 'poet', '诗人', 'word', NOW(), NOW()),
  (1508, 16, '1. pose', '造成 2 姿势', 'word', NOW(), NOW()),
  (1509, 16, 'pour', '倾倒', 'word', NOW(), NOW()),
  (1510, 16, 'pride', '骄傲', 'word', NOW(), NOW()),
  (1511, 16, 'priority', '优先', 'word', NOW(), NOW()),
  (1512, 16, 'prolong', '延长', 'word', NOW(), NOW()),
  (1513, 16, 'proper', '恰当的', 'word', NOW(), NOW()),
  (1514, 16, 'puritan', '清教徒', 'word', NOW(), NOW()),
  (1515, 17, 'radio', '1 无线电 2 收音机', 'word', NOW(), NOW()),
  (1516, 17, 'rage', '狂怒', 'word', NOW(), NOW()),
  (1517, 17, 'rap', '说唱', 'word', NOW(), NOW()),
  (1518, 17, 'rapidly', '迅速地', 'word', NOW(), NOW()),
  (1519, 17, 'rarely', '少见地', 'word', NOW(), NOW()),
  (1520, 17, 'recovery', '恢复', 'word', NOW(), NOW()),
  (1521, 17, 'recruit', '招收', 'word', NOW(), NOW()),
  (1522, 17, 'refuse', '拒绝', 'word', NOW(), NOW()),
  (1523, 17, 'relatively', '相对来说', 'word', NOW(), NOW()),
  (1524, 17, 'release', '1 发布 2 释放', 'word', NOW(), NOW()),
  (1525, 17, 'reliable', '可靠的', 'word', NOW(), NOW()),
  (1526, 17, 'reply', '回应', 'word', NOW(), NOW()),
  (1527, 17, 'reporter', '记者', 'word', NOW(), NOW()),
  (1528, 17, 'resistant', '抗拒的', 'word', NOW(), NOW()),
  (1529, 17, 'routine', '惯例常规', 'word', NOW(), NOW()),
  (1530, 17, 'save', '1 节约 2 拯救', 'word', NOW(), NOW()),
  (1531, 17, 'scope', '3 免去 范围', 'word', NOW(), NOW()),
  (1532, 17, 'sea', '海', 'word', NOW(), NOW()),
  (1533, 17, 'segment', '部分', 'word', NOW(), NOW()),
  (1534, 17, 'seriously', '1 .严肃认真 2 当回事', 'word', NOW(), NOW()),
  (1535, 17, 'settle', '1 和解，解决 2 定居', 'word', NOW(), NOW()),
  (1536, 17, 'sex', '1 性 2 性别', 'word', NOW(), NOW()),
  (1537, 17, 'shut', '关闭', 'word', NOW(), NOW()),
  (1538, 17, 'sight', '1 视力视野 2 风景', 'word', NOW(), NOW()),
  (1539, 17, 'six', '六', 'word', NOW(), NOW()),
  (1540, 17, 'somewhat', '有一点', 'word', NOW(), NOW()),
  (1541, 17, 'specialization', '专门化', 'word', NOW(), NOW()),
  (1542, 17, 'staff', '员工', 'word', NOW(), NOW()),
  (1543, 17, 'specialize', '专门从事', 'word', NOW(), NOW()),
  (1544, 17, 'speculate', '推测', 'word', NOW(), NOW()),
  (1545, 17, 'spell', '1 拼写 2 一段时间', 'word', NOW(), NOW()),
  (1546, 17, 'stem', '阻止', 'word', NOW(), NOW()),
  (1547, 17, 'strengthen', '加强', 'word', NOW(), NOW()),
  (1548, 17, 'strongly', '强烈地', 'word', NOW(), NOW()),
  (1549, 17, 'substantial', '1 大量的 2 坚实的', 'word', NOW(), NOW()),
  (1550, 17, 'supporter', '支持者', 'word', NOW(), NOW()),
  (1551, 17, 'surgery', '外科手术', 'word', NOW(), NOW()),
  (1552, 17, 'surname', '姓', 'word', NOW(), NOW()),
  (1553, 17, 'surplus', '过剩的', 'word', NOW(), NOW()),
  (1554, 17, 'survey', '调查', 'word', NOW(), NOW()),
  (1555, 17, 'switch', '1 转换 2 开关', 'word', NOW(), NOW()),
  (1556, 17, 'sympathy', '同情', 'word', NOW(), NOW()),
  (1557, 17, 'traffic', '交通', 'word', NOW(), NOW()),
  (1558, 17, 'terminally', '终结地', 'word', NOW(), NOW()),
  (1559, 17, 'throughout', '贯穿，遍布 从始至终', 'word', NOW(), NOW()),
  (1560, 17, 'tip', '1 建议 2 小费', 'word', NOW(), NOW()),
  (1561, 17, 'trait', '3 尖端 特征', 'word', NOW(), NOW()),
  (1562, 17, 'triumph', '胜利，成功', 'word', NOW(), NOW()),
  (1563, 17, 'unconscious', '1 .昏迷的 2 无意识的', 'word', NOW(), NOW()),
  (1564, 17, 'underlie', '引起', 'word', NOW(), NOW()),
  (1565, 17, 'unemployment', '失业', 'word', NOW(), NOW()),
  (1566, 17, 'unusual', '不寻常的', 'word', NOW(), NOW()),
  (1567, 17, 'valid', '有效的', 'word', NOW(), NOW()),
  (1568, 17, 'victim', '受害者', 'word', NOW(), NOW()),
  (1569, 17, 'virtual', '1 几乎 2 虚拟的', 'word', NOW(), NOW()),
  (1570, 17, 'vitamin', '维生素', 'word', NOW(), NOW()),
  (1571, 17, 'water', '水', 'word', NOW(), NOW()),
  (1572, 17, 'weaken', '减弱', 'word', NOW(), NOW()),
  (1573, 17, 'western', '西方的', 'word', NOW(), NOW()),
  (1574, 17, 'whom', '谁', 'word', NOW(), NOW()),
  (1575, 17, 'abroad', '国外', 'word', NOW(), NOW()),
  (1576, 17, 'academy', '学院', 'word', NOW(), NOW()),
  (1577, 17, 'accessible', '易进入易使用的', 'word', NOW(), NOW()),
  (1578, 17, 'achiever', '成就的人', 'word', NOW(), NOW()),
  (1579, 17, 'acknowledge', '1 承认 2 感谢', 'word', NOW(), NOW()),
  (1580, 17, 'acquisition', '收购，获得', 'word', NOW(), NOW()),
  (1581, 17, 'actual', '实际的', 'word', NOW(), NOW()),
  (1582, 17, 'adequate', '足够的', 'word', NOW(), NOW()),
  (1583, 17, 'affair', '事务，事件', 'word', NOW(), NOW()),
  (1584, 17, 'aggravate', '恶化', 'word', NOW(), NOW()),
  (1585, 17, 'ahead', '在前面', 'word', NOW(), NOW()),
  (1586, 17, 'alike', '相同的', 'word', NOW(), NOW()),
  (1587, 17, 'alive', '1 活的 2 活跃的', 'word', NOW(), NOW()),
  (1588, 17, 'alternative', '另一个选择', 'word', NOW(), NOW()),
  (1589, 17, 'annoy', '惹恼', 'word', NOW(), NOW()),
  (1590, 17, 'anxiety', '焦虑', 'word', NOW(), NOW()),
  (1591, 17, 'anyway', '反正', 'word', NOW(), NOW()),
  (1592, 17, 'apart', '分开', 'word', NOW(), NOW()),
  (1593, 17, 'applicant', '申请人', 'word', NOW(), NOW()),
  (1594, 17, 'appointment', '1 任命 2 预约', 'word', NOW(), NOW()),
  (1595, 17, 'appreciate', '1 欣赏 2 感激', 'word', NOW(), NOW()),
  (1596, 17, 'appreciation', '3 了解 同上', 'word', NOW(), NOW()),
  (1597, 17, 'approval', '1 同意 2 批准', 'word', NOW(), NOW()),
  (1598, 17, 'arm', '手臂', 'word', NOW(), NOW()),
  (1599, 17, 'arouse', '激起', 'word', NOW(), NOW()),
  (1600, 17, 'assemble', '1 集合 2 组装', 'word', NOW(), NOW()),
  (1601, 17, 'associate', '联系', 'word', NOW(), NOW()),
  (1602, 17, 'assumption', '假设', 'word', NOW(), NOW()),
  (1603, 17, 'athlete', '运动员', 'word', NOW(), NOW()),
  (1604, 17, 'attach', '粘上，附上', 'word', NOW(), NOW()),
  (1605, 17, 'attribute', '归因', 'word', NOW(), NOW()),
  (1606, 17, 'award', '奖', 'word', NOW(), NOW()),
  (1607, 17, 'awareness', '知道', 'word', NOW(), NOW()),
  (1608, 17, 'banker', '银行家', 'word', NOW(), NOW()),
  (1609, 17, 'baseline', '基础', 'word', NOW(), NOW()),
  (1610, 17, 'belong', '属于', 'word', NOW(), NOW()),
  (1611, 17, 'belt', '带', 'word', NOW(), NOW()),
  (1612, 17, 'bid', '竞价', 'word', NOW(), NOW()),
  (1613, 18, 'bind', '捆绑', 'word', NOW(), NOW()),
  (1614, 18, 'biologist', '生物学家', 'word', NOW(), NOW()),
  (1615, 18, 'black', '黑', 'word', NOW(), NOW()),
  (1616, 18, 'boy', '男孩儿', 'word', NOW(), NOW()),
  (1617, 18, 'breakthrough', '突破', 'word', NOW(), NOW()),
  (1618, 18, 'capability', '能力', 'word', NOW(), NOW()),
  (1619, 18, 'bright', '1 光明的 2 聪明的', 'word', NOW(), NOW()),
  (1620, 18, 'capture', '捕获', 'word', NOW(), NOW()),
  (1621, 18, 'certainly', '肯定地', 'word', NOW(), NOW()),
  (1622, 18, 'chair', '1 主席 2 椅子', 'word', NOW(), NOW()),
  (1623, 18, 'club', '俱乐部', 'word', NOW(), NOW()),
  (1624, 18, 'childless', '无子女的', 'word', NOW(), NOW()),
  (1625, 18, 'civil', '1 国内的 2 文明的', 'word', NOW(), NOW()),
  (1626, 18, 'cognitive', '认知的', 'word', NOW(), NOW()),
  (1627, 18, 'colony', '殖民地', 'word', NOW(), NOW()),
  (1628, 18, 'command', '命令，指挥', 'word', NOW(), NOW()),
  (1629, 18, 'commitment', '承诺', 'word', NOW(), NOW()),
  (1630, 18, 'committee', '委员会', 'word', NOW(), NOW()),
  (1631, 18, 'commonly', '通常地', 'word', NOW(), NOW()),
  (1632, 18, 'communicate', '沟通交流', 'word', NOW(), NOW()),
  (1633, 18, 'confidence', '信心', 'word', NOW(), NOW()),
  (1634, 18, 'compensate', '补偿', 'word', NOW(), NOW()),
  (1635, 18, 'competitor', '竞争者', 'word', NOW(), NOW()),
  (1636, 18, 'component', '部分', 'word', NOW(), NOW()),
  (1637, 18, 'confront', '直面，正视', 'word', NOW(), NOW()),
  (1638, 18, 'consequently', '所以', 'word', NOW(), NOW()),
  (1639, 18, 'considerable', '相当的', 'word', NOW(), NOW()),
  (1640, 18, 'consideration', '考虑', 'word', NOW(), NOW()),
  (1641, 18, 'constitute', '组成', 'word', NOW(), NOW()),
  (1642, 18, 'consume', '消费，消耗', 'word', NOW(), NOW()),
  (1643, 18, 'contact', '接触联系', 'word', NOW(), NOW()),
  (1644, 18, 'context', '1 上下文 2 环境', 'word', NOW(), NOW()),
  (1645, 18, 'controversial', '争议的', 'word', NOW(), NOW()),
  (1646, 18, 'cool', '1 凉的 2 好的', 'word', NOW(), NOW()),
  (1647, 18, 'crack', '3 酷的 破裂，破解', 'word', NOW(), NOW()),
  (1648, 18, 'coverage', '覆盖范围', 'word', NOW(), NOW()),
  (1649, 18, 'crop', '庄稼', 'word', NOW(), NOW()),
  (1650, 18, 'cucumber', '黄瓜', 'word', NOW(), NOW()),
  (1651, 18, 'custom', '习俗', 'word', NOW(), NOW()),
  (1652, 18, 'damage', '损害', 'word', NOW(), NOW()),
  (1653, 18, 'dead', '死亡的', 'word', NOW(), NOW()),
  (1654, 18, 'delay', '死的 延误', 'word', NOW(), NOW()),
  (1655, 18, 'deliberately', '故意地', 'word', NOW(), NOW()),
  (1656, 18, 'deliver', '1 递送 2 讲话', 'word', NOW(), NOW()),
  (1657, 18, 'dependence', '依赖', 'word', NOW(), NOW()),
  (1658, 18, 'deprive', '剥夺', 'word', NOW(), NOW()),
  (1659, 18, 'detach', '脱离分开', 'word', NOW(), NOW()),
  (1660, 18, 'detect', '探测', 'word', NOW(), NOW()),
  (1661, 18, 'diet', '饮食，节食', 'word', NOW(), NOW()),
  (1662, 18, 'disadvantage', '不利', 'word', NOW(), NOW()),
  (1663, 18, 'disappoint', '失望', 'word', NOW(), NOW()),
  (1664, 18, 'disaster', '灾难', 'word', NOW(), NOW()),
  (1665, 18, 'dismiss', '1 解除解雇解散 2 不考虑', 'word', NOW(), NOW()),
  (1666, 18, 'disorganize', '混乱', 'word', NOW(), NOW()),
  (1667, 18, 'dissatisfaction', '不满足', 'word', NOW(), NOW()),
  (1668, 18, 'diverse', '多样的', 'word', NOW(), NOW()),
  (1669, 18, 'doctor', '1 医生 2 博士', 'word', NOW(), NOW()),
  (1670, 18, 'dominate', '统治，主宰', 'word', NOW(), NOW()),
  (1671, 18, 'dose', '剂量', 'word', NOW(), NOW()),
  (1672, 18, 'dramatic', '戏剧性的', 'word', NOW(), NOW()),
  (1673, 18, 'e-commerce', '电子商务', 'word', NOW(), NOW()),
  (1674, 18, 'elementary', '基础的初级的', 'word', NOW(), NOW()),
  (1675, 18, 'eliminate', '终止', 'word', NOW(), NOW()),
  (1676, 18, 'endeavor', '努力', 'word', NOW(), NOW()),
  (1677, 18, 'enlighten', '启发', 'word', NOW(), NOW()),
  (1678, 18, 'entertain', '娱乐', 'word', NOW(), NOW()),
  (1679, 18, 'entire', '整个的', 'word', NOW(), NOW()),
  (1680, 18, 'environmental', '环境的', 'word', NOW(), NOW()),
  (1681, 18, 'environmentalist', '环保人士', 'word', NOW(), NOW()),
  (1682, 18, 'everywhere', '到处', 'word', NOW(), NOW()),
  (1683, 18, 'exaggerate', '夸张', 'word', NOW(), NOW()),
  (1684, 18, 'expectation', '期待', 'word', NOW(), NOW()),
  (1685, 18, 'explosion', '爆炸', 'word', NOW(), NOW()),
  (1686, 18, 'extension', '延伸', 'word', NOW(), NOW()),
  (1687, 18, 'factual', '事实的', 'word', NOW(), NOW()),
  (1688, 18, 'fame', '名', 'word', NOW(), NOW()),
  (1689, 18, 'familiar', '熟悉的', 'word', NOW(), NOW()),
  (1690, 18, 'fascinate', '使着迷', 'word', NOW(), NOW()),
  (1691, 18, 'fee', '费用', 'word', NOW(), NOW()),
  (1692, 18, 'fiction', '小说', 'word', NOW(), NOW()),
  (1693, 18, 'fierce', '激烈的', 'word', NOW(), NOW()),
  (1694, 18, 'final', '最后的', 'word', NOW(), NOW()),
  (1695, 18, 'flaw', '缺陷', 'word', NOW(), NOW()),
  (1696, 18, 'flood', '洪水', 'word', NOW(), NOW()),
  (1697, 18, 'foresee', '预见', 'word', NOW(), NOW()),
  (1698, 18, 'found', '1 建立 2 找到 3 发现', 'word', NOW(), NOW());

-- 单元: 18 | 单词: 1698
SET FOREIGN_KEY_CHECKS = 1;