-- ============================================================
-- 18章答案 Unit 词汇表初始化数据
-- 来源: 18章答案.md  (共 18 个 Unit / 1700 词)
-- 适配表: unit / word  (word.seq 见迁移 006_word_seq；word.unit_id ON DELETE CASCADE)
-- 字符集: utf8mb4
-- 幂等: 开头按 title 删除同名 unit；word 随外键级联删除，可安全重跑
-- 注意: unit.sequence 唯一，若已被其它数据占用会冲突，请相应调整
-- ============================================================

SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM unit WHERE title LIKE '18章答案 Unit%';

-- ---------- Unit 1  (80 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 1', 1);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'would', '会', 1, 'word'),
  (@u, 'world', '世界', 2, 'word'),
  (@u, 'if', '1 如果；2 是否', 3, 'word'),
  (@u, 'human', '人类', 4, 'word'),
  (@u, 'paragraph', '段落', 5, 'word'),
  (@u, 'such', '如此的', 6, 'word'),
  (@u, 'should', '应该', 7, 'word'),
  (@u, 'social', '1 社会的；2 社交的', 8, 'word'),
  (@u, 'state', '1 国家；2 州；3 状态；4 说', 9, 'word'),
  (@u, 'work', '1 工作；2 作品；3 起作用', 10, 'word'),
  (@u, 'time', '1 时间；2 次数；3 倍数', 11, 'word'),
  (@u, 'company', '1 公司；2 陪伴', 12, 'word'),
  (@u, 'author', '作者', 13, 'word'),
  (@u, 'become', '变成', 14, 'word'),
  (@u, 'even', '甚至', 15, 'word'),
  (@u, 'way', '1 道路；2 方式', 16, 'word'),
  (@u, 'science', '科学', 17, 'word'),
  (@u, 'research', '研究', 18, 'word'),
  (@u, 'search', '搜索', 19, 'word'),
  (@u, 'into', '进入', 20, 'word'),
  (@u, 'life', '1 生活；2 生命', 21, 'word'),
  (@u, 'according to', '根据', 22, 'word'),
  (@u, 'because', '因为', 23, 'word'),
  (@u, 'also', '也，还', 24, 'word'),
  (@u, 'mean', '意味着', 25, 'word'),
  (@u, 'means', '方式；方法', 26, 'word'),
  (@u, 'need', '需要', 27, 'word'),
  (@u, 'seem', '似乎', 28, 'word'),
  (@u, 'over/under', '在...之上／之下；过了；不足', 29, 'word'),
  (@u, 'between', '两者之间', 30, 'word'),
  (@u, 'business', '1 商业；2 商家；3 事', 31, 'word'),
  (@u, 'like', '1 喜欢；2 像', 32, 'word'),
  (@u, 'likely', '很有可能的', 33, 'word'),
  (@u, 'find', '1 找到；2 发现', 34, 'word'),
  (@u, 'just', '1 仅仅；2 就；3 公平的', 35, 'word'),
  (@u, 'last', '1 最后；2 持续', 36, 'word'),
  (@u, '-less', '没有', 37, 'word'),
  (@u, 'less', '较少的', 38, 'word'),
  (@u, 'result', '结果', 39, 'word'),
  (@u, 'result in/lead to', '导致', 40, 'word'),
  (@u, 'few', '几乎没有', 41, 'word'),
  (@u, 'a few', '一些', 42, 'word'),
  (@u, 'follow', '跟随', 43, 'word'),
  (@u, 'live', '1 活／居住；2 直播的', 44, 'word'),
  (@u, 'own', 'adj. 自己的；v. 拥有', 45, 'word'),
  (@u, 'however', '然而；但是', 46, 'word'),
  (@u, 'show', '展现', 47, 'word'),
  (@u, 'child', '孩子', 48, 'word'),
  (@u, 'see', '1 看见；2 明白', 49, 'word'),
  (@u, 'study', '1 学习；2 研究', 50, 'word'),
  (@u, 'education', '教育', 51, 'word'),
  (@u, 'learn', '1 学习；2 了解', 52, 'word'),
  (@u, 'scientific', '科学的', 53, 'word'),
  (@u, 'test', '测试', 54, 'word'),
  (@u, 'example', '例子', 55, 'word'),
  (@u, 'large', '大', 56, 'word'),
  (@u, 'law', '法律；规则', 57, 'word'),
  (@u, 'pass', '1 通过；2 传递', 58, 'word'),
  (@u, 'too', '也', 59, 'word'),
  (@u, 'increase', '增加', 60, 'word'),
  (@u, 'market', '市场', 61, 'word'),
  (@u, 'yet', '不过', 62, 'word'),
  (@u, 'any', '任何', 63, 'word'),
  (@u, 'early', '早', 64, 'word'),
  (@u, 'part', '部分', 65, 'word'),
  (@u, 'reason', '1 理性；2 原因；3 推理', 66, 'word'),
  (@u, 'century', '世纪', 67, 'word'),
  (@u, 'family', '家族', 68, 'word'),
  (@u, 'before', '在...之前', 69, 'word'),
  (@u, 'country', '国家', 70, 'word'),
  (@u, 'high', '高', 71, 'word'),
  (@u, 'might', '可能', 72, 'word'),
  (@u, 'often', '经常', 73, 'word'),
  (@u, 'scientist', '科学家', 74, 'word'),
  (@u, 'culture', '文化', 75, 'word'),
  (@u, 'economic', '经济的', 76, 'word'),
  (@u, 'federal', '联邦', 77, 'word'),
  (@u, 'keep', '1 保持；2 留下', 78, 'word'),
  (@u, 'price', '价格', 79, 'word'),
  (@u, 'cost', '1 成本；2 花费；3 代价', 80, 'word');

-- ---------- Unit 2  (85 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 2', 2);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'idea', '主意；观点', 1, 'word'),
  (@u, 'influence/impact', '影响', 2, 'word'),
  (@u, 'language', '语言', 3, 'word'),
  (@u, 'line', '线', 4, 'word'),
  (@u, 'process', '1 过程；2 处理', 5, 'word'),
  (@u, 'word', '单词', 6, 'word'),
  (@u, 'begin', '开始', 7, 'word'),
  (@u, 'power', '权力；能力', 8, 'word'),
  (@u, 'society', '1 社会；2 协会；社团', 9, 'word'),
  (@u, 'still', '仍然', 10, 'word'),
  (@u, 'different', '不同的', 11, 'word'),
  (@u, 'kind', '1 慈善的；2 种类', 12, 'word'),
  (@u, 'rate', '1 速率；2 比例；3 打分评级', 13, 'word'),
  (@u, 'suggest', '1 建议；2 暗示', 14, 'word'),
  (@u, 'theory', '理论', 15, 'word'),
  (@u, 'control', '管控', 16, 'word'),
  (@u, 'great', '1 伟大的；2 好的；3 大的', 17, 'word'),
  (@u, 'number', '数字', 18, 'word'),
  (@u, 'thing', '事情', 19, 'word'),
  (@u, 'question', '1 问题；2 质疑', 20, 'word'),
  (@u, 'right', '1 正确的；2 权利；3 右边', 21, 'word'),
  (@u, 'very', '非常', 22, 'word'),
  (@u, 'want', '想', 23, 'word'),
  (@u, 'industry', '1 工业；2 行业；产业', 24, 'word'),
  (@u, 'information', '信息', 25, 'word'),
  (@u, 'look', '1 看；2 外表', 26, 'word'),
  (@u, 'man', '1 人；2 男人', 27, 'word'),
  (@u, 'media', '媒体', 28, 'word'),
  (@u, 'through', '通过', 29, 'word'),
  (@u, 'though', '尽管', 30, 'word'),
  (@u, 'write', '写', 31, 'word'),
  (@u, 'against', '1 反对；2 面对；3 针对', 32, 'word'),
  (@u, 'believe', '1 相信；2 认为', 33, 'word'),
  (@u, 'government', '政府', 34, 'word'),
  (@u, 'interest', '1 兴趣；2 利息；3 利益', 35, 'word'),
  (@u, 'system', '系统', 36, 'word'),
  (@u, 'both', '两者都', 37, 'word'),
  (@u, 'then', '1 然后；2 那么；3 那时', 38, 'word'),
  (@u, 'case', '1 箱子；2 案例；3 情况', 39, 'word'),
  (@u, 'develop', '1 发展；2 开发', 40, 'word'),
  (@u, 'late', '迟到；晚了', 41, 'word'),
  (@u, 'mind', 'v. 在意；n. 思维', 42, 'word'),
  (@u, 'text', '文本', 43, 'word'),
  (@u, 'view', 'v. 看；n. 观点', 44, 'word'),
  (@u, 'important', '重要的', 45, 'word'),
  (@u, 'tend to', '倾向于；往往', 46, 'word'),
  (@u, 'another', '另一个', 47, 'word'),
  (@u, 'book', 'n. 书本；v. 预定', 48, 'word'),
  (@u, 'data', '数据', 49, 'word'),
  (@u, 'drug', '1 药；2 毒品', 50, 'word'),
  (@u, 'effect', '效果；效应', 51, 'word'),
  (@u, 'affect', '影响', 52, 'word'),
  (@u, 'point', 'n. 观点；点；v. 指', 53, 'word'),
  (@u, 'require', '要求', 54, 'word'),
  (@u, 'since', '1 自从；2 由于', 55, 'word'),
  (@u, 'value', 'n. 价值；价值观；v. 重视；珍视', 56, 'word'),
  (@u, 'create', '创造', 57, 'word'),
  (@u, 'economy', '经济', 58, 'word'),
  (@u, 'future', '将来', 59, 'word'),
  (@u, 'grow', '1 成长；2 变得', 60, 'word'),
  (@u, 'growth', '增长；成长', 61, 'word'),
  (@u, 'intellectual', '有学识的', 62, 'word'),
  (@u, 'turn', '转', 63, 'word'),
  (@u, 'university', '大学', 64, 'word'),
  (@u, 'without', '没有', 65, 'word'),
  (@u, 'claim', '1 声称；2 索取', 66, 'word'),
  (@u, 'end', '结束；终结', 67, 'word'),
  (@u, 'group', '群体', 68, 'word'),
  (@u, 'lead', '指引', 69, 'word'),
  (@u, 'leave', '离开；留下', 70, 'word'),
  (@u, 'national', '国家的', 71, 'word'),
  (@u, 'pay', '支付；工资', 72, 'word'),
  (@u, 'rather than', '而不是', 73, 'word'),
  (@u, 'same', '相同的', 74, 'word'),
  (@u, 'support', '支持', 75, 'word'),
  (@u, 'cause', '1 导致；引起；2 原因', 76, 'word'),
  (@u, 'computer', '电脑', 77, 'word'),
  (@u, 'every', '每一个', 78, 'word'),
  (@u, 'percent', '百分比', 79, 'word'),
  (@u, 'place', 'n. 地方；地点；v. 放置', 80, 'word'),
  (@u, 'probably', '可能地', 81, 'word'),
  (@u, 'report', '报告', 82, 'word'),
  (@u, 'three', '三', 83, 'word'),
  (@u, 'true', '真实的', 84, 'word'),
  (@u, 'while', '1 当...时；2 尽管；3 然而', 85, 'word');

-- ---------- Unit 3  (84 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 3', 3);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'account', '账户', 1, 'word'),
  (@u, 'among', '在...中间', 2, 'word'),
  (@u, 'certain', '1 一些；2 肯定的', 3, 'word'),
  (@u, 'customer', '顾客', 4, 'word'),
  (@u, 'far', '1 远的；2 相当的', 5, 'word'),
  (@u, 'form', 'v. 形成；n. 形式', 6, 'word'),
  (@u, 'issue', '1 问题；2 发布', 7, 'word'),
  (@u, 'public', '公众的', 8, 'word'),
  (@u, 'researcher', '研究员', 9, 'word'),
  (@u, 'rise', '上升', 10, 'word'),
  (@u, 'rule', '1 统治；2 判决', 11, 'word'),
  (@u, 'technology', '技术', 12, 'word'),
  (@u, 'where', '在...地方', 13, 'word'),
  (@u, 'argue', '1 争吵；争论；2 认为；主张', 14, 'word'),
  (@u, 'call', '打电话', 15, 'word'),
  (@u, 'community', '1 社区；2 团体', 16, 'word'),
  (@u, 'consider', '1 考虑；2 认为', 17, 'word'),
  (@u, 'consumer', '消费者', 18, 'word'),
  (@u, 'court', '法院', 19, 'word'),
  (@u, 'each', '每个', 20, 'word'),
  (@u, 'off', '离开；分开', 21, 'word'),
  (@u, 'political', '政治的', 22, 'word'),
  (@u, 'provide', '提供', 23, 'word'),
  (@u, 'service', '服务', 24, 'word'),
  (@u, 'bring', '带来', 25, 'word'),
  (@u, 'feel', '感觉', 26, 'word'),
  (@u, 'fund', 'n. 基金；v. 资助', 27, 'word'),
  (@u, 'improve', '改善；提高', 28, 'word'),
  (@u, 'little', '几乎没有', 29, 'word'),
  (@u, 'a little', '一点点', 30, 'word'),
  (@u, 'offer', '提供', 31, 'word'),
  (@u, 'continue', '继续', 32, 'word'),
  (@u, 'stress', 'v. 强调；n. 压力', 33, 'word'),
  (@u, 'during', '在...期间', 34, 'word'),
  (@u, 'fact', '事实', 35, 'word'),
  (@u, 'in fact', '事实上', 36, 'word'),
  (@u, 'history', '历史', 37, 'word'),
  (@u, 'internet', '互联网', 38, 'word'),
  (@u, 'million', '百万', 39, 'word'),
  (@u, 'billion', '十亿', 40, 'word'),
  (@u, 'old', '1 旧的；2 年老的', 41, 'word'),
  (@u, 'paper', '1 纸；2 论文', 42, 'word'),
  (@u, 'passage', '文章', 43, 'word'),
  (@u, 'start', '开始', 44, 'word'),
  (@u, 'population', '人口', 45, 'word'),
  (@u, 'program', 'n. 节目；n. 程序；v. 编程', 46, 'word'),
  (@u, 'whether', '是否', 47, 'word'),
  (@u, 'behavior', '行为', 48, 'word'),
  (@u, 'common', '常见的；共同的', 49, 'word'),
  (@u, 'dream', '梦想', 50, 'word'),
  (@u, 'limit', '限制', 51, 'word'),
  (@u, 'move', 'v. 移动；n. 行动', 52, 'word'),
  (@u, 'online', '在线的', 53, 'word'),
  (@u, 'role', '角色', 54, 'word'),
  (@u, 'patient', 'adj. 耐心的；n. 病人', 55, 'word'),
  (@u, 'put', '1 放；放置；2 说', 56, 'word'),
  (@u, 'share', 'v. 分享', 57, 'word'),
  (@u, 'share', 'n. 股份', 58, 'word'),
  (@u, 'why', '为什么', 59, 'word'),
  (@u, 'woman', '女人', 60, 'word'),
  (@u, 'always', '总是', 61, 'word'),
  (@u, 'average', '1 平均的；2 普通的', 62, 'word'),
  (@u, 'bank', '1 银行；2 河岸', 63, 'word'),
  (@u, 'skill', '技能', 64, 'word'),
  (@u, 'development', '发展', 65, 'word'),
  (@u, 'experience', 'n. 经验；v. 经历', 66, 'word'),
  (@u, 'set', 'v. 设置；v. 下降；n. 一套', 67, 'word'),
  (@u, 'small', '小的', 68, 'word'),
  (@u, 'act', 'v. 行动；v. 表现；n. 法案', 69, 'word'),
  (@u, 'appear', '1 出现；2 显得', 70, 'word'),
  (@u, 'deal', '交易', 71, 'word'),
  (@u, 'deal with', '处理', 72, 'word'),
  (@u, 'a great deal of', '大量', 73, 'word'),
  (@u, 'decade', '十年', 74, 'word'),
  (@u, 'decision', '决定', 75, 'word'),
  (@u, 'evidence', '证据', 76, 'word'),
  (@u, 'food', '食物', 77, 'word'),
  (@u, 'health', '健康', 78, 'word'),
  (@u, 'him', '他', 79, 'word'),
  (@u, 'individual', '个人的', 80, 'word'),
  (@u, 'instead', '反而', 81, 'word'),
  (@u, 'likely', '很可能的', 82, 'word'),
  (@u, 'lose', '1 失去；2 输', 83, 'word'),
  (@u, 'medical', '医学的', 84, 'word');

-- ---------- Unit 4  (97 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 4', 4);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'patent', '专利', 1, 'word'),
  (@u, 'play', '玩', 2, 'word'),
  (@u, 'professional', '专业的', 3, 'word'),
  (@u, 'search', '搜索', 4, 'word'),
  (@u, 'though', '虽然', 5, 'word'),
  (@u, 'try', '试图', 6, 'word'),
  (@u, 'understand', '理解', 7, 'word'),
  (@u, 'age', 'n. 年龄；v. 变老', 8, 'word'),
  (@u, 'concern', '担心', 9, 'word'),
  (@u, 'fall', '下降', 10, 'word'),
  (@u, 'function', '功能', 11, 'word'),
  (@u, 'half', '一半', 12, 'word'),
  (@u, 'hold', '1 持有；2 认为', 13, 'word'),
  (@u, 'infer', '推断', 14, 'word'),
  (@u, 'least', '最少的', 15, 'word'),
  (@u, 'at least', '至少', 16, 'word'),
  (@u, 'once', '1 一旦；2 一次；3 曾经', 17, 'word'),
  (@u, 'attitude', '态度', 18, 'word'),
  (@u, 'back', '1 后面；2 后背；3 支持', 19, 'word'),
  (@u, 'basic', '基础的', 20, 'word'),
  (@u, 'benefit', 'n. 利益；v. 对……有益', 21, 'word'),
  (@u, 'care', '1 关怀；照料；2 在乎', 22, 'word'),
  (@u, 'death', '死亡', 23, 'word'),
  (@u, 'decline', '1 下降；2 谢绝', 24, 'word'),
  (@u, 'describe', '描述', 25, 'word'),
  (@u, 'financial', '金融的', 26, 'word'),
  (@u, 'force', '1 力量；2 强迫', 27, 'word'),
  (@u, 'happen', '发生', 28, 'word'),
  (@u, 'including', '包括', 29, 'word'),
  (@u, 'intelligence', '1 智力；2 情报', 30, 'word'),
  (@u, 'journal', '刊物', 31, 'word'),
  (@u, 'moral', '道德的', 32, 'word'),
  (@u, 'practice', '1 实践；2 练习', 33, 'word'),
  (@u, 'produce', '生产', 34, 'word'),
  (@u, 'productivity', '生产力', 35, 'word'),
  (@u, 'subject', '1 科目；2 主题', 36, 'word'),
  (@u, 'ago', '以前的', 37, 'word'),
  (@u, 'ask', '问', 38, 'word'),
  (@u, 'brain', '头脑', 39, 'word'),
  (@u, 'build', '建造', 40, 'word'),
  (@u, 'clone', '克隆', 41, 'word'),
  (@u, 'doctor', '医生', 42, 'word'),
  (@u, 'expect', '1 期待；2 预料', 43, 'word'),
  (@u, 'knowledge', '知识', 44, 'word'),
  (@u, 'legal', '合法的', 45, 'word'),
  (@u, 'major', 'adj. 重大的；n. 专业', 46, 'word'),
  (@u, 'music', '音乐', 47, 'word'),
  (@u, 'my', '我的', 48, 'word'),
  (@u, 'nation', '国家', 49, 'word'),
  (@u, 'nature', '1 自然；2 本质；本性', 50, 'word'),
  (@u, 'possible', '可能的', 51, 'word'),
  (@u, 'under', '在……之下', 52, 'word'),
  (@u, 'unite', '团结；联合', 53, 'word'),
  (@u, 'young', '年轻的', 54, 'word'),
  (@u, 'environment', '环境', 55, 'word'),
  (@u, 'evolution', '进化', 56, 'word'),
  (@u, 'revolution', '革命', 57, 'word'),
  (@u, 'fail', '失败', 58, 'word'),
  (@u, 'fail to', '未能做；没做', 59, 'word'),
  (@u, 'fashion', '1 时尚；2 方式', 60, 'word'),
  (@u, 'inflation', '通货膨胀', 61, 'word'),
  (@u, 'intend', '打算', 62, 'word'),
  (@u, 'oil', '油', 63, 'word'),
  (@u, 'plan', '计划', 64, 'word'),
  (@u, 'potential', '1 潜能', 65, 'word'),
  (@u, 'potential', '2 潜在的', 66, 'word'),
  (@u, 'publish', '出版', 67, 'word'),
  (@u, 'raise', '1 提高；2 提出；3 筹集；4 抚养；饲养', 68, 'word'),
  (@u, 'risk', '风险', 69, 'word'),
  (@u, 'run', '1 跑；2 经营', 70, 'word'),
  (@u, 'she', '她', 71, 'word'),
  (@u, 'species', '物种', 72, 'word'),
  (@u, 'structure', '结构', 73, 'word'),
  (@u, 'student', '学生', 74, 'word'),
  (@u, 'trend', '趋势', 75, 'word'),
  (@u, 'substance', '物质', 76, 'word'),
  (@u, 'term', '1 术语；2 学期', 77, 'word'),
  (@u, 'train', 'n. 火车；v. 培训', 78, 'word'),
  (@u, 'until', '直到', 79, 'word'),
  (@u, 'within', '在……之内', 80, 'word'),
  (@u, 'worker', '工人', 81, 'word'),
  (@u, 'ambition', '雄心；野心', 82, 'word'),
  (@u, 'around', '在……周围', 83, 'word'),
  (@u, 'course', '1 过程；2 课程', 84, 'word'),
  (@u, 'demand', '需求', 85, 'word'),
  (@u, 'discovery', '发现', 86, 'word'),
  (@u, 'enough', '足够的', 87, 'word'),
  (@u, 'ever', '从来；永远', 88, 'word'),
  (@u, 'experiment', '试验', 89, 'word'),
  (@u, 'explain', '解释', 90, 'word'),
  (@u, 'involve', '涉及到', 91, 'word'),
  (@u, 'low', '低', 92, 'word'),
  (@u, 'pattern', '模式', 93, 'word'),
  (@u, 'pressure', '压力', 94, 'word'),
  (@u, 'read', '读', 95, 'word'),
  (@u, 'reduce', '减少', 96, 'word'),
  (@u, 'remain', '1 保持；2 留下', 97, 'word');

-- ---------- Unit 5  (94 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 5', 5);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'add', '增加', 1, 'word'),
  (@u, 'almost', '几乎', 2, 'word'),
  (@u, 'attention', '注意力', 3, 'word'),
  (@u, 'body', '身体', 4, 'word'),
  (@u, 'condition', '条件', 5, 'word'),
  (@u, 'dam', '大坝', 6, 'word'),
  (@u, 'difference', '不同', 7, 'word'),
  (@u, 'down', '下', 8, 'word'),
  (@u, 'especially', '尤其', 9, 'word'),
  (@u, 'generally', '通常来说', 10, 'word'),
  (@u, 'generation', '代', 11, 'word'),
  (@u, 'home', '家', 12, 'word'),
  (@u, 'humanity', '人性', 13, 'word'),
  (@u, 'kid', '孩子', 14, 'word'),
  (@u, 'loss', '失去', 15, 'word'),
  (@u, 'monkey', '猴子', 16, 'word'),
  (@u, 'natural', '自然的', 17, 'word'),
  (@u, 'policy', '政策', 18, 'word'),
  (@u, 'several', '一些', 19, 'word'),
  (@u, 'talk', '谈论', 20, 'word'),
  (@u, 'television', '电视', 21, 'word'),
  (@u, 'web', '网络', 22, 'word'),
  (@u, 'writer', '作家', 23, 'word'),
  (@u, 'ability', '能力', 24, 'word'),
  (@u, 'accept', '接受', 25, 'word'),
  (@u, 'agree', '同意', 26, 'word'),
  (@u, 'available', '1 可用的；2 可得到的', 27, 'word'),
  (@u, 'casino', '赌场', 28, 'word'),
  (@u, 'class', '1 阶级；2 等级；3 班级', 29, 'word'),
  (@u, 'compare', '比较', 30, 'word'),
  (@u, 'consequence', '结果', 31, 'word'),
  (@u, 'cultural', '文化的', 32, 'word'),
  (@u, 'depend on', '1 依靠；2 取决于', 33, 'word'),
  (@u, 'easy', '1 容易的；2 轻松的', 34, 'word'),
  (@u, 'firm', 'n. 公司；adj. 坚固的', 35, 'word'),
  (@u, 'hot', '热的', 36, 'word'),
  (@u, 'justice', '1 正义；2 大法官', 37, 'word'),
  (@u, 'news', '新闻', 38, 'word'),
  (@u, 'newspaper', '报纸', 39, 'word'),
  (@u, 'open', '打开', 40, 'word'),
  (@u, 'seek', '寻找', 41, 'word'),
  (@u, 'send', '发送', 42, 'word'),
  (@u, 'single', '单个的', 43, 'word'),
  (@u, 'standard', '标准', 44, 'word'),
  (@u, 'together', '一起', 45, 'word'),
  (@u, 'week', '周', 46, 'word'),
  (@u, 'although', '尽管', 47, 'word'),
  (@u, 'advocate', 'v. 拥护；提倡；n. 拥护者', 48, 'word'),
  (@u, 'concept', '概念', 49, 'word'),
  (@u, 'house', '房子', 50, 'word'),
  (@u, 'influential', '有影响力的', 51, 'word'),
  (@u, 'management', '管理', 52, 'word'),
  (@u, 'member', '成员', 53, 'word'),
  (@u, 'message', '信息', 54, 'word'),
  (@u, 'note', '1 笔记；2 注意到；3 氛围', 55, 'word'),
  (@u, 'opportunity', '机会', 56, 'word'),
  (@u, 'parent', '家长', 57, 'word'),
  (@u, 'plate', '1 盘子；2 牌子', 58, 'word'),
  (@u, 'present', '1 礼物；2 现在的；3 出席的；4 呈现', 59, 'word'),
  (@u, 'production', '生产', 60, 'word'),
  (@u, 'receive', '接收', 61, 'word'),
  (@u, 'regard', 'v. 认为；n. 问候', 62, 'word'),
  (@u, 'second', '1 第二；2 秒', 63, 'word'),
  (@u, 'thus', '因此', 64, 'word'),
  (@u, 'top', '顶端', 65, 'word'),
  (@u, 'union', '联盟', 66, 'word'),
  (@u, 'war', '战争', 67, 'word'),
  (@u, 'whose', '谁的', 68, 'word'),
  (@u, 'advantage', '优势', 69, 'word'),
  (@u, 'already', '已经', 70, 'word'),
  (@u, 'art', '艺术', 71, 'word'),
  (@u, 'asset', '资产', 72, 'word'),
  (@u, 'billion', '十亿', 73, 'word'),
  (@u, 'million', '百万', 74, 'word'),
  (@u, 'carry', '携带', 75, 'word'),
  (@u, 'challenge', '挑战', 76, 'word'),
  (@u, 'difficult', '困难的', 77, 'word'),
  (@u, 'earn', '挣得', 78, 'word'),
  (@u, 'focus/concentrate', '集中', 79, 'word'),
  (@u, 'habit', '习惯', 80, 'word'),
  (@u, 'happiness', '幸福', 81, 'word'),
  (@u, 'introduce', '介绍', 82, 'word'),
  (@u, 'leader', '领导', 83, 'word'),
  (@u, 'lot', '许多', 84, 'word'),
  (@u, 'matter', 'n. 事情；v. 要紧', 85, 'word'),
  (@u, 'modern', '现代的', 86, 'word'),
  (@u, 'order', '1 命令；2 订', 87, 'word'),
  (@u, 'personal', '1 个人的；2 人际的', 88, 'word'),
  (@u, 'poor', '1 贫穷的；2 可怜的', 89, 'word'),
  (@u, 'product', '产品', 90, 'word'),
  (@u, 'real', '真实的', 91, 'word'),
  (@u, 'reveal', '揭示', 92, 'word'),
  (@u, 'sell', '卖', 93, 'word'),
  (@u, 'sense', '1 感官；2 察觉；3 感（抽象）；4 意义', 94, 'word');

-- ---------- Unit 6  (94 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 6', 6);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'situation', '情况', 1, 'word'),
  (@u, 'smell', '闻', 2, 'word'),
  (@u, 'success', '成功', 3, 'word'),
  (@u, 'suffer', '遭受', 4, 'word'),
  (@u, 'towards', '朝着', 5, 'word'),
  (@u, 'able', '能够', 6, 'word'),
  (@u, 'achieve', '成就；达成', 7, 'word'),
  (@u, 'action', '行动', 8, 'word'),
  (@u, 'activity', '活动', 9, 'word'),
  (@u, 'adult', '成人', 10, 'word'),
  (@u, 'advance', '前进', 11, 'word'),
  (@u, 'agent', '代理', 12, 'word'),
  (@u, 'anything', '任何事', 13, 'word'),
  (@u, 'approach', '1 接近；2 方式；方法', 14, 'word'),
  (@u, 'area', '地区', 15, 'word'),
  (@u, 'base', '基地', 16, 'word'),
  (@u, 'close', '1 关闭；2 近的', 17, 'word'),
  (@u, 'critic/criticize/critical/criticism', '批评', 18, 'word'),
  (@u, 'essential', '基本的', 19, 'word'),
  (@u, 'freedom', '自由', 20, 'word'),
  (@u, 'gamble', '赌博', 21, 'word'),
  (@u, 'general', '通用的', 22, 'word'),
  (@u, 'goal', '目标', 23, 'word'),
  (@u, 'hard', '1 困难的；2 坚硬的；3 努力的', 24, 'word'),
  (@u, 'immigrant', '移民', 25, 'word'),
  (@u, 'international', '国际的', 26, 'word'),
  (@u, 'investment', '投资', 27, 'word'),
  (@u, 'IQ', '智商', 28, 'word'),
  (@u, 'list', 'v. 列出；n. 清单', 29, 'word'),
  (@u, 'machine', '机器', 30, 'word'),
  (@u, 'meet', '1 遇见；2 满足', 31, 'word'),
  (@u, 'method', '方法', 32, 'word'),
  (@u, 'necessary', '必要的', 33, 'word'),
  (@u, 'never', '绝不；从不', 34, 'word'),
  (@u, 'pain', '痛', 35, 'word'),
  (@u, 'peer pressure', '同辈压力', 36, 'word'),
  (@u, 'prove', '证明', 37, 'word'),
  (@u, 'score', 'n. 分数；v. 得分', 38, 'word'),
  (@u, 'something', '某事', 39, 'word'),
  (@u, 'spot', '点', 40, 'word'),
  (@u, 'tell', '1 告诉；2 分辨', 41, 'word'),
  (@u, 'trade', '贸易', 42, 'word'),
  (@u, 'wonder', 'v. 想知道；n. 神奇', 43, 'word'),
  (@u, 'baby', '婴儿', 44, 'word'),
  (@u, 'beyond', '超过', 45, 'word'),
  (@u, 'clear', '清楚的', 46, 'word'),
  (@u, 'fast', '快', 47, 'word'),
  (@u, 'competition', '竞争', 48, 'word'),
  (@u, 'conduct', '实施', 49, 'word'),
  (@u, 'define', '下定义', 50, 'word'),
  (@u, 'effort', '努力', 51, 'word'),
  (@u, 'face', '1 脸；2 面对', 52, 'word'),
  (@u, 'feature', '特征', 53, 'word'),
  (@u, 'genetic', '基因的', 54, 'word'),
  (@u, 'include', '包括', 55, 'word'),
  (@u, 'itself', '它自己', 56, 'word'),
  (@u, 'labor', '劳动', 57, 'word'),
  (@u, 'lack', '缺乏', 58, 'word'),
  (@u, 'level', '水平', 59, 'word'),
  (@u, 'next', '接下来', 60, 'word'),
  (@u, 'outside', '在外面', 61, 'word'),
  (@u, 'particular', '特别', 62, 'word'),
  (@u, 'particularly', '尤其', 63, 'word'),
  (@u, 'perhaps', '也许', 64, 'word'),
  (@u, 'physical', '1 身体的；2 实体的', 65, 'word'),
  (@u, 'mental', '1 心理的；2 精神的', 66, 'word'),
  (@u, 'president', '1 总统；2 校长；总裁', 67, 'word'),
  (@u, 'publication', '出版', 68, 'word'),
  (@u, 'quality', '品质', 69, 'word'),
  (@u, 'reach', '到达', 70, 'word'),
  (@u, 'record', '记录', 71, 'word'),
  (@u, 'site', '地点', 72, 'word'),
  (@u, 'slave', '奴隶', 73, 'word'),
  (@u, 'story', '故事', 74, 'word'),
  (@u, 'teach', '教', 75, 'word'),
  (@u, 'traditional', '传统的', 76, 'word'),
  (@u, 'usually', '通常', 77, 'word'),
  (@u, 'amateur', '业余', 78, 'word'),
  (@u, 'avoid', '避免', 79, 'word'),
  (@u, 'bear/stand/end', '忍受', 80, 'word'),
  (@u, 'buy', '1 买；2 相信', 81, 'word'),
  (@u, 'capacity', '容量', 82, 'word'),
  (@u, 'choose', '选择', 83, 'word'),
  (@u, 'commercial', '商业的', 84, 'word'),
  (@u, 'creative', '有创造力的', 85, 'word'),
  (@u, 'database', '数据库', 86, 'word'),
  (@u, 'debate', '辩论；争论', 87, 'word'),
  (@u, 'die', '死', 88, 'word'),
  (@u, 'directly', '直接地', 89, 'word'),
  (@u, 'discipline', '纪律', 90, 'word'),
  (@u, 'DNA', '脱氧核糖核酸', 91, 'word'),
  (@u, 'either', '也不', 92, 'word'),
  (@u, 'else', '其他的', 93, 'word'),
  (@u, 'emerge', '出现；新兴', 94, 'word');

-- ---------- Unit 7  (102 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 7', 7);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'encourage', '鼓励', 1, 'word'),
  (@u, 'energy', '能量；精力', 2, 'word'),
  (@u, 'except', '除...以外', 3, 'word'),
  (@u, 'expert', '专家', 4, 'word'),
  (@u, 'expect', '期待', 5, 'word'),
  (@u, 'exist', '存在', 6, 'word'),
  (@u, 'expression', '表达', 7, 'word'),
  (@u, 'fear', '害怕', 8, 'word'),
  (@u, 'feeling', '感受', 9, 'word'),
  (@u, 'foreign', '外国的', 10, 'word'),
  (@u, 'global', '全球的', 11, 'word'),
  (@u, 'hand', '1 手；2 传递', 12, 'word'),
  (@u, 'happy', '快乐', 13, 'word'),
  (@u, 'homeless', '无家可归的', 14, 'word'),
  (@u, 'increasingly', '越来越', 15, 'word'),
  (@u, 'industrial', '工业的', 16, 'word'),
  (@u, 'journalist', '新闻工作者', 17, 'word'),
  (@u, 'middle', '中间', 18, 'word'),
  (@u, 'money', '钱', 19, 'word'),
  (@u, 'name', 'n. 名字；v. 命名', 20, 'word'),
  (@u, 'nothing', '没什么', 21, 'word'),
  (@u, 'period', '时期', 22, 'word'),
  (@u, 'poetry', '诗歌；艺术', 23, 'word'),
  (@u, 'predict', '预测', 24, 'word'),
  (@u, 'principle', '原则；原理', 25, 'word'),
  (@u, 'reality', '现实', 26, 'word'),
  (@u, 'recent/recently', '最近', 27, 'word'),
  (@u, 'response', '回应', 28, 'word'),
  (@u, 'return', '返回', 29, 'word'),
  (@u, 'shift', '转换', 30, 'word'),
  (@u, 'similar', '相似的', 31, 'word'),
  (@u, 'speak', '说', 32, 'word'),
  (@u, 'spend', '花费', 33, 'word'),
  (@u, 'strong', '强大的；强壮的', 34, 'word'),
  (@u, 'therefore', '因此', 35, 'word'),
  (@u, 'above', '在...之上', 36, 'word'),
  (@u, 'advertisement', '广告', 37, 'word'),
  (@u, 'advertiser', '广告客户', 38, 'word'),
  (@u, 'allow', '允许', 39, 'word'),
  (@u, 'analysis', '分析', 40, 'word'),
  (@u, 'attempt', '企图', 41, 'word'),
  (@u, 'board', '1 板子；2 董事会；3 登交通工具', 42, 'word'),
  (@u, 'break', '打破', 43, 'word'),
  (@u, 'car', '汽车', 44, 'word'),
  (@u, 'conclude', '下结论', 45, 'word'),
  (@u, 'cover', '覆盖', 46, 'word'),
  (@u, 'degree', '度数；学位', 47, 'word'),
  (@u, 'desire', '欲望', 48, 'word'),
  (@u, 'determine', '下决心', 49, 'word'),
  (@u, 'educate', '教育', 50, 'word'),
  (@u, 'enjoy', '享受', 51, 'word'),
  (@u, 'establish', '建立', 52, 'word'),
  (@u, 'fair', '公平的', 53, 'word'),
  (@u, 'hardly', '几乎不', 54, 'word'),
  (@u, 'himself', '他自己', 55, 'word'),
  (@u, 'historian', '历史学家', 56, 'word'),
  (@u, 'identify', '辨认', 57, 'word'),
  (@u, 'ignore', '忽略', 58, 'word'),
  (@u, 'immigration', '移民', 59, 'word'),
  (@u, 'institution', '机构；制度', 60, 'word'),
  (@u, 'key', 'n. 钥匙；adj. 关键的', 61, 'word'),
  (@u, 'largely', '大大地', 62, 'word'),
  (@u, 'local', '当地的', 63, 'word'),
  (@u, 'majority', '大多数', 64, 'word'),
  (@u, 'mass', '1 质量；2 大量', 65, 'word'),
  (@u, 'measure', 'v. 测量；n. 措施', 66, 'word'),
  (@u, 'model', '1 模特；2 模型；3 模范', 67, 'word'),
  (@u, 'movement', '1 动作；2 运动', 68, 'word'),
  (@u, 'nuclear', '核能的', 69, 'word'),
  (@u, 'plant', '1 种植；2 植物', 70, 'word'),
  (@u, 'position', '位置；职位', 71, 'word'),
  (@u, 'push', '1 推；2 逼', 72, 'word'),
  (@u, 'railroad', '铁路', 73, 'word'),
  (@u, 'reader', '读者', 74, 'word'),
  (@u, 'really', '真实地', 75, 'word'),
  (@u, 'refer', '涉及', 76, 'word'),
  (@u, 'reflect', '1 反映；反射；2 深思', 77, 'word'),
  (@u, 'relate', '相关', 78, 'word'),
  (@u, 'relationship', '关系', 79, 'word'),
  (@u, 'respect', '1 尊重；2 方面', 80, 'word'),
  (@u, 'responsible', '负责的', 81, 'word'),
  (@u, 'rich', '1 有钱的；2 丰富的', 82, 'word'),
  (@u, 'sentence', 'n. 句子；v. 宣判', 83, 'word'),
  (@u, 'sign', 'v. 签署；n. 符号', 84, 'word'),
  (@u, 'simply', '仅仅', 85, 'word'),
  (@u, 'stand', '1 站立；2 忍受', 86, 'word'),
  (@u, 'stop', '停止', 87, 'word'),
  (@u, 'third', '第三', 88, 'word'),
  (@u, 'threat', '威胁', 89, 'word'),
  (@u, 'threaten', '威胁', 90, 'word'),
  (@u, 'title', '标题', 91, 'word'),
  (@u, 'track', 'n. 轨迹；v. 追踪', 92, 'word'),
  (@u, 'unique', '独特的', 93, 'word'),
  (@u, 'various/variation/variable/variety', '不同；多样', 94, 'word'),
  (@u, 'affect', '影响', 95, 'word'),
  (@u, 'effect', '效果', 96, 'word'),
  (@u, 'agency', '机构', 97, 'word'),
  (@u, 'alone', '独自的', 98, 'word'),
  (@u, 'capital', '1 首都；2 资本', 99, 'word'),
  (@u, 'career', '事业', 100, 'word'),
  (@u, 'complex', '复杂', 101, 'word'),
  (@u, 'current', '现在的', 102, 'word');

-- ---------- Unit 8  (86 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 8', 8);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'deep', '深的', 1, 'word'),
  (@u, 'design', '设计', 2, 'word'),
  (@u, 'doubt', '怀疑', 3, 'word'),
  (@u, 'draw', '1 画；2 引起；吸引', 4, 'word'),
  (@u, 'drive', '1 驾驶；2 驱动', 5, 'word'),
  (@u, 'everything', '一切', 6, 'word'),
  (@u, 'executive', '管理者；执行者', 7, 'word'),
  (@u, 'father', '爸爸', 8, 'word'),
  (@u, 'friend', '朋友', 9, 'word'),
  (@u, 'further', '更远', 10, 'word'),
  (@u, 'gain', '获得', 11, 'word'),
  (@u, 'height', '高度', 12, 'word'),
  (@u, 'imply', '暗示', 13, 'word'),
  (@u, 'importance', '重要性', 14, 'word'),
  (@u, 'judgment', '判断', 15, 'word'),
  (@u, 'lawyer', '律师', 16, 'word'),
  (@u, 'link', '链接', 17, 'word'),
  (@u, 'light', 'adj. 轻的；n. 光；v. 点燃', 18, 'word'),
  (@u, 'mainly', '主要的', 19, 'word'),
  (@u, 'manager', '经理', 20, 'word'),
  (@u, 'near', '附近', 21, 'word'),
  (@u, 'net', '网', 22, 'word'),
  (@u, 'network', '网络', 23, 'word'),
  (@u, 'observe', '观察', 24, 'word'),
  (@u, 'obvious', '明显的', 25, 'word'),
  (@u, 'occur', '发生', 26, 'word'),
  (@u, 'organization', '组织', 27, 'word'),
  (@u, 'project', 'n. 项目；v. 投射', 28, 'word'),
  (@u, 'promise', '承诺', 29, 'word'),
  (@u, 'promote', '1 促进；2 推销', 30, 'word'),
  (@u, 'pursuit', '追求', 31, 'word'),
  (@u, 'realize', '1 意识到；2 实现', 32, 'word'),
  (@u, 'religion', '宗教', 33, 'word'),
  (@u, 'religious', '宗教的', 34, 'word'),
  (@u, 'review', '1 复习；2 评论', 35, 'word'),
  (@u, 'robot', '机器人', 36, 'word'),
  (@u, 'slavery', '奴隶制', 37, 'word'),
  (@u, 'tradition', '传统', 38, 'word'),
  (@u, 'upon', '在...之上', 39, 'word'),
  (@u, 'soon', '一会儿', 40, 'word'),
  (@u, 'spread', '散播', 41, 'word'),
  (@u, 'stay', '逗留', 42, 'word'),
  (@u, 'street', '街道', 43, 'word'),
  (@u, 'technological', '技术的', 44, 'word'),
  (@u, 'tool', '工具', 45, 'word'),
  (@u, 'variety', '多样', 46, 'word'),
  (@u, 'west', '西方', 47, 'word'),
  (@u, 'academic', '学术的', 48, 'word'),
  (@u, 'aim', 'n. 目的；v. 瞄准', 49, 'word'),
  (@u, 'alter', '改变', 50, 'word'),
  (@u, 'amount', '数量', 51, 'word'),
  (@u, 'anti-', '反', 52, 'word'),
  (@u, 'anyone', '任何人', 53, 'word'),
  (@u, 'apply', '1 应用；2 申请', 54, 'word'),
  (@u, 'argument', '争论', 55, 'word'),
  (@u, 'aspect', '方面', 56, 'word'),
  (@u, 'authority', '1 权威；2 权力；3 当局', 57, 'word'),
  (@u, 'away', '离去', 58, 'word'),
  (@u, 'belief', '信念', 59, 'word'),
  (@u, 'below', '在...之下', 60, 'word'),
  (@u, 'chance', '1 机会；2 概率', 61, 'word'),
  (@u, 'church', '1 教堂；2 教会', 62, 'word'),
  (@u, 'communication', '交流', 63, 'word'),
  (@u, 'conscious', '1 清醒的；2 有意识的', 64, 'word'),
  (@u, 'consumption', '消费', 65, 'word'),
  (@u, 'contribute', '贡献', 66, 'word'),
  (@u, 'corporation', '大公司', 67, 'word'),
  (@u, 'discover', '发现', 68, 'word'),
  (@u, 'divide', '划分', 69, 'word'),
  (@u, 'drop', '落', 70, 'word'),
  (@u, 'easily', '容易地', 71, 'word'),
  (@u, 'element', '元素', 72, 'word'),
  (@u, 'everyone', '每一个人', 73, 'word'),
  (@u, 'express', '1 表达；2 快递', 74, 'word'),
  (@u, 'eye', '眼睛', 75, 'word'),
  (@u, 'factor', '因素', 76, 'word'),
  (@u, 'favor', 'v. 偏爱；n. 帮忙', 77, 'word'),
  (@u, 'figure', 'n. 数字；计算', 78, 'word'),
  (@u, 'former', '前者', 79, 'word'),
  (@u, 'fully', '完全地', 80, 'word'),
  (@u, 'game', '游戏', 81, 'word'),
  (@u, 'garden', '花园', 82, 'word'),
  (@u, 'grant', '授予', 83, 'word'),
  (@u, 'hear', '听到', 84, 'word'),
  (@u, 'here', '这', 85, 'word'),
  (@u, 'humor', '幽默', 86, 'word');

-- ---------- Unit 9  (103 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 9', 9);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'hundred', '一百', 1, 'word'),
  (@u, 'ill', '生病的', 2, 'word'),
  (@u, 'label', 'n. 标签；v. 打标签', 3, 'word'),
  (@u, 'mental', '1 心理的；2 精神的', 4, 'word'),
  (@u, 'physical', '1 身体的；2 实体的', 5, 'word'),
  (@u, 'mention', '提到', 6, 'word'),
  (@u, 'month', '月份', 7, 'word'),
  (@u, 'negative', '否定的', 8, 'word'),
  (@u, 'positive', '肯定的', 9, 'word'),
  (@u, 'original', '原始的', 10, 'word'),
  (@u, 'panel', '面板', 11, 'word'),
  (@u, 'phenomenon', '现象', 12, 'word'),
  (@u, 'politic', '政治', 13, 'word'),
  (@u, 'powerful', '强大的', 14, 'word'),
  (@u, 'private', '私人的', 15, 'word'),
  (@u, 'sale', '销售', 16, 'word'),
  (@u, 'progress', '进步', 17, 'word'),
  (@u, 'range', '范围', 18, 'word'),
  (@u, 'relation', '关系', 19, 'word'),
  (@u, 'respond', '反应', 20, 'word'),
  (@u, 'root', '根', 21, 'word'),
  (@u, 'security', '安全', 22, 'word'),
  (@u, 'shareholder', '股东', 23, 'word'),
  (@u, 'shop', 'n. 商店；v. 购物', 24, 'word'),
  (@u, 'sort', 'n. 种类；v. 分类', 25, 'word'),
  (@u, 'source', '来源', 26, 'word'),
  (@u, 'south', '南方', 27, 'word'),
  (@u, 'special', '特别的', 28, 'word'),
  (@u, 'status', '地位', 29, 'word'),
  (@u, 'stick', 'n. 棍子；v. 粘连', 30, 'word'),
  (@u, 'stick to', '坚持', 31, 'word'),
  (@u, 'stock', '股份', 32, 'word'),
  (@u, 'store', 'n. 商店；v. 储存', 33, 'word'),
  (@u, 'teacher', 'n. 老师', 34, 'word'),
  (@u, 'type', 'n. 种类；v. 打字', 35, 'word'),
  (@u, 'universe', '宇宙', 36, 'word'),
  (@u, 'usual', '通常', 37, 'word'),
  (@u, 'wave/trend/tide', '潮流', 38, 'word'),
  (@u, 'whole', '整个的', 39, 'word'),
  (@u, 'wide/broad', '宽的', 40, 'word'),
  (@u, 'access', '进入', 41, 'word'),
  (@u, 'actually', '其实', 42, 'word'),
  (@u, 'along', '沿着', 43, 'word'),
  (@u, 'anthropology', '人类学', 44, 'word'),
  (@u, 'appeal', '恳求', 45, 'word'),
  (@u, 'behavioral', '行为的', 46, 'word'),
  (@u, 'bill', '1 账单；2 钞票', 47, 'word'),
  (@u, 'celebrity', '名人', 48, 'word'),
  (@u, 'comment', '评论', 49, 'word'),
  (@u, 'confuse', '使困惑', 50, 'word'),
  (@u, 'continent', '大陆；大洲', 51, 'word'),
  (@u, 'credibility', '可信性', 52, 'word'),
  (@u, 'cure', '治愈', 53, 'word'),
  (@u, 'daily', '日常的', 54, 'word'),
  (@u, 'decide', '决定', 55, 'word'),
  (@u, 'despite', '尽管', 56, 'word'),
  (@u, 'draft', '草稿', 57, 'word'),
  (@u, 'earth', '地球', 58, 'word'),
  (@u, 'emotional', '情绪的', 59, 'word'),
  (@u, 'emphasize', '强调', 60, 'word'),
  (@u, 'exercise', '练习', 61, 'word'),
  (@u, 'fill', '填充', 62, 'word'),
  (@u, 'fish', '鱼', 63, 'word'),
  (@u, 'fishery', '渔业', 64, 'word'),
  (@u, 'formal/former', '正式的；前任的', 65, 'word'),
  (@u, 'four', '四', 66, 'word'),
  (@u, 'highly', '高度地', 67, 'word'),
  (@u, 'historical', '历史的', 68, 'word'),
  (@u, 'hope', '希望', 69, 'word'),
  (@u, 'income', '收入', 70, 'word'),
  (@u, 'indeed', '确实', 71, 'word'),
  (@u, 'independent', '独立的', 72, 'word'),
  (@u, 'invention', '发明', 73, 'word'),
  (@u, 'justify', '证明', 74, 'word'),
  (@u, 'material', '物质的', 75, 'word'),
  (@u, 'me', '我', 76, 'word'),
  (@u, 'medicine', '药', 77, 'word'),
  (@u, 'moreover', '而且', 78, 'word'),
  (@u, 'nearly', '几乎', 79, 'word'),
  (@u, 'neglect/ignore', '忽视', 80, 'word'),
  (@u, 'observer', '观察者', 81, 'word'),
  (@u, 'official', '官方的', 82, 'word'),
  (@u, 'oppose', '反对', 83, 'word'),
  (@u, 'particularly', '尤其', 84, 'word'),
  (@u, 'philosopher', '哲学家', 85, 'word'),
  (@u, 'picture', '图画', 86, 'word'),
  (@u, 'player', '玩家', 87, 'word'),
  (@u, 'press', 'v. 按压；n. 新闻', 88, 'word'),
  (@u, 'prospect', '前景', 89, 'word'),
  (@u, 'protection', '保护', 90, 'word'),
  (@u, 'province', '省', 91, 'word'),
  (@u, 'recognize', '认出', 92, 'word'),
  (@u, 'rely', '依赖', 93, 'word'),
  (@u, 'remember', '记得', 94, 'word'),
  (@u, 'replace', '代替', 95, 'word'),
  (@u, 'resource', '资源', 96, 'word'),
  (@u, 'retailer', '零售商', 97, 'word'),
  (@u, 'safety', '安全', 98, 'word'),
  (@u, 'secure', '安全的', 99, 'word'),
  (@u, 'senior', '年长的', 100, 'word'),
  (@u, 'serve', '服务', 101, 'word'),
  (@u, 'side', '边', 102, 'word'),
  (@u, 'sleep', '睡觉', 103, 'word');

-- ---------- Unit 10  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 10', 10);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'specific', '明确的；具体的', 1, 'word'),
  (@u, 'statement', '陈述；声明', 2, 'word'),
  (@u, 'successful', '成功的', 3, 'word'),
  (@u, 'sure', '当然；确信的', 4, 'word'),
  (@u, 'surprise', '惊喜；惊讶', 5, 'word'),
  (@u, 'survive', '幸存', 6, 'word'),
  (@u, 'technical', '工艺的；技术的', 7, 'word'),
  (@u, 'travel', '旅行', 8, 'word'),
  (@u, 'visit', '拜访', 9, 'word'),
  (@u, 'warn', '警告', 10, 'word'),
  (@u, 'white', '白的', 11, 'word'),
  (@u, 'widely', '宽泛的', 12, 'word'),
  (@u, 'win', '赢得', 13, 'word'),
  (@u, 'wrong', '错的', 14, 'word'),
  (@u, 'achievement', '成就', 15, 'word'),
  (@u, 'administration', '管理', 16, 'word'),
  (@u, 'answer', '回答', 17, 'word'),
  (@u, 'arise', '产生；出现', 18, 'word'),
  (@u, 'association', '协会', 19, 'word'),
  (@u, 'behind', '在……后面', 20, 'word'),
  (@u, 'bias', '偏斜的；偏见', 21, 'word'),
  (@u, 'boom', '激增', 22, 'word'),
  (@u, 'broad', '辽阔的', 23, 'word'),
  (@u, 'catch', '捉住；追上', 24, 'word'),
  (@u, 'center', '中心', 25, 'word'),
  (@u, 'CEO', '首席执行官', 26, 'word'),
  (@u, 'chairman', '主席', 27, 'word'),
  (@u, 'chemical', '化学的', 28, 'word'),
  (@u, 'chief', '主要的', 29, 'word'),
  (@u, 'city', '城市', 30, 'word'),
  (@u, 'climate', '气候', 31, 'word'),
  (@u, 'congress', '国会', 32, 'word'),
  (@u, 'convince', '说服', 33, 'word'),
  (@u, 'crime', '犯罪', 34, 'word'),
  (@u, 'cut', '切割', 35, 'word'),
  (@u, 'description', '描述', 36, 'word'),
  (@u, 'detail', '细节', 37, 'word'),
  (@u, 'direct', 'v. 指方向；adj. 直接的', 38, 'word'),
  (@u, 'direction', '方向', 39, 'word'),
  (@u, 'director', '董事；主任；主管', 40, 'word'),
  (@u, 'disease', '疾病', 41, 'word'),
  (@u, 'drink', 'n. 饮料；v. 喝', 42, 'word'),
  (@u, 'economist', '经济学家', 43, 'word'),
  (@u, 'educational', '教育的', 44, 'word'),
  (@u, 'emphasis', '重点', 45, 'word'),
  (@u, 'entirely', '完全地', 46, 'word'),
  (@u, 'escape', '逃跑', 47, 'word'),
  (@u, 'event', '事件', 48, 'word'),
  (@u, 'exchange', '交换', 49, 'word'),
  (@u, 'explanation', '解释', 50, 'word'),
  (@u, 'female', '女性', 51, 'word'),
  (@u, 'join', '加入；参加', 52, 'word'),
  (@u, 'fit', '合适的', 53, 'word'),
  (@u, 'five', '五', 54, 'word'),
  (@u, 'flow', '流动', 55, 'word'),
  (@u, 'frequently', '频繁地', 56, 'word'),
  (@u, 'full', '满的', 57, 'word'),
  (@u, 'futurist', '未来主义者', 58, 'word'),
  (@u, 'heavy', '厚重的', 59, 'word'),
  (@u, 'illustrate', '阐明', 60, 'word'),
  (@u, 'immediate', '立即的', 61, 'word'),
  (@u, 'impact', '影响', 62, 'word'),
  (@u, 'inevitable', '不可避免的', 63, 'word'),
  (@u, 'innovation', '革新', 64, 'word'),
  (@u, 'intellect', '智力；才华', 65, 'word'),
  (@u, 'journalism', '新闻业', 66, 'word'),
  (@u, 'judge', 'v. 判断；v. 评头论足；n. 法官', 67, 'word'),
  (@u, 'jump', '跳', 68, 'word'),
  (@u, 'kill', '杀', 69, 'word'),
  (@u, 'letter', '字母；信', 70, 'word'),
  (@u, 'lie', '1 躺；2 谎言', 71, 'word'),
  (@u, 'magazine', '杂志', 72, 'word'),
  (@u, 'maintain', '维持；保养', 73, 'word'),
  (@u, 'manner', '1 方式；2 礼貌', 74, 'word'),
  (@u, 'objective', '客观的；目标', 75, 'word'),
  (@u, 'optimistic', '乐观的', 76, 'word'),
  (@u, 'otherwise', '否则', 77, 'word'),
  (@u, 'overall', '总共', 78, 'word'),
  (@u, 'payment', '支付', 79, 'word'),
  (@u, 'planet', '星球', 80, 'word'),
  (@u, 'poverty', '贫困', 81, 'word'),
  (@u, 'prevent', '预防', 82, 'word'),
  (@u, 'publisher', '出版商', 83, 'word'),
  (@u, 'quit', '离开；停止', 84, 'word'),
  (@u, 'radical', '激进的', 85, 'word'),
  (@u, 'reform', '改革', 86, 'word'),
  (@u, 'reject', '拒绝', 87, 'word'),
  (@u, 'remove', '消除', 88, 'word'),
  (@u, 'responsibility', '责任', 89, 'word'),
  (@u, 'rest', '休息', 90, 'word'),
  (@u, 'safe', '安全', 91, 'word'),
  (@u, 'separate', '使分离', 92, 'word'),
  (@u, 'serious', '1 严重的；2 严肃的', 93, 'word'),
  (@u, 'shape', 'n. 形状；v. 塑造', 94, 'word'),
  (@u, 'soccer', '足球', 95, 'word'),
  (@u, 'sometimes', '有时', 96, 'word');

-- ---------- Unit 11  (107 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 11', 11);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'speed', '速度', 1, 'word'),
  (@u, 'step', '1 步子；2 走', 2, 'word'),
  (@u, 'suicide', '自杀', 3, 'word'),
  (@u, 'supply', '供应', 4, 'word'),
  (@u, 'suppose', '假定；认为', 5, 'word'),
  (@u, 'user', '用户', 6, 'word'),
  (@u, 'treatment', '治疗；对待', 7, 'word'),
  (@u, 'trouble', '麻烦', 8, 'word'),
  (@u, 'unless', '除非', 9, 'word'),
  (@u, 'urge', '力劝；渴望', 10, 'word'),
  (@u, 'wealth', '财富', 11, 'word'),
  (@u, 'wholesale', '批发', 12, 'word'),
  (@u, 'workforce', '劳动力', 13, 'word'),
  (@u, 'abuse', '1 滥用；2 虐待', 14, 'word'),
  (@u, 'acquire', '获得；购得', 15, 'word'),
  (@u, 'advertise', '广告', 16, 'word'),
  (@u, 'again', '再一次', 17, 'word'),
  (@u, 'agreement', '共识；协定', 18, 'word'),
  (@u, 'anthropologist', '人类学家', 19, 'word'),
  (@u, 'appropriate', '恰当的；合适的', 20, 'word'),
  (@u, 'assume', '假设', 21, 'word'),
  (@u, 'attract', '吸引', 22, 'word'),
  (@u, 'ban', '禁止；禁令', 23, 'word'),
  (@u, 'audience', '听众；观众', 24, 'word'),
  (@u, 'background', '背景', 25, 'word'),
  (@u, 'biological', '生物的', 26, 'word'),
  (@u, 'birth', '出生', 27, 'word'),
  (@u, 'bite', '咬', 28, 'word'),
  (@u, 'category', '种类', 29, 'word'),
  (@u, 'channel', '频道；途径', 30, 'word'),
  (@u, 'characteristic', '特征', 31, 'word'),
  (@u, 'characterize', '具有……特征', 32, 'word'),
  (@u, 'check', '1 检查；2 制止', 33, 'word'),
  (@u, 'circuit', '电路；环线', 34, 'word'),
  (@u, 'circumstance', '状况；情形', 35, 'word'),
  (@u, 'colleague', '同事', 36, 'word'),
  (@u, 'commit', '1 承诺；2 犯下', 37, 'word'),
  (@u, 'competitive', '竞争的', 38, 'word'),
  (@u, 'complete', '完成；完整的', 39, 'word'),
  (@u, 'completely', '完全地；彻底地', 40, 'word'),
  (@u, 'conflict', '冲突；矛盾', 41, 'word'),
  (@u, 'conventional', '惯例的', 42, 'word'),
  (@u, 'creation', '创造；作品', 43, 'word'),
  (@u, 'crucial', '关键的', 44, 'word'),
  (@u, 'crude', '粗略的', 45, 'word'),
  (@u, 'department', '部门', 46, 'word'),
  (@u, 'digital', '数码的', 47, 'word'),
  (@u, 'direction', '方向', 48, 'word'),
  (@u, 'distribution', '分配；分布', 49, 'word'),
  (@u, 'dollar', '美元', 50, 'word'),
  (@u, 'due to', '由于', 51, 'word'),
  (@u, 'eat', '吃', 52, 'word'),
  (@u, 'electronic', '电子的', 53, 'word'),
  (@u, 'e-mail', '电子邮件', 54, 'word'),
  (@u, 'embryo', '胚胎', 55, 'word'),
  (@u, 'emotion', '情绪', 56, 'word'),
  (@u, 'employ', '雇佣；采取', 57, 'word'),
  (@u, 'employment', '就业', 58, 'word'),
  (@u, 'enable', '使……能够', 59, 'word'),
  (@u, 'engage', '参与', 60, 'word'),
  (@u, 'equal', '平等的；等于', 61, 'word'),
  (@u, 'examine', '检查', 62, 'word'),
  (@u, 'expose', '暴露；接触', 63, 'word'),
  (@u, 'fight', '斗争；打', 64, 'word'),
  (@u, 'finally', '终于', 65, 'word'),
  (@u, 'generate', '产生', 66, 'word'),
  (@u, 'geological', '地质学的', 67, 'word'),
  (@u, 'health-care', '医疗服务', 68, 'word'),
  (@u, 'ideal', '理想', 69, 'word'),
  (@u, 'implication', '影响；后果；暗示', 70, 'word'),
  (@u, 'indicate', '表明', 71, 'word'),
  (@u, 'infrastructure', '基础设施', 72, 'word'),
  (@u, 'insist', '坚持', 73, 'word'),
  (@u, 'insurance', '保险', 74, 'word'),
  (@u, 'land', '土地', 75, 'word'),
  (@u, 'laugh', '笑', 76, 'word'),
  (@u, 'lifestyle', '生活方式', 77, 'word'),
  (@u, 'love', '爱', 78, 'word'),
  (@u, 'literature', '文学', 79, 'word'),
  (@u, 'manage', '1 管理；2 应对；处理', 80, 'word'),
  (@u, 'mark', '标记', 81, 'word'),
  (@u, 'mechanical', '机械的', 82, 'word'),
  (@u, 'memory', '记忆', 83, 'word'),
  (@u, 'sit', '坐', 84, 'word'),
  (@u, 'mostly', '大多', 85, 'word'),
  (@u, 'native', '土生土长的', 86, 'word'),
  (@u, 'night', '夜', 87, 'word'),
  (@u, 'notion', '观念', 88, 'word'),
  (@u, 'object', '物体；反对', 89, 'word'),
  (@u, 'obtain', '获得', 90, 'word'),
  (@u, 'office', '办公室', 91, 'word'),
  (@u, 'opposite', '相反的', 92, 'word'),
  (@u, 'parallel', '平行的', 93, 'word'),
  (@u, 'performance', '1 表现；性能；2 表演', 94, 'word'),
  (@u, 'physician', '医生', 95, 'word'),
  (@u, 'popularity', '受欢迎度', 96, 'word'),
  (@u, 'positive/negative', '正／负', 97, 'word'),
  (@u, 'possibility', '可能性', 98, 'word'),
  (@u, 'practical', '实际的；实用的', 99, 'word'),
  (@u, 'presence', '到场；存在', 100, 'word'),
  (@u, 'primary', '首要的；初级的', 101, 'word'),
  (@u, 'professor', '教授', 102, 'word'),
  (@u, 'propose', '提议', 103, 'word'),
  (@u, 'purchase', '购买', 104, 'word'),
  (@u, 'purpose', '目的', 105, 'word'),
  (@u, 'quickly', '快', 106, 'word'),
  (@u, 'quite', '相当的', 107, 'word');

-- ---------- Unit 12  (100 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 12', 12);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'ready', '准备好的', 1, 'word'),
  (@u, 'requirement', '要求', 2, 'word'),
  (@u, 'retail', '零售', 3, 'word'),
  (@u, 'revival', '复兴', 4, 'word'),
  (@u, 'reward', '回报', 5, 'word'),
  (@u, 'scale', '规模', 6, 'word'),
  (@u, 'scholar', '学者', 7, 'word'),
  (@u, 'sensitive', '敏感的', 8, 'word'),
  (@u, 'shock', '震惊', 9, 'word'),
  (@u, 'short', '短；缺', 10, 'word'),
  (@u, 'significant', '重大的', 11, 'word'),
  (@u, 'size', '尺寸；规模', 12, 'word'),
  (@u, 'smile', '笑', 13, 'word'),
  (@u, 'smoke', '烟；抽', 14, 'word'),
  (@u, 'sound', 'n. 声音；adj. 好的', 15, 'word'),
  (@u, 'statistic', '统计', 16, 'word'),
  (@u, 'supreme', '最高', 17, 'word'),
  (@u, 'theater', '剧院', 18, 'word'),
  (@u, 'thousand', '千', 19, 'word'),
  (@u, 'town', '城镇', 20, 'word'),
  (@u, 'townsfolk', '市民', 21, 'word'),
  (@u, 'tree', '树', 22, 'word'),
  (@u, 'trust', '信任', 23, 'word'),
  (@u, 'truth', '真相', 24, 'word'),
  (@u, 'universal', '普遍的', 25, 'word'),
  (@u, 'wait', '等', 26, 'word'),
  (@u, 'unlikely', '不太可能的', 27, 'word'),
  (@u, 'wake', '醒', 28, 'word'),
  (@u, 'wish', '希望', 29, 'word'),
  (@u, 'witness', '1 见证；2 目睹', 30, 'word'),
  (@u, 'worth', '价值；值', 31, 'word'),
  (@u, 'abandon', '抛弃；放弃', 32, 'word'),
  (@u, 'afford', '负担得起', 33, 'word'),
  (@u, 'alphabetically', '字母顺序的', 34, 'word'),
  (@u, 'apparently', '显然的', 35, 'word'),
  (@u, 'attractive', '有吸引力的', 36, 'word'),
  (@u, 'biomass', '生物总量', 37, 'word'),
  (@u, 'blame', '责怪', 38, 'word'),
  (@u, 'blueprint', '蓝图', 39, 'word'),
  (@u, 'buyer', '买家', 40, 'word'),
  (@u, 'campaign', '活动', 41, 'word'),
  (@u, 'capable', '能够的', 42, 'word'),
  (@u, 'cell', '细胞', 43, 'word'),
  (@u, 'charge', '管理；收费；控告；充', 44, 'word'),
  (@u, 'choice', '选择', 45, 'word'),
  (@u, 'clearly', '清晰的', 46, 'word'),
  (@u, 'code', 'n. 代码；v. 编码', 47, 'word'),
  (@u, 'collection', '收集', 48, 'word'),
  (@u, 'conservation', '保护', 49, 'word'),
  (@u, 'conservative', '保守的', 50, 'word'),
  (@u, 'content', '1 内容；2 满意的', 51, 'word'),
  (@u, 'convention', '大会；惯例', 52, 'word'),
  (@u, 'cope', '处理', 53, 'word'),
  (@u, 'creationism', '创造论', 54, 'word'),
  (@u, 'creationist', '创造论者', 55, 'word'),
  (@u, 'creativity', '创造力', 56, 'word'),
  (@u, 'critical', '1 批评的；2 关键的；3 审慎的；有判断力的', 57, 'word'),
  (@u, 'danger', '危险', 58, 'word'),
  (@u, 'definition', '定义', 59, 'word'),
  (@u, 'demonstrate', '证明；表现', 60, 'word'),
  (@u, 'deny', '否认', 61, 'word'),
  (@u, 'dependent', '依赖的', 62, 'word'),
  (@u, 'domestic', '国内的', 63, 'word'),
  (@u, 'dominant', '主宰的；统治的', 64, 'word'),
  (@u, 'duty', '1 义务；职责；2 税', 65, 'word'),
  (@u, 'dynamic', '动态的', 66, 'word'),
  (@u, 'employer/employee', '老板/员工', 67, 'word'),
  (@u, 'enforcement', '执行；实施', 68, 'word'),
  (@u, 'enter', '1 进入', 69, 'word'),
  (@u, 'enter', '2 输入', 70, 'word'),
  (@u, 'equally', '均等的', 71, 'word'),
  (@u, 'error', '错误', 72, 'word'),
  (@u, 'estimate', '估计', 73, 'word'),
  (@u, 'eventually', '最终地', 74, 'word'),
  (@u, 'everyday', 'adj. 日常的', 75, 'word'),
  (@u, 'evolutionary', '进化的', 76, 'word'),
  (@u, 'evolve', '进化', 77, 'word'),
  (@u, 'existence', '存在', 78, 'word'),
  (@u, 'explore', '探索', 79, 'word'),
  (@u, 'extend', '延伸；延续；扩大', 80, 'word'),
  (@u, 'extent', '程度', 81, 'word'),
  (@u, 'extremely', '极度地', 82, 'word'),
  (@u, 'forget', '忘记', 83, 'word'),
  (@u, 'fulfill', '1 满足；2 实现', 84, 'word'),
  (@u, 'gather', '聚集', 85, 'word'),
  (@u, 'giant', '巨大的', 86, 'word'),
  (@u, 'harmful', '有害的', 87, 'word'),
  (@u, 'head', '1 头；2 朝……行进', 88, 'word'),
  (@u, 'hijack', '劫持', 89, 'word'),
  (@u, 'hour', '小时', 90, 'word'),
  (@u, 'imagine', '想象', 91, 'word'),
  (@u, 'injury', '外伤', 92, 'word'),
  (@u, 'for instance', '举例', 93, 'word'),
  (@u, 'integrate', '合并；融合', 94, 'word'),
  (@u, 'invite', '邀请', 95, 'word'),
  (@u, 'laughter', '笑', 96, 'word'),
  (@u, 'let', '让', 97, 'word'),
  (@u, 'liability', '负担', 98, 'word'),
  (@u, 'marketer', '市场营销者', 99, 'word'),
  (@u, 'match', '1 比赛；2 配对；3 火柴', 100, 'word');

-- ---------- Unit 13  (109 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 13', 13);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'mere', '仅仅', 1, 'word'),
  (@u, 'merger', '合并', 2, 'word'),
  (@u, 'mode', '模式', 3, 'word'),
  (@u, 'moment', '时刻；瞬间', 4, 'word'),
  (@u, 'motion', '移动；运动', 5, 'word'),
  (@u, 'narrow', '窄', 6, 'word'),
  (@u, 'negotiate', '谈判；协商', 7, 'word'),
  (@u, 'newly', '新近', 8, 'word'),
  (@u, 'nineteenth', '第十九', 9, 'word'),
  (@u, 'none', '没有', 10, 'word'),
  (@u, 'ocean', '海', 11, 'word'),
  (@u, 'odd', '奇怪', 12, 'word'),
  (@u, 'officer', '官员', 13, 'word'),
  (@u, 'operate', '1 操作；2 运转', 14, 'word'),
  (@u, 'page', '页面', 15, 'word'),
  (@u, 'partner', '搭档；合伙人', 16, 'word'),
  (@u, 'performer', '表演者', 17, 'word'),
  (@u, 'phrase', '短语；习语', 18, 'word'),
  (@u, 'politician', '政客', 19, 'word'),
  (@u, 'possibly', '可能的', 20, 'word'),
  (@u, 'post', 'n. 邮政；v. 发帖', 21, 'word'),
  (@u, 'preserve', '保护；维持', 21, 'word'),
  (@u, 'previous', '先前的', 22, 'word'),
  (@u, 'properly', '正确地', 23, 'word'),
  (@u, 'property', '财产', 24, 'word'),
  (@u, 'psychology', '心理学', 25, 'word'),
  (@u, 'puzzle', '困惑；谜题', 26, 'word'),
  (@u, 'regulation', '规章；制度', 27, 'word'),
  (@u, 'remark', '评论', 28, 'word'),
  (@u, 'represent', '代表', 29, 'word'),
  (@u, 'reputation', '名誉；声望', 30, 'word'),
  (@u, 'revenue/income', '收入', 31, 'word'),
  (@u, 'revolution', '革命', 32, 'word'),
  (@u, 'royal', '皇室的', 33, 'word'),
  (@u, 'loyal', '忠诚的', 34, 'word'),
  (@u, 'satisfy', '满足', 35, 'word'),
  (@u, 'sector', '领域', 36, 'word'),
  (@u, 'select', '选择', 37, 'word'),
  (@u, 'selection', '选择', 38, 'word'),
  (@u, 'series', '一系列', 39, 'word'),
  (@u, 'seven', '七', 40, 'word'),
  (@u, 'significance', '重要性', 41, 'word'),
  (@u, 'slow', '慢的', 42, 'word'),
  (@u, 'solve', '解决', 43, 'word'),
  (@u, 'someone', '某人', 44, 'word'),
  (@u, 'sport', '体育运动', 45, 'word'),
  (@u, 'spy', '间谍', 46, 'word'),
  (@u, 'strain', '损伤', 47, 'word'),
  (@u, 'strategy', '策略；战略', 48, 'word'),
  (@u, 'struggle', '1 奋斗；2 挣扎', 49, 'word'),
  (@u, 'sustain', '持续；维持', 50, 'word'),
  (@u, 'task', '任务', 51, 'word'),
  (@u, 'mission', '任务', 52, 'word'),
  (@u, 'teenager', '青少年', 53, 'word'),
  (@u, 'thought', '想法', 54, 'word'),
  (@u, 'topic', '话题', 55, 'word'),
  (@u, 'toward', '朝着；向着', 56, 'word'),
  (@u, 'trace', '查找；追溯', 57, 'word'),
  (@u, 'transaction', '交易', 58, 'word'),
  (@u, 'unlike', '不像', 59, 'word'),
  (@u, 'upset', '烦恼', 60, 'word'),
  (@u, 'version', '版本', 61, 'word'),
  (@u, 'vote', '投票', 62, 'word'),
  (@u, 'warm', '温暖的', 63, 'word'),
  (@u, 'watch', '1 提防；2 观看；3 手表', 64, 'word'),
  (@u, 'wear', '穿戴', 65, 'word'),
  (@u, 'addict', 'n. 上瘾的人；v. 上瘾', 66, 'word'),
  (@u, 'air', '空气', 67, 'word'),
  (@u, 'address', '1 应对；处理；2 说；3 地址', 68, 'word'),
  (@u, 'admire', '钦佩；欣赏', 69, 'word'),
  (@u, 'admission', '准入；录取', 70, 'word'),
  (@u, 'admit', '1 承认；2 准入', 71, 'word'),
  (@u, 'alphabet', '字母表', 72, 'word'),
  (@u, 'amaze', '使吃惊', 73, 'word'),
  (@u, 'ancestor', '祖先', 74, 'word'),
  (@u, 'application', '应用；申请', 75, 'word'),
  (@u, 'arrival', '到达', 76, 'word'),
  (@u, 'arrive', '到达', 77, 'word'),
  (@u, 'artificial', '人造的', 78, 'word'),
  (@u, 'artist', '艺术家', 79, 'word'),
  (@u, 'assert', '坚称；断言', 80, 'word'),
  (@u, 'assess', '评估', 81, 'word'),
  (@u, 'access', '进入；使用', 82, 'word'),
  (@u, 'attack', '攻击', 83, 'word'),
  (@u, 'attend', '参加', 84, 'word'),
  (@u, 'on behalf of', '代表', 85, 'word'),
  (@u, 'besides', '除了...之外；还', 86, 'word'),
  (@u, 'bird', '鸟', 87, 'word'),
  (@u, 'brief', '简短的', 88, 'word'),
  (@u, 'broadcast', '广播', 89, 'word'),
  (@u, 'broadly', '大体上', 90, 'word'),
  (@u, 'budget', '预算', 91, 'word'),
  (@u, 'businessman', '商人', 92, 'word'),
  (@u, 'candidate', '候选人', 93, 'word'),
  (@u, 'census', '人口普查', 94, 'word'),
  (@u, 'central', '中央的', 95, 'word'),
  (@u, 'character', '1 性格；2 特点；3 人品；4 角色', 96, 'word'),
  (@u, 'collect', '1 收集；2 领取', 97, 'word'),
  (@u, 'college', '大学', 98, 'word'),
  (@u, 'combine', '结合；组合', 99, 'word'),
  (@u, 'commission', '1 委员会；2 佣金', 100, 'word'),
  (@u, 'commodity', '商品', 101, 'word'),
  (@u, 'crisis', '危机', 102, 'word'),
  (@u, 'compete', '竞争', 103, 'word'),
  (@u, 'connect', '连接', 104, 'word'),
  (@u, 'consistently', '一贯的', 105, 'word'),
  (@u, 'contrary', '相反', 106, 'word'),
  (@u, 'cooperation', '合作', 107, 'word'),
  (@u, 'criticize', '批评', 108, 'word');

-- ---------- Unit 14  (85 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 14', 14);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'corporate', '公司的', 1, 'word'),
  (@u, 'couple', '一对', 2, 'word'),
  (@u, 'cry', '1 哭；2 喊叫', 3, 'word'),
  (@u, 'cycle', '1 循环；2 周期', 4, 'word'),
  (@u, 'dedicate to', '致力于', 5, 'word'),
  (@u, 'deserve', '应得', 6, 'word'),
  (@u, 'difficulty', '困难', 7, 'word'),
  (@u, 'discrimination', '歧视', 8, 'word'),
  (@u, 'discuss', '探讨', 9, 'word'),
  (@u, 'display', '显示', 10, 'word'),
  (@u, 'distinction', '区别；卓越', 11, 'word'),
  (@u, 'distinguish', '区分', 12, 'word'),
  (@u, 'diversity', '多样', 13, 'word'),
  (@u, 'downshift', '放慢', 14, 'word'),
  (@u, 'editor', '编辑', 15, 'word'),
  (@u, 'elite', '精英', 16, 'word'),
  (@u, 'enhance', '增强；提高', 17, 'word'),
  (@u, 'enormous', '巨大的', 18, 'word'),
  (@u, 'ensure', '确保', 19, 'word'),
  (@u, 'epidemic', '流行病', 20, 'word'),
  (@u, 'euthanasia', '安乐死', 21, 'word'),
  (@u, 'exactly', '1 准确地；2 到底', 22, 'word'),
  (@u, 'exclude', '不包括', 23, 'word'),
  (@u, 'expand', '扩张', 24, 'word'),
  (@u, 'factory', '工厂', 25, 'word'),
  (@u, 'failure', '失败', 26, 'word'),
  (@u, 'field', '1 地；2 领域', 27, 'word'),
  (@u, 'fly', '飞', 28, 'word'),
  (@u, 'finding', '发现', 29, 'word'),
  (@u, 'folk', '1 民间的；2 人们', 30, 'word'),
  (@u, 'forward', '向前', 31, 'word'),
  (@u, 'free', '1 自由的；2 免费的', 32, 'word'),
  (@u, 'friendly', '友好的', 33, 'word'),
  (@u, 'fundamental', '根本的', 34, 'word'),
  (@u, 'greatly', '大大地', 35, 'word'),
  (@u, 'ground', '地面', 36, 'word'),
  (@u, 'guard', 'n. 守卫者；v. 保护', 37, 'word'),
  (@u, 'heart', '心', 38, 'word'),
  (@u, 'hence', '因此', 39, 'word'),
  (@u, 'host', 'n. 主人；v. 主办', 40, 'word'),
  (@u, 'huge', '大的', 41, 'word'),
  (@u, 'independence', '独立', 42, 'word'),
  (@u, 'inquiry', '调查；询问', 43, 'word'),
  (@u, 'intelligent', '1 聪明的；2 智能的', 44, 'word'),
  (@u, 'introduction', '1 介绍；2 引入', 45, 'word'),
  (@u, 'laboratory', '实验室', 46, 'word'),
  (@u, 'main', '主要的', 47, 'word'),
  (@u, 'male/female', '男性／女性', 48, 'word'),
  (@u, 'minister', '官员', 49, 'word'),
  (@u, 'misery', '苦难；悲惨', 50, 'word'),
  (@u, 'mix', '混合', 51, 'word'),
  (@u, 'mom/mother', '妈', 52, 'word'),
  (@u, 'oblige', '强迫', 53, 'word'),
  (@u, 'not necessarily', '不一定', 54, 'word'),
  (@u, 'nervous', '1 紧张的；2 神经的', 55, 'word'),
  (@u, 'openly', '公开地', 56, 'word'),
  (@u, 'opinion', '看法', 57, 'word'),
  (@u, 'option', '选项', 58, 'word'),
  (@u, 'organization', '组织', 59, 'word'),
  (@u, 'original', '起初地', 60, 'word'),
  (@u, 'originate', '起源', 61, 'word'),
  (@u, 'owe', '欠', 62, 'word'),
  (@u, 'partly', '部分地', 63, 'word'),
  (@u, 'party', '1 党；2 派对', 64, 'word'),
  (@u, 'passionate', '热情的', 65, 'word'),
  (@u, 'peculiar', '特有的；奇怪的', 66, 'word'),
  (@u, 'people', '1 人；2 民族', 67, 'word'),
  (@u, 'perfect', 'adj. 完美；v. 使完美的', 68, 'word'),
  (@u, 'pick', '选', 69, 'word'),
  (@u, 'personality', '个性', 70, 'word'),
  (@u, 'philosophy', '哲学', 71, 'word'),
  (@u, 'precede', '发生在….前', 72, 'word'),
  (@u, 'precisely', '准确地', 73, 'word'),
  (@u, 'prepare', '准备', 74, 'word'),
  (@u, 'quick', '快', 75, 'word'),
  (@u, 'print', '打印', 76, 'word'),
  (@u, 'privilege', '1 优待；2 荣幸', 77, 'word'),
  (@u, 'procedure', '手续；流程', 78, 'word'),
  (@u, 'profession', '行业', 79, 'word'),
  (@u, 'psychological', '心理学的', 80, 'word'),
  (@u, 'professionalization', '职业化', 81, 'word'),
  (@u, 'pursue', '追求', 82, 'word'),
  (@u, 'quote', '引用', 83, 'word'),
  (@u, 'race', '1 比赛；2 种族', 84, 'word'),
  (@u, 'radically', '激进地', 85, 'word');

-- ---------- Unit 15  (102 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 15', 15);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'rail', '铁轨', 1, 'word'),
  (@u, 'railway', '铁路', 2, 'word'),
  (@u, 'random', '随机的', 3, 'word'),
  (@u, 'reaction', '反应', 4, 'word'),
  (@u, 'reasonable', '合理的', 5, 'word'),
  (@u, 'recommend', '推荐', 6, 'word'),
  (@u, 'recommendation', '推荐', 7, 'word'),
  (@u, 'reduction', '减少', 8, 'word'),
  (@u, 'reference', '参考', 9, 'word'),
  (@u, 'repeat', '重复', 10, 'word'),
  (@u, 'request', '请求', 11, 'word'),
  (@u, 'signal', '信号', 12, 'word'),
  (@u, 'simple', '简单', 13, 'word'),
  (@u, 'skeptical', '怀疑的', 14, 'word'),
  (@u, 'solution', '解决办法', 15, 'word'),
  (@u, 'southern', '南方的', 16, 'word'),
  (@u, 'strength', '力量', 17, 'word'),
  (@u, 'strike', '打击', 18, 'word'),
  (@u, 'succeed', '成功', 19, 'word'),
  (@u, 'suddenly', '突然地', 20, 'word'),
  (@u, 'sufficient', '充足的', 21, 'word'),
  (@u, 'suit', '1 适合；2 诉讼；3 正装', 22, 'word'),
  (@u, 'supportive', '支持的', 23, 'word'),
  (@u, 'systematic', '系统的', 24, 'word'),
  (@u, 'target', '1 目标；2 瞄准', 25, 'word'),
  (@u, 'team', '团队', 26, 'word'),
  (@u, 'technique', '技术', 27, 'word'),
  (@u, 'temporary', '临时的', 28, 'word'),
  (@u, 'transform', '转变', 29, 'word'),
  (@u, 'treat', '1 治疗；2 对待', 30, 'word'),
  (@u, 'uniform', '制服', 31, 'word'),
  (@u, 'upload', '上传', 32, 'word'),
  (@u, 'valuable', '宝贵的', 33, 'word'),
  (@u, 'vary', '不同', 34, 'word'),
  (@u, 'visitor', '来访者', 35, 'word'),
  (@u, 'wall', '墙', 36, 'word'),
  (@u, 'welcome', '欢迎', 37, 'word'),
  (@u, 'whatever', '无论什么', 38, 'word'),
  (@u, 'whereas', '然而', 39, 'word'),
  (@u, 'widespread', '广泛的', 40, 'word'),
  (@u, 'workman', '工匠', 41, 'word'),
  (@u, 'worm', '虫', 42, 'word'),
  (@u, 'acceptable', '可接受的', 43, 'word'),
  (@u, 'accident', '事故', 44, 'word'),
  (@u, 'across', '穿过', 45, 'word'),
  (@u, 'active', '活跃的', 46, 'word'),
  (@u, 'actor', '演员', 47, 'word'),
  (@u, 'in addition', '另外', 48, 'word'),
  (@u, 'adjust', '调整', 49, 'word'),
  (@u, 'adopt', '1 采用；2 收养', 50, 'word'),
  (@u, 'aggressive', '大胆；激进的', 51, 'word'),
  (@u, 'alcohol', '酒精', 52, 'word'),
  (@u, 'analyze', '分析', 53, 'word'),
  (@u, 'annual', '年度的', 54, 'word'),
  (@u, 'anti-intellectualism', '反智主义', 55, 'word'),
  (@u, 'anywhere', '任何地方', 56, 'word'),
  (@u, 'apple', '苹果', 57, 'word'),
  (@u, 'approve', '1 赞同；2 批准', 58, 'word'),
  (@u, 'article', '1 文章；2 物品', 59, 'word'),
  (@u, 'atmosphere', '氛围', 60, 'word'),
  (@u, 'aware', '知道；明白', 61, 'word'),
  (@u, 'balance', '平衡', 62, 'word'),
  (@u, 'barely', '几乎不', 63, 'word'),
  (@u, 'bargain', 'n. 便宜货；n. 交易；v. 讲价', 64, 'word'),
  (@u, 'basis', '1 基本原则；2 基础', 65, 'word'),
  (@u, 'biology', '生物学', 66, 'word'),
  (@u, 'blind', '瞎的', 67, 'word'),
  (@u, 'boss', 'n. 老板；v. 指手画脚', 68, 'word'),
  (@u, 'branch', '分支', 69, 'word'),
  (@u, 'brand', 'n. 品牌', 70, 'word'),
  (@u, 'busy', '忙的', 71, 'word'),
  (@u, 'cancer', '癌症', 72, 'word'),
  (@u, 'cancel', '取消', 73, 'word'),
  (@u, 'captive', '被监禁的', 74, 'word'),
  (@u, 'casual', '随意的', 75, 'word'),
  (@u, 'cater', 'v. 承办宴席', 76, 'word'),
  (@u, 'cite', '引用', 77, 'word'),
  (@u, 'citizen', '公民', 78, 'word'),
  (@u, 'classical', '经典的', 79, 'word'),
  (@u, 'classroom', '教室', 80, 'word'),
  (@u, 'clean', '干净的', 81, 'word'),
  (@u, 'closely', '紧密地', 82, 'word'),
  (@u, 'complain', '抱怨', 83, 'word'),
  (@u, 'complementary', '互补的', 84, 'word'),
  (@u, 'comply', '服从', 85, 'word'),
  (@u, 'compromise', '妥协', 86, 'word'),
  (@u, 'concentration', '集中', 87, 'word'),
  (@u, 'conclusion', '结论', 88, 'word'),
  (@u, 'constitution', '宪法', 89, 'word'),
  (@u, 'constitutional', '宪法的', 90, 'word'),
  (@u, 'contempt', '轻视', 91, 'word'),
  (@u, 'contract', 'n. 合同；v. 收缩', 92, 'word'),
  (@u, 'contrast', '对比', 93, 'word'),
  (@u, 'contribution', '贡献', 94, 'word'),
  (@u, 'convey', '传达', 95, 'word'),
  (@u, 'cooperate', '合作', 96, 'word'),
  (@u, 'count', '算术', 97, 'word'),
  (@u, 'creature', '生物', 98, 'word'),
  (@u, 'criminal', 'adj. 犯罪的；n. 罪犯', 99, 'word'),
  (@u, 'dangerous', '危险的', 100, 'word'),
  (@u, 'date', '1 日期；2 约会', 101, 'word'),
  (@u, 'default', '默认', 102, 'word');

-- ---------- Unit 16  (92 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 16', 16);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'defend', '保卫；辩护', 1, 'word'),
  (@u, 'democracy', '民主', 2, 'word'),
  (@u, 'democratic', '民主的', 3, 'word'),
  (@u, 'desirable', '理想的', 4, 'word'),
  (@u, 'destroy', '毁灭', 5, 'word'),
  (@u, 'device', '设备', 6, 'word'),
  (@u, 'director', '董事；总监；主任', 7, 'word'),
  (@u, 'disappear', '消失', 8, 'word'),
  (@u, 'discussion', '探讨', 9, 'word'),
  (@u, 'disorder', '失调；混乱', 10, 'word'),
  (@u, 'distinctly', '明显', 11, 'word'),
  (@u, 'economics', '经济学', 12, 'word'),
  (@u, 'effectively', '有效地', 13, 'word'),
  (@u, 'efficiency', '效率', 14, 'word'),
  (@u, 'elsewhere', '别处', 15, 'word'),
  (@u, 'emergence', '兴起', 16, 'word'),
  (@u, 'employee', '员工', 17, 'word'),
  (@u, 'endure', '忍受', 18, 'word'),
  (@u, 'engineer', '工程师', 19, 'word'),
  (@u, 'enlarge', '扩大', 20, 'word'),
  (@u, 'equivalent', 'adj. 对等的；n. 对等物', 21, 'word'),
  (@u, 'excess', '过多', 22, 'word'),
  (@u, 'excessive', '过多的', 23, 'word'),
  (@u, 'extent', '程度', 24, 'word'),
  (@u, 'external', '外部的', 25, 'word'),
  (@u, 'extra', '额外的', 26, 'word'),
  (@u, 'extreme', '极度的', 27, 'word'),
  (@u, 'fairly', '相当地', 28, 'word'),
  (@u, 'famous', '著名的', 29, 'word'),
  (@u, 'faith', '1 信心；2 信仰', 30, 'word'),
  (@u, 'far-reaching', '深远的', 31, 'word'),
  (@u, 'formation', '建立；形成', 32, 'word'),
  (@u, 'fortune', '1 幸运；2 财富', 33, 'word'),
  (@u, 'frustration', '沮丧', 34, 'word'),
  (@u, 'fun', '乐趣', 35, 'word'),
  (@u, 'garment', '衣服', 36, 'word'),
  (@u, 'graduate', 'v. 毕业；n. 毕业生', 37, 'word'),
  (@u, 'grammar', '语法', 38, 'word'),
  (@u, 'grape', '葡萄', 39, 'word'),
  (@u, 'guarantee', '确保', 40, 'word'),
  (@u, 'guide', '指引', 41, 'word'),
  (@u, 'handle', '应对；处理', 42, 'word'),
  (@u, 'healthy', '健康的', 43, 'word'),
  (@u, 'helmet', '头盔', 44, 'word'),
  (@u, 'hospitality', 'n. 热情款待', 45, 'word'),
  (@u, 'hotel', '酒店', 46, 'word'),
  (@u, 'illegal', '非法的', 47, 'word'),
  (@u, 'image', '1 形象；2 图像', 48, 'word'),
  (@u, 'immediately', '立刻地', 49, 'word'),
  (@u, 'impulse', '冲动', 50, 'word'),
  (@u, 'initial', '最初的', 51, 'word'),
  (@u, 'initiative', '积极性', 52, 'word'),
  (@u, 'intense', '强烈的', 53, 'word'),
  (@u, 'interaction', '互动', 54, 'word'),
  (@u, 'interpret', '理解', 55, 'word'),
  (@u, 'interview', '1 采访；2 面试', 56, 'word'),
  (@u, 'joy', '欢乐', 57, 'word'),
  (@u, 'the latter', '后者', 58, 'word'),
  (@u, 'the former', '前者', 59, 'word'),
  (@u, 'launch', '1 发射；2 发起', 60, 'word'),
  (@u, 'leadership', '领导力', 61, 'word'),
  (@u, 'leakage', '泄漏', 62, 'word'),
  (@u, 'legislation', '立法', 63, 'word'),
  (@u, 'liberal', '自由；开明的', 64, 'word'),
  (@u, 'migration', '移居', 65, 'word'),
  (@u, 'military', '军事的', 66, 'word'),
  (@u, 'nevertheless', '然而', 67, 'word'),
  (@u, 'nor', '也不', 68, 'word'),
  (@u, 'normal', '正常的', 69, 'word'),
  (@u, 'north', '北', 70, 'word'),
  (@u, 'notice', 'v. 注意到；n. 通知', 71, 'word'),
  (@u, 'objection', '反对', 72, 'word'),
  (@u, 'observation', '观察', 73, 'word'),
  (@u, 'obviously', '明显地', 74, 'word'),
  (@u, 'ourselves', '我们自己', 75, 'word'),
  (@u, 'outcome', '结果', 76, 'word'),
  (@u, 'outlook', '世界观；人生观', 77, 'word'),
  (@u, 'pace', '步伐；节奏', 78, 'word'),
  (@u, 'painful', '痛苦的', 79, 'word'),
  (@u, 'paycheck', '薪水', 80, 'word'),
  (@u, 'percentage', '百分比', 81, 'word'),
  (@u, 'permission', '许可', 82, 'word'),
  (@u, 'physics', '物理学', 83, 'word'),
  (@u, 'piece', '一块/片/点/段', 84, 'word'),
  (@u, 'poet', '诗人', 85, 'word'),
  (@u, 'pose', '1 造成；2 姿势', 86, 'word'),
  (@u, 'pour', '倾倒', 87, 'word'),
  (@u, 'pride', '骄傲', 88, 'word'),
  (@u, 'priority', '优先', 89, 'word'),
  (@u, 'prolong', '延长', 90, 'word'),
  (@u, 'proper', '恰当的', 91, 'word'),
  (@u, 'puritan', '清教徒', 92, 'word');

-- ---------- Unit 17  (98 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 17', 17);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'radio', '1 无线电；2 收音机', 1, 'word'),
  (@u, 'rage', '狂怒', 2, 'word'),
  (@u, 'rap', '说唱', 3, 'word'),
  (@u, 'rapidly', '迅速地', 4, 'word'),
  (@u, 'rarely', '少见地', 5, 'word'),
  (@u, 'recovery', '恢复', 6, 'word'),
  (@u, 'recruit', '招收', 7, 'word'),
  (@u, 'refuse', '拒绝', 8, 'word'),
  (@u, 'relatively', '相对来说', 9, 'word'),
  (@u, 'release', '1 发布；2 释放', 10, 'word'),
  (@u, 'reliable', '可靠的', 11, 'word'),
  (@u, 'reply', '回应', 12, 'word'),
  (@u, 'reporter', '记者', 13, 'word'),
  (@u, 'resistant', '抗拒的', 14, 'word'),
  (@u, 'routine', '惯例；常规', 15, 'word'),
  (@u, 'save', '1 节约；2 拯救；3 免去', 16, 'word'),
  (@u, 'scope', '范围', 17, 'word'),
  (@u, 'sea', '海', 18, 'word'),
  (@u, 'segment', '部分', 19, 'word'),
  (@u, 'seriously', '1 严肃；认真；2 当回事', 20, 'word'),
  (@u, 'settle', '1 和解；解决；2 定居', 21, 'word'),
  (@u, 'sex', '1 性；2 性别', 22, 'word'),
  (@u, 'shut', '关闭', 23, 'word'),
  (@u, 'sight', '1 视力；视野；2 风景', 24, 'word'),
  (@u, 'six', '六', 25, 'word'),
  (@u, 'somewhat', '有一点', 26, 'word'),
  (@u, 'specialization', '专门化', 27, 'word'),
  (@u, 'staff', '员工', 28, 'word'),
  (@u, 'specialize', '专门从事', 29, 'word'),
  (@u, 'speculate', '推测', 30, 'word'),
  (@u, 'spell', '1 拼写；2 一段时间', 31, 'word'),
  (@u, 'stem', '阻止', 32, 'word'),
  (@u, 'strengthen', '加强', 33, 'word'),
  (@u, 'strongly', '强烈地', 34, 'word'),
  (@u, 'substantial', '1 大量的；2 坚实的', 35, 'word'),
  (@u, 'supporter', '支持者', 36, 'word'),
  (@u, 'surgery', '外科手术', 37, 'word'),
  (@u, 'surname', '姓', 38, 'word'),
  (@u, 'surplus', '过剩的', 39, 'word'),
  (@u, 'survey', '调查', 40, 'word'),
  (@u, 'switch', '1 转换；2 开关', 41, 'word'),
  (@u, 'sympathy', '同情', 42, 'word'),
  (@u, 'traffic', '交通', 43, 'word'),
  (@u, 'terminally', '终结地', 44, 'word'),
  (@u, 'throughout', '贯穿；遍布；从始至终', 45, 'word'),
  (@u, 'tip', '1 建议；2 小费；3 尖端', 46, 'word'),
  (@u, 'trait', '特征', 47, 'word'),
  (@u, 'triumph', '胜利；成功', 48, 'word'),
  (@u, 'unconscious', '1 昏迷的；2 无意识的', 49, 'word'),
  (@u, 'underlie', '引起', 50, 'word'),
  (@u, 'unemployment', '失业', 51, 'word'),
  (@u, 'unusual', '不寻常的', 52, 'word'),
  (@u, 'valid', '有效的', 53, 'word'),
  (@u, 'victim', '受害者', 54, 'word'),
  (@u, 'virtual', '1 几乎；2 虚拟的', 55, 'word'),
  (@u, 'vitamin', '维生素', 56, 'word'),
  (@u, 'water', '水', 57, 'word'),
  (@u, 'weaken', '减弱', 58, 'word'),
  (@u, 'western', '西方的', 59, 'word'),
  (@u, 'whom', '谁', 60, 'word'),
  (@u, 'abroad', '国外', 61, 'word'),
  (@u, 'academy', '学院', 62, 'word'),
  (@u, 'accessible', '易进入；易使用', 63, 'word'),
  (@u, 'achiever', '成就的人', 64, 'word'),
  (@u, 'acknowledge', '1 承认；2 感谢', 65, 'word'),
  (@u, 'acquisition', '收购；获得', 66, 'word'),
  (@u, 'actual', '实际的', 67, 'word'),
  (@u, 'adequate', '足够的', 68, 'word'),
  (@u, 'affair', '事务；事件', 69, 'word'),
  (@u, 'aggravate', '恶化', 70, 'word'),
  (@u, 'ahead', '在前面', 71, 'word'),
  (@u, 'alike', '相同的', 72, 'word'),
  (@u, 'alive', '1 活的；2 活跃的', 73, 'word'),
  (@u, 'alternative', '另一个选择', 74, 'word'),
  (@u, 'annoy', '惹恼', 75, 'word'),
  (@u, 'anxiety', '焦虑', 76, 'word'),
  (@u, 'anyway', '反正', 77, 'word'),
  (@u, 'apart', '分开', 78, 'word'),
  (@u, 'applicant', '申请人', 79, 'word'),
  (@u, 'appointment', '1 任命；2 预约', 80, 'word'),
  (@u, 'appreciate', '1 欣赏；2 感激；3 了解', 81, 'word'),
  (@u, 'appreciation', '欣赏；感激', 82, 'word'),
  (@u, 'approval', '1 同意；2 批准', 83, 'word'),
  (@u, 'arm', '手臂', 84, 'word'),
  (@u, 'arouse', '激起', 85, 'word'),
  (@u, 'assemble', '1 集合；2 组装', 86, 'word'),
  (@u, 'associate', '联系', 87, 'word'),
  (@u, 'assumption', '假设', 88, 'word'),
  (@u, 'athlete', '运动员', 89, 'word'),
  (@u, 'attach', '粘上；附上', 90, 'word'),
  (@u, 'attribute', '归因', 91, 'word'),
  (@u, 'award', '奖', 92, 'word'),
  (@u, 'awareness', '知道', 93, 'word'),
  (@u, 'banker', '银行家', 94, 'word'),
  (@u, 'baseline', '基础', 95, 'word'),
  (@u, 'belong', '属于', 96, 'word'),
  (@u, 'belt', '带', 97, 'word'),
  (@u, 'bid', '竞价', 98, 'word');

-- ---------- Unit 18  (86 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18章答案 Unit 18', 18);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'bind', '捆绑', 1, 'word'),
  (@u, 'biologist', '生物学家', 2, 'word'),
  (@u, 'black', '黑', 3, 'word'),
  (@u, 'boy', '男孩儿', 4, 'word'),
  (@u, 'breakthrough', '突破', 5, 'word'),
  (@u, 'capability', '能力', 6, 'word'),
  (@u, 'bright', '1 光明的；2 聪明的', 7, 'word'),
  (@u, 'capture', '捕获', 8, 'word'),
  (@u, 'certainly', '肯定地', 9, 'word'),
  (@u, 'chair', '1 主席；2 椅子', 10, 'word'),
  (@u, 'club', '俱乐部', 11, 'word'),
  (@u, 'childless', '无子女的', 12, 'word'),
  (@u, 'civil', '1 国内的；2 文明的', 13, 'word'),
  (@u, 'cognitive', '认知的', 14, 'word'),
  (@u, 'colony', '殖民地', 15, 'word'),
  (@u, 'command', '命令；指挥', 16, 'word'),
  (@u, 'commitment', '承诺', 17, 'word'),
  (@u, 'committee', '委员会', 18, 'word'),
  (@u, 'commonly', '通常地', 19, 'word'),
  (@u, 'communicate', '沟通；交流', 20, 'word'),
  (@u, 'confidence', '信心', 21, 'word'),
  (@u, 'compensate', '补偿', 22, 'word'),
  (@u, 'competitor', '竞争者', 23, 'word'),
  (@u, 'component', '部分', 24, 'word'),
  (@u, 'confront', '直面；正视', 25, 'word'),
  (@u, 'consequently', '所以', 26, 'word'),
  (@u, 'considerable', '相当的', 27, 'word'),
  (@u, 'consideration', '考虑', 28, 'word'),
  (@u, 'constitute', '组成', 29, 'word'),
  (@u, 'consume', '消费；消耗', 30, 'word'),
  (@u, 'contact', '接触；联系', 31, 'word'),
  (@u, 'context', '1 上下文；2 环境', 32, 'word'),
  (@u, 'controversial', '争议的', 33, 'word'),
  (@u, 'cool', '1 凉的；2 好的；3 酷的', 34, 'word'),
  (@u, 'crack', '破裂；破解', 35, 'word'),
  (@u, 'coverage', '覆盖范围', 36, 'word'),
  (@u, 'crop', '庄稼', 37, 'word'),
  (@u, 'cucumber', '黄瓜', 38, 'word'),
  (@u, 'custom', '习俗', 39, 'word'),
  (@u, 'damage', '损坏', 40, 'word'),
  (@u, 'dead', '死的', 41, 'word'),
  (@u, 'delay', '延误', 42, 'word'),
  (@u, 'deliberately', '故意地', 43, 'word'),
  (@u, 'deliver', '1 递送；2 讲话', 44, 'word'),
  (@u, 'dependence', '依赖', 45, 'word'),
  (@u, 'deprive', '剥夺', 46, 'word'),
  (@u, 'detach', '脱离；分开', 47, 'word'),
  (@u, 'detect', '探测', 48, 'word'),
  (@u, 'diet', '饮食；节食', 49, 'word'),
  (@u, 'disadvantage', '不利', 50, 'word'),
  (@u, 'disappoint', '失望', 51, 'word'),
  (@u, 'disaster', '灾难', 52, 'word'),
  (@u, 'dismiss', '1 解除；解雇；解散；2 不考虑', 53, 'word'),
  (@u, 'disorganize', '混乱', 54, 'word'),
  (@u, 'dissatisfaction', '不满足', 55, 'word'),
  (@u, 'diverse', '多样的', 56, 'word'),
  (@u, 'doctor', '1 医生；2 博士', 57, 'word'),
  (@u, 'dominate', '统治；主宰', 58, 'word'),
  (@u, 'dose', '剂量', 59, 'word'),
  (@u, 'dramatic', '戏剧性的', 60, 'word'),
  (@u, 'e-commerce', '电子商务', 61, 'word'),
  (@u, 'elementary', '基础的；初级的', 62, 'word'),
  (@u, 'eliminate', '终止；消除', 63, 'word'),
  (@u, 'endeavor', '努力', 64, 'word'),
  (@u, 'enlighten', '启发', 65, 'word'),
  (@u, 'entertain', '娱乐', 66, 'word'),
  (@u, 'entire', '整个的', 67, 'word'),
  (@u, 'environmental', '环境的', 68, 'word'),
  (@u, 'environmentalist', '环保人士', 69, 'word'),
  (@u, 'everywhere', '到处', 70, 'word'),
  (@u, 'exaggerate', '夸张', 71, 'word'),
  (@u, 'expectation', '期待', 72, 'word'),
  (@u, 'explosion', '爆炸', 73, 'word'),
  (@u, 'extension', '延伸', 74, 'word'),
  (@u, 'factual', '事实的', 75, 'word'),
  (@u, 'fame', '名', 76, 'word'),
  (@u, 'familiar', '熟悉的', 77, 'word'),
  (@u, 'fascinate', '使着迷', 78, 'word'),
  (@u, 'fee', '费用', 79, 'word'),
  (@u, 'fiction', '小说', 80, 'word'),
  (@u, 'fierce', '激烈的', 81, 'word'),
  (@u, 'final', '最后的', 82, 'word'),
  (@u, 'flaw', '缺陷', 83, 'word'),
  (@u, 'flood', '洪水', 84, 'word'),
  (@u, 'foresee', '预见', 85, 'word'),
  (@u, 'found', '1 建立；2 找到；3 发现', 86, 'word');

COMMIT;
