-- ============================================================
-- 18中频词汇答案 Unit 词汇表初始化数据
-- 来源: 18中频词汇答案.md  (Unit 19–29 / 共 11 个 Unit / 976 词)
-- 适配表: unit / word  (word.seq 见迁移 006_word_seq；word.unit_id ON DELETE CASCADE)
-- 字符集: utf8mb4
-- 幂等: 开头按 title 删除同名 unit；word 随外键级联删除，可安全重跑
-- 编号: unit.sequence 接续 seed_18_units.sql (1–18)，本文件用 19–29
-- 说明: U19 的 NO30–32、U29 的 NO20–96 在原 PDF 中为空白，故 word.seq 不连续
-- ============================================================

SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM unit WHERE title LIKE '18中频词汇 Unit%';

-- ---------- Unit 19  (93 词；NO30–32 原PDF留空) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 19', 19);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'counterbalance', 'vt.抗衡n.抗衡（力）', 1, 'word'),
  (@u, 'criterion', 'n.标准；准则', 2, 'word'),
  (@u, 'critique', 'n.评论文章，批评；vt. 发表评论', 3, 'word'),
  (@u, 'crown', 'n.王冠；vt. 为…加冕，使圆满', 4, 'word'),
  (@u, 'cruelty', 'n.残忍，残忍的行为', 5, 'word'),
  (@u, 'cultivate', 'vt.耕作，种植，栽培', 6, 'word'),
  (@u, 'cultivation', 'n.教养，栽培', 7, 'word'),
  (@u, 'cunning', 'a. 狡猾的n. 狡猾', 8, 'word'),
  (@u, 'cup', 'n.杯子vt. 使（手）窝成环状', 9, 'word'),
  (@u, 'curb', 'vt. 制止，束缚n. 限制，（证券的）场外市场', 10, 'word'),
  (@u, 'curiosity', 'n. 好奇心', 11, 'word'),
  (@u, 'curious', 'a. 好奇的', 12, 'word'),
  (@u, 'currently', 'ad.当前；目前', 13, 'word'),
  (@u, 'cute', 'a. 漂亮的，娇小可爱的', 14, 'word'),
  (@u, 'dare', 'vt. 敢做vi.敢aux. 竟敢n. 挑战', 15, 'word'),
  (@u, 'dazzlingly', 'ad. 灿烂地；炫耀地', 16, 'word'),
  (@u, 'deadline', 'n. 最后期限', 17, 'word'),
  (@u, 'December', 'n. 12月', 18, 'word'),
  (@u, 'deceptive', 'a.欺诈的，骗人的', 19, 'word'),
  (@u, 'decisive', 'a. 决定性的；果决的', 20, 'word'),
  (@u, 'declaration', 'n. 宣言；声明；（原告的）申诉', 21, 'word'),
  (@u, 'deduce', 'vt. 推论；推断', 22, 'word'),
  (@u, 'deem', 'vt. 认为；视为', 23, 'word'),
  (@u, 'defeat', 'vt. 击败；n. 战胜', 24, 'word'),
  (@u, 'defective', 'a. 有缺陷的n. 身心缺陷的人', 25, 'word'),
  (@u, 'defendant', 'n. 被告人a. 辩护的', 26, 'word'),
  (@u, 'definite', 'a. 明确的；一定的', 27, 'word'),
  (@u, 'delight', 'n. 快乐vt. 使高兴', 28, 'word'),
  (@u, 'delinquency', 'n. 不法行为；过失', 29, 'word'),
  (@u, 'demographer', 'n. 人口统计学家', 33, 'word'),
  (@u, 'demographic', 'a. 人口统计学的', 34, 'word'),
  (@u, 'descendant', 'n. 后代', 35, 'word'),
  (@u, 'designer', 'n. 设计师', 36, 'word'),
  (@u, 'despair', 'n.绝望v. 失去希望', 37, 'word'),
  (@u, 'destruction', 'n. 破灭；毁灭', 38, 'word'),
  (@u, 'determinism', 'n. 决定论；宿命论', 39, 'word'),
  (@u, 'dictate', 'vt/vi. 口述n. 命令', 40, 'word'),
  (@u, 'diffuse', 'a. 散开的；冗长的vi. 传播vt.发散', 41, 'word'),
  (@u, 'diffusionism', 'n. 弥漫说；传播论', 42, 'word'),
  (@u, 'dim', 'a. 暗淡的vt/vi （使）变暗淡', 43, 'word'),
  (@u, 'dimension', 'n. 度；维', 44, 'word'),
  (@u, 'diminish', 'vt. (使)减少vi. 变小或减少', 45, 'word'),
  (@u, 'dirt-cheap', '很廉价', 46, 'word'),
  (@u, 'disagree', 'vi 不同意', 47, 'word'),
  (@u, 'disapproval', 'n. 不赞同；反对', 48, 'word'),
  (@u, 'discomfort', 'n. 不舒适vt. 使…不舒服', 49, 'word'),
  (@u, 'discontent', 'n. 不满a. 不满的v. 使不满意', 50, 'word'),
  (@u, 'discourage', 'v. 使泄气', 51, 'word'),
  (@u, 'disgrace', 'n. 丢脸；耻辱vt. 使丢脸', 52, 'word'),
  (@u, 'disguise', 'vt. 隐瞒n. 伪装', 53, 'word'),
  (@u, 'dishonor', 'n. 侮辱vt. 拒付；侮辱', 54, 'word'),
  (@u, 'disposable', 'a. 一次性的；可处理的', 55, 'word'),
  (@u, 'disposition', 'n. 性格；安排；配置', 56, 'word'),
  (@u, 'disputable', 'a. 可争辩的', 57, 'word'),
  (@u, 'disregard', 'vt. 不顾n. 漠视', 58, 'word'),
  (@u, 'distance', 'n. 距离', 59, 'word'),
  (@u, 'distaste', 'n. 厌恶vt. 厌恶', 60, 'word'),
  (@u, 'distortion', 'n. 扭曲；变形', 61, 'word'),
  (@u, 'distract', 'vt. 使分心', 62, 'word'),
  (@u, 'distribute', 'vt. 分配；散布', 63, 'word'),
  (@u, 'divorce', 'n. 离婚vt. 与….离婚', 64, 'word'),
  (@u, 'doctrine', 'n. 教条', 65, 'word'),
  (@u, 'dome', 'n. 圆屋顶；圆顶体育场', 66, 'word'),
  (@u, 'doom', 'n. 厄运vt. 注定；使…失败', 67, 'word'),
  (@u, 'doormat', 'n. 垫子', 68, 'word'),
  (@u, 'double', 'a. 双的vt. 使加倍vi. 加倍', 69, 'word'),
  (@u, 'double-digit', 'a. 两位数的', 70, 'word'),
  (@u, 'doubtful', 'a. 怀疑的；难以预测的', 71, 'word'),
  (@u, 'downsize', 'v. 缩小规模', 72, 'word'),
  (@u, 'dreadful', 'a. 可怕的；令人畏惧的', 73, 'word'),
  (@u, 'driver', 'n. 驾驶员；', 74, 'word'),
  (@u, 'duplication', 'n. 复制；重复', 75, 'word'),
  (@u, 'dust', 'n. 灰尘；花粉vt&vi 拂去', 76, 'word'),
  (@u, 'eagerness', 'n. 渴望；热心', 77, 'word'),
  (@u, 'earner', 'n. 挣钱人', 78, 'word'),
  (@u, 'east', 'n. 东方a. 东方的adv. 向东方的', 79, 'word'),
  (@u, 'educator', 'n. 教员', 80, 'word'),
  (@u, 'effectiveness', 'n. 有效；有力', 81, 'word'),
  (@u, 'efficient', 'a. 高效的', 82, 'word'),
  (@u, 'egalitarian', 'a. 主张平等的n. 平等主义', 83, 'word'),
  (@u, 'elder', 'n. 长辈a. 年纪较大的', 84, 'word'),
  (@u, 'election', 'n. 选举；当选', 85, 'word'),
  (@u, 'electricity', 'n. 电力；电流', 86, 'word'),
  (@u, 'elevate', 'vt. 举起；提高', 87, 'word'),
  (@u, 'encode', 'vt. （将文字材料）译成密码', 88, 'word'),
  (@u, 'encompass', 'vt. 围绕；包围；包含（2007年考过）', 89, 'word'),
  (@u, 'endanger', 'vt. 危及；使遭受危险', 90, 'word'),
  (@u, 'endless', 'a. 无尽的', 91, 'word'),
  (@u, 'end-of-life', '临终', 92, 'word'),
  (@u, 'energetic', 'a. 精力充沛的；充满活力的', 93, 'word'),
  (@u, 'enforce', 'vt. 事实；执行', 94, 'word'),
  (@u, 'engine', 'n. 发动机', 95, 'word'),
  (@u, 'enthusiastically', 'ad. 热情地', 96, 'word');

-- ---------- Unit 20  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 20', 20);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'entrench', 'v. 牢固地确立n. 壕沟', 1, 'word'),
  (@u, 'entrepreneur', 'n. 企业家', 2, 'word'),
  (@u, 'episode', 'n. 插曲；片段', 3, 'word'),
  (@u, 'establishment', 'n. 创业；建立', 4, 'word'),
  (@u, 'evaluate', 'vt. 评价', 5, 'word'),
  (@u, 'evident', 'a. 明显的', 6, 'word'),
  (@u, 'evil', 'a. 邪恶的n. 邪恶', 7, 'word'),
  (@u, 'exaggeration', 'n. 夸张', 8, 'word'),
  (@u, 'exam', 'n. 考试；测验', 9, 'word'),
  (@u, 'exceed', 'v. 超过；超出', 10, 'word'),
  (@u, 'excellence', 'n. 优点；卓越', 11, 'word'),
  (@u, 'exclusive', 'a. 不包括；除…以外', 12, 'word'),
  (@u, 'exclusively', 'ad. 唯一地；专门地', 13, 'word'),
  (@u, 'exhaust', 'vt. 用尽；使精疲力尽vi. 排气n. 排除的尾气', 14, 'word'),
  (@u, 'exhibition', 'n. 陈列；展览', 15, 'word'),
  (@u, 'exit', 'n. 出口vi. 离开', 16, 'word'),
  (@u, 'expense', 'n.费用vt. 向…收取费用', 17, 'word'),
  (@u, 'explanatory', 'a. 解释的；说明的', 18, 'word'),
  (@u, 'explicit', 'a. 明确的；清晰的', 19, 'word'),
  (@u, 'exploit', 'vt. 开采n. 功绩', 20, 'word'),
  (@u, 'export', 'vt/vi 出口，输出vt. 传播', 21, 'word'),
  (@u, 'exposure', 'n. 暴露；揭发', 22, 'word'),
  (@u, 'extinction', 'n. 熄灭；消灭', 23, 'word'),
  (@u, 'extract', 'vt.提取；选取n. 汁', 24, 'word'),
  (@u, 'eyebrow', 'n. 眉毛', 25, 'word'),
  (@u, 'fallacy', 'n. 谬误；谬见', 26, 'word'),
  (@u, 'fallout', 'n. （尤指不好的事）的后果', 27, 'word'),
  (@u, 'false', 'a. 虚伪的ad. 欺诈地', 28, 'word'),
  (@u, 'fan', 'n. 粉丝vt. 煽动', 29, 'word'),
  (@u, 'fancy', 'vt. 想象；认为n. 想象的事物a. 精致的', 30, 'word'),
  (@u, 'farm', 'n. 农场vt. 耕种', 31, 'word'),
  (@u, 'fascination', 'n. 魅力；迷恋', 32, 'word'),
  (@u, 'ashionable', 'a. 流行的；时髦的', 33, 'word'),
  (@u, 'fat', 'a. 胖的n. 脂肪', 34, 'word'),
  (@u, 'fatal', 'a. 致命的，严重的', 35, 'word'),
  (@u, 'fault', 'n. 缺点vt. 挑剔', 36, 'word'),
  (@u, 'favorable', 'a. 赞同的', 37, 'word'),
  (@u, 'fearful', 'a. 害怕的；担心的', 38, 'word'),
  (@u, 'feeble', 'a. 虚弱的；衰弱的', 39, 'word'),
  (@u, 'fertilizer', 'n. 肥料；化肥', 40, 'word'),
  (@u, 'fetch', 'v. 得到', 41, 'word'),
  (@u, 'feverish', 'a. 发烧的', 42, 'word'),
  (@u, 'file', 'vt. 提出…；把…归档vi. 提出申请n. 文件', 43, 'word'),
  (@u, 'finance', 'n. 财政v. 为…提供资金', 44, 'word'),
  (@u, 'financially', 'ad. 财政上地', 45, 'word'),
  (@u, 'fine', 'a. 好的，上等的n. 罚款vt. 罚款', 46, 'word'),
  (@u, 'finish', 'v. 完成', 47, 'word'),
  (@u, 'finite', 'a. 有限的n. 有限性', 48, 'word'),
  (@u, 'fissure', 'n. 分歧分裂；vt/vi 裂开', 49, 'word'),
  (@u, 'fix', 'vt. 固定；修理n. 困境', 50, 'word'),
  (@u, 'flight', 'n. 航班', 51, 'word'),
  (@u, 'float', 'vt. （使）浮动vi. 游荡', 52, 'word'),
  (@u, 'fluctuate', 'v. 波动', 53, 'word'),
  (@u, 'fond', 'a. 喜欢的；多情的', 54, 'word'),
  (@u, 'foot', 'n. 脚', 55, 'word'),
  (@u, 'foremost', 'a. 第一流的ad. 首先', 56, 'word'),
  (@u, 'forever', 'ad. 永远n. 永恒', 57, 'word'),
  (@u, 'format', 'n. （出版物的）版式vt. 使格式化', 58, 'word'),
  (@u, 'formerly', 'ad. 原来', 59, 'word'),
  (@u, 'formulation', 'n. 配方；构想', 60, 'word'),
  (@u, 'foundation', 'n. 基础', 61, 'word'),
  (@u, 'founder', 'n. 创始人vi. 失败vt. 破坏', 62, 'word'),
  (@u, 'fraction', 'n. 一小部分', 63, 'word'),
  (@u, 'frame', 'n. 框架vt. 陷害', 64, 'word'),
  (@u, 'framework', 'n. 构架；框架', 65, 'word'),
  (@u, 'frankly', 'ad. 坦白地', 66, 'word'),
  (@u, 'fresh', 'a. 新鲜的n. 开始', 67, 'word'),
  (@u, 'frighten', 'vt. 使惊恐vi. 惊恐', 68, 'word'),
  (@u, 'frontier', 'n. 边疆a. 边疆的', 69, 'word'),
  (@u, 'frown', 'vt/ vi 皱眉n. 皱眉', 70, 'word'),
  (@u, 'fruitless', 'a. 无果的', 71, 'word'),
  (@u, 'frustrate', 'v. 使沮丧', 72, 'word'),
  (@u, 'full-time', 'a. 全日制的', 73, 'word'),
  (@u, 'functional', 'a. 功能的', 74, 'word'),
  (@u, 'fundamentally', 'ad. 基础地', 75, 'word'),
  (@u, 'funny', 'a. 有趣的n. 滑稽人物', 76, 'word'),
  (@u, 'futurologist', 'n. 未来学家', 77, 'word'),
  (@u, 'galaxy', 'n. 星系；银河系', 78, 'word'),
  (@u, 'gas', 'n. 气体', 79, 'word'),
  (@u, 'gate', 'n. 闸门vt. 给…装大门', 80, 'word'),
  (@u, 'generative', 'a. 能生产的', 81, 'word'),
  (@u, 'generous', 'a. 慷慨的', 82, 'word'),
  (@u, 'geologist', 'n. 地质学家', 83, 'word'),
  (@u, 'geophysical', 'a. 地质学的', 84, 'word'),
  (@u, 'gigantic', 'a. 巨大的；庞大的', 85, 'word'),
  (@u, 'gizmo', 'n. 小发明', 86, 'word'),
  (@u, 'glance', 'vi. 一瞥n. 浏览', 87, 'word'),
  (@u, 'globalization', 'n. 全球化', 88, 'word'),
  (@u, 'globally', 'ad. 全球地', 89, 'word'),
  (@u, 'golden', 'a. 金黄色的；美好的', 90, 'word'),
  (@u, 'government-funded', '政府资助的', 91, 'word'),
  (@u, 'governor', 'n. 统治者', 92, 'word'),
  (@u, 'gradual', 'a. 逐渐的', 93, 'word'),
  (@u, 'gradually', 'ad.逐步地', 94, 'word'),
  (@u, 'grammatical', 'a.语法上的', 95, 'word'),
  (@u, 'graph', 'n. 图表', 96, 'word');

-- ---------- Unit 21  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 21', 21);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'gratification', 'n. 满意', 1, 'word'),
  (@u, 'gravity', 'n. 重力', 2, 'word'),
  (@u, 'green', 'a. 绿色的', 3, 'word'),
  (@u, 'grocery', 'n. 杂货铺', 4, 'word'),
  (@u, 'guardian', 'n. 监护人；保护者', 5, 'word'),
  (@u, 'guidance', 'n. 指导', 6, 'word'),
  (@u, 'hall', 'n. 过道；大厅', 7, 'word'),
  (@u, 'happily', 'ad. 开心地', 8, 'word'),
  (@u, 'hard-line', 'a. 毫不妥协的', 9, 'word'),
  (@u, 'hardship', 'n. 艰难；困苦', 10, 'word'),
  (@u, 'harm', 'n. 损害vt. 伤害', 11, 'word'),
  (@u, 'haste', 'n. 匆忙v. 赶紧', 12, 'word'),
  (@u, 'hasten', 'vt/vi 加速vi 赶快', 13, 'word'),
  (@u, 'haunt', 'vt. 时常萦绕心头', 14, 'word'),
  (@u, 'haze', 'n. 烟雾；vt. 戏弄', 15, 'word'),
  (@u, 'headhunter', 'n. 猎头', 16, 'word'),
  (@u, 'heaven', 'n. 天堂', 17, 'word'),
  (@u, 'heavily', 'ad. 沉重地', 18, 'word'),
  (@u, 'hero', 'n. 英雄；勇士', 19, 'word'),
  (@u, 'hesitate', 'v, 犹豫', 20, 'word'),
  (@u, 'high-quality', '高品质', 21, 'word'),
  (@u, 'hip', 'n.臀部', 22, 'word'),
  (@u, 'historically', 'ad. 从历史角度', 23, 'word'),
  (@u, 'hit', 'vt/vi 打；打击', 24, 'word'),
  (@u, 'hitherto', 'ad.到目前为之', 25, 'word'),
  (@u, 'holder', 'n. 持有者', 26, 'word'),
  (@u, 'homogenize', 'vt. 使同类；同化', 27, 'word'),
  (@u, 'honest', 'a. 诚实的', 28, 'word'),
  (@u, 'hook', 'n. 钩vt/vi 用钩挂', 29, 'word'),
  (@u, 'horrify', 'vt.使震惊', 30, 'word'),
  (@u, 'hostile', 'a. 敌人的n. 敌对者', 31, 'word'),
  (@u, 'hostility', 'n. 敌意', 32, 'word'),
  (@u, 'humankind', 'n. 人类', 33, 'word'),
  (@u, 'humble', 'a. 谦逊的vt. 使谦恭', 34, 'word'),
  (@u, 'humorous', 'a. 幽默的', 35, 'word'),
  (@u, 'hunger', 'n. 饥饿', 36, 'word'),
  (@u, 'hungry', 'a. 饥饿的', 37, 'word'),
  (@u, 'hypothesis', 'n. 假设；假说', 38, 'word'),
  (@u, 'identifiable', 'a. 可辨认的；可视为相同的', 39, 'word'),
  (@u, 'identity', 'n. 身份', 40, 'word'),
  (@u, 'ideology', 'n. 思想（体系）；意识形态', 41, 'word'),
  (@u, 'illegally', 'ad. 非法地', 42, 'word'),
  (@u, 'illusion', 'n. 错觉；幻想', 43, 'word'),
  (@u, 'imaginative', 'a. 有想象力的', 44, 'word'),
  (@u, 'imitation', 'n. 模仿', 45, 'word'),
  (@u, 'implement', 'v. 执行；实施', 46, 'word'),
  (@u, 'import', 'v. 进口', 47, 'word'),
  (@u, 'impress', 'vt. 给…以深刻印象n. 印象', 48, 'word'),
  (@u, 'impressive', 'a. 让人印象深刻的', 49, 'word'),
  (@u, 'inability', 'n. 无能', 50, 'word'),
  (@u, 'inadequacy', 'n. 不充足', 51, 'word'),
  (@u, 'inappropriate', 'a. 不合适的', 52, 'word'),
  (@u, 'incentive', 'n. 刺激因素', 53, 'word'),
  (@u, 'incidence', 'n. 发生率', 54, 'word'),
  (@u, 'incident', 'n. 事件', 55, 'word'),
  (@u, 'incline', 'vt/ vi 倾斜n. 斜坡', 56, 'word'),
  (@u, 'incompetently', 'ad. 无能力地', 57, 'word'),
  (@u, 'indefinitely', 'ad. 无期限地', 58, 'word'),
  (@u, 'indicative', 'a. 象征的；指示的', 59, 'word'),
  (@u, 'indictment', 'n. 诉状；起诉书', 60, 'word'),
  (@u, 'indifferent', 'a. 冷漠的', 61, 'word'),
  (@u, 'indignation', 'n. 愤怒；愤慨', 62, 'word'),
  (@u, 'indirectly', 'ad. 间接地', 63, 'word'),
  (@u, 'indispensable', 'a. 不可却少的', 64, 'word'),
  (@u, 'ineffective', 'a. 无效果的', 65, 'word'),
  (@u, 'inefficient', 'a. 无效率的', 66, 'word'),
  (@u, 'Inequality', 'n. 不平等', 67, 'word'),
  (@u, 'infancy', 'n. 婴儿期；初期', 68, 'word'),
  (@u, 'infant', 'n. 婴儿a. 婴儿的', 69, 'word'),
  (@u, 'infection', 'n. 感染', 70, 'word'),
  (@u, 'inflate', 'vt/ vi （使）充气', 71, 'word'),
  (@u, 'ingenuity', 'n. 足智多谋；心灵手巧', 72, 'word'),
  (@u, 'initiate', 'vi.发起，开始n. 新加入某组织的人', 73, 'word'),
  (@u, 'inject', 'vt. （给…）注射（药物等）', 74, 'word'),
  (@u, 'innate', 'a. 天生的', 75, 'word'),
  (@u, 'insecurity', 'n. 不安全', 76, 'word'),
  (@u, 'insensitivity', 'n. 不灵敏', 77, 'word'),
  (@u, 'inside', 'a. 里面的n. 里面', 78, 'word'),
  (@u, 'inspection', 'n. 检查', 79, 'word'),
  (@u, 'instantly', 'ad. 立刻', 80, 'word'),
  (@u, 'intensify', 'v. （使）增强', 81, 'word'),
  (@u, 'intention', 'n. 目的', 82, 'word'),
  (@u, 'interactivity', 'n. 相互作用', 83, 'word'),
  (@u, 'interfere', 'vi.干预；干涉', 84, 'word'),
  (@u, 'intermarriage', 'n. 异族结婚', 85, 'word'),
  (@u, 'interprovincial', 'a. 各省之间的', 86, 'word'),
  (@u, 'intimate', 'a. 亲密的n. 至交', 87, 'word'),
  (@u, 'intricacy', 'n. 错综复杂', 88, 'word'),
  (@u, 'intrinsic', 'a. 固有的；内在的', 89, 'word'),
  (@u, 'invent', 'vt. 发明；创造', 90, 'word'),
  (@u, 'inventiveness', 'n. 创造性', 91, 'word'),
  (@u, 'invisible', 'a. 看不见的', 92, 'word'),
  (@u, 'irrigation', 'n. 灌溉', 93, 'word'),
  (@u, 'isolate', 'vt. 使孤立vi. 隔离a. 隔离的', 94, 'word'),
  (@u, 'jobless', 'a. 没工作的n. 失业者', 95, 'word'),
  (@u, 'joint', 'a. 共同的', 96, 'word');

-- ---------- Unit 22  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 22', 22);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'June', 'n. 六月', 1, 'word'),
  (@u, 'justification', 'n.辩解', 2, 'word'),
  (@u, 'kilogram', 'n. 千克', 3, 'word'),
  (@u, 'kinship', 'n. 亲属关系', 4, 'word'),
  (@u, 'kit', 'n. 衣物和装备', 5, 'word'),
  (@u, 'knock', 'v. 敲打', 6, 'word'),
  (@u, 'ladder', 'n. 梯子；阶梯', 7, 'word'),
  (@u, 'lag', 'vt. 落后于n. 滞后', 8, 'word'),
  (@u, 'landowner', 'n. 地主', 9, 'word'),
  (@u, 'lateral', 'a. 侧面的横向的n.侧部的东西', 10, 'word'),
  (@u, 'lawful', 'a. 合法的；法定的', 11, 'word'),
  (@u, 'leap', 'vi. 跳；vt. 跳过n. 跳跃', 12, 'word'),
  (@u, 'legitimacy', 'n. 合法性', 13, 'word'),
  (@u, 'length', 'n. 长度；长', 14, 'word'),
  (@u, 'liable', 'a. 有责任的；有义务的', 15, 'word'),
  (@u, 'liberal-arts', '大学文科', 16, 'word'),
  (@u, 'liberate', 'vt. 解放；释放', 17, 'word'),
  (@u, 'likewise', 'ad. 同样地', 18, 'word'),
  (@u, 'limbic', 'a. 边的；边缘的', 19, 'word'),
  (@u, 'lining', 'n. 衬里v. 排队', 20, 'word'),
  (@u, 'listen', 'v. 听', 21, 'word'),
  (@u, 'liveliness', 'n. 活泼', 22, 'word'),
  (@u, 'loan', 'n. 贷款vt. 借', 23, 'word'),
  (@u, 'locate', 'vt. 位于vi. 定位', 24, 'word'),
  (@u, 'logic', 'n. 逻辑', 25, 'word'),
  (@u, 'longline', 'n. 多钩长线', 26, 'word'),
  (@u, 'lounge', 'n. 休息厅vi. 闲逛', 27, 'word'),
  (@u, 'low-level', '低层次', 28, 'word'),
  (@u, 'loyal', 'a. 忠诚的', 29, 'word'),
  (@u, 'lucky', 'a. 幸运的', 30, 'word'),
  (@u, 'lunch', 'n. 午餐vt/vi 吃午餐', 31, 'word'),
  (@u, 'lung', 'n. 肺', 32, 'word'),
  (@u, 'maintenance', 'n. 维持；保持；保养', 33, 'word'),
  (@u, 'maker', 'n. 制造者', 34, 'word'),
  (@u, 'mania', 'n. 狂躁；热衷', 35, 'word'),
  (@u, 'manipulation', 'n. （熟练的）操作；控制', 36, 'word'),
  (@u, 'manpower', 'n. 人力；劳动力', 37, 'word'),
  (@u, 'markedly', 'ad. 显著地', 38, 'word'),
  (@u, 'marketplace', 'n. 市集；集市', 39, 'word'),
  (@u, 'marriage', 'n. 婚姻', 40, 'word'),
  (@u, 'marvel', 'n. 奇迹vt/vi 对…感到惊奇', 41, 'word'),
  (@u, 'mask', 'n. 面具vt. 掩饰vi. 戴面具', 42, 'word'),
  (@u, 'mate', 'n. 伴侣', 43, 'word'),
  (@u, 'mathematical', 'a. 数学的', 44, 'word'),
  (@u, 'mathematics', 'n. 数学', 45, 'word'),
  (@u, 'meaningless', 'a. 无意义的', 46, 'word'),
  (@u, 'measurable', 'a. 可测量的', 47, 'word'),
  (@u, 'meat', 'n. 肉', 48, 'word'),
  (@u, 'mechanic', 'a. 技工；机修师', 49, 'word'),
  (@u, 'mechanistic', 'a. 机械论的', 50, 'word'),
  (@u, 'mentally', 'ad. 心理上', 51, 'word'),
  (@u, 'merit', 'n. 优点；好处', 52, 'word'),
  (@u, 'migrate', 'v. 迁徙', 53, 'word'),
  (@u, 'mildly', 'ad. 和善地', 54, 'word'),
  (@u, 'mine', 'n. 矿井vt. 在…中开采pron: 我的（东西）', 55, 'word'),
  (@u, 'minimum', 'n. 最少量', 56, 'word'),
  (@u, 'misguide', 'vt. 把…引入歧途', 57, 'word'),
  (@u, 'misplace', 'vt. 把（情感等）寄托于不值得寄托的人身上；把…放错位置', 58, 'word'),
  (@u, 'mistakenly', 'ad. 错误地', 59, 'word'),
  (@u, 'mobile', 'a. 可移动的', 60, 'word'),
  (@u, 'mobility', 'n. 流动性', 61, 'word'),
  (@u, 'modesty', 'n.谦虚；谦逊', 62, 'word'),
  (@u, 'modification', 'n. 修改；修正', 63, 'word'),
  (@u, 'molecular', 'a. 分子的', 64, 'word'),
  (@u, 'monitor', 'n. 显示屏vt. 监控vi. 监视', 65, 'word'),
  (@u, 'moon', 'n. 月亮', 66, 'word'),
  (@u, 'morally', 'ad. 道德地', 67, 'word'),
  (@u, 'mountain', 'n. 山', 68, 'word'),
  (@u, 'mythical', 'a. 神话的；虚构的', 69, 'word'),
  (@u, 'narrowly', 'ad. 狭窄地；勉强地', 70, 'word'),
  (@u, 'nationally', 'ad. 全国性地', 71, 'word'),
  (@u, 'nation-wide', 'a. 全国范围内的', 72, 'word'),
  (@u, 'necessity', 'n. 必需品', 73, 'word'),
  (@u, 'neighbor', 'n. 邻居', 74, 'word'),
  (@u, 'nerve', 'n. 神经vt. 鼓励', 75, 'word'),
  (@u, 'newsletter', 'n. 时事通讯', 76, 'word'),
  (@u, 'newsroom', 'n. 新闻编辑室', 77, 'word'),
  (@u, 'newsstand', 'n. 报刊；杂志摊', 78, 'word'),
  (@u, 'nine', 'n. 9', 79, 'word'),
  (@u, 'noble', 'a. 时尚的n. 尊贵的人', 80, 'word'),
  (@u, 'nobody', 'n. 小人物', 81, 'word'),
  (@u, 'nonetheless', 'ad. 虽然如此', 82, 'word'),
  (@u, 'non-standard', 'a. 不标准的', 83, 'word'),
  (@u, 'norm', 'n. 标准', 84, 'word'),
  (@u, 'normally', 'adv. 通常地', 85, 'word'),
  (@u, 'novelty', 'n. 新奇；新奇的事物', 86, 'word'),
  (@u, 'numerical', 'a. 数字的；数值的', 87, 'word'),
  (@u, 'nurse', 'n. 护士', 88, 'word'),
  (@u, 'obligation', 'n. 义务；责任', 89, 'word'),
  (@u, 'obsess', 'vt. 使着迷', 90, 'word'),
  (@u, 'oil-price', '油价', 91, 'word'),
  (@u, 'one-quarter', '四分之一', 92, 'word'),
  (@u, 'opening', 'a. 开放的', 93, 'word'),
  (@u, 'open-source', '提供源程序的', 94, 'word'),
  (@u, 'operational', 'a. 操作的；经营的', 95, 'word'),
  (@u, 'operator', 'n. 经营者；操作者', 96, 'word');

-- ---------- Unit 23  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 23', 23);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'opponent', 'n. 对手a. 对立的', 1, 'word'),
  (@u, 'opposition', 'n. 反对', 2, 'word'),
  (@u, 'orderly', 'a. 整齐的；有秩序的', 3, 'word'),
  (@u, 'organ', 'n. 器官', 4, 'word'),
  (@u, 'organism', 'n. 有机体', 5, 'word'),
  (@u, 'originally', 'ad. 起初；原来', 6, 'word'),
  (@u, 'outburst', 'n. （怒气等的）爆发', 7, 'word'),
  (@u, 'outlive', 'v. 比….长寿；（在….消失后）继续存在（语境意）', 8, 'word'),
  (@u, 'outsider', 'n. 局外人', 9, 'word'),
  (@u, 'outweigh', 'vt. 比…重要', 10, 'word'),
  (@u, 'overcharge', 'vt. 对…要价过高n. 过高要价', 11, 'word'),
  (@u, 'overcome', 'v. 克服', 12, 'word'),
  (@u, 'palace', 'n. 宫殿', 13, 'word'),
  (@u, 'pan', 'n. 平底锅vt. 淘金', 14, 'word'),
  (@u, 'paradoxical', 'a. 悖论的', 15, 'word'),
  (@u, 'paralyze', 'v. 使残疾', 16, 'word'),
  (@u, 'paraphrase', 'v. 改写', 17, 'word'),
  (@u, 'parental', 'a. 父母的', 18, 'word'),
  (@u, 'parenthood', 'n. 家长身份', 19, 'word'),
  (@u, 'parliamentary', 'a. 议会的；国会的', 20, 'word'),
  (@u, 'partial', 'a. 部分的；有偏见的', 21, 'word'),
  (@u, 'partially', 'ad. 部分地', 22, 'word'),
  (@u, 'participant', 'n. 参与者', 23, 'word'),
  (@u, 'patchwork', 'n. 拼缝物', 24, 'word'),
  (@u, 'paternity', 'n.父亲的身份', 25, 'word'),
  (@u, 'patronize', 'vt.回顾；资助', 26, 'word'),
  (@u, 'peace', 'n. 和平', 27, 'word'),
  (@u, 'peaceful', 'a. 和平的', 28, 'word'),
  (@u, 'peak', 'n. 山峰vi 达到高峰', 29, 'word'),
  (@u, 'peer-review', '同辈评审', 30, 'word'),
  (@u, 'pen', 'n. 笔vt. 写', 31, 'word'),
  (@u, 'perfectly', 'ad. 完美地', 32, 'word'),
  (@u, 'persist', 'v. 坚持', 33, 'word'),
  (@u, 'persuasive', 'a 有说服力的', 34, 'word'),
  (@u, 'pessimism', 'n. 悲观；悲观情绪', 35, 'word'),
  (@u, 'petrol', 'n. 汽油', 36, 'word'),
  (@u, 'phase', 'n. 阶段；vt. 分阶段进行', 37, 'word'),
  (@u, 'photo', '/photograph：n. 照片', 38, 'word'),
  (@u, 'pilgrim', 'n. 朝圣者v. 朝圣', 39, 'word'),
  (@u, 'pipe', 'n. 烟斗vt. 以管道运输', 40, 'word'),
  (@u, 'plain', 'n. 平原a. 平的ad. 清楚地', 41, 'word'),
  (@u, 'plead', 'v. 请求', 42, 'word'),
  (@u, 'please', '请；vt/vi 使高兴', 43, 'word'),
  (@u, 'plunge', 'vt. 用力插入vi. 调入n. 投入', 44, 'word'),
  (@u, 'poach', 'v. 水煮；窃取', 45, 'word'),
  (@u, 'poisonous', 'a. 有毒的', 46, 'word'),
  (@u, 'poorly', 'ad. 可怜地；表现不好地', 47, 'word'),
  (@u, 'popularize', 'vt.使受欢迎', 48, 'word'),
  (@u, 'positively', 'ad. 积极地；乐观地', 49, 'word'),
  (@u, 'possession', 'n. 财产', 50, 'word'),
  (@u, 'posture', 'n. 姿势；态度；立场', 51, 'word'),
  (@u, 'practically', 'ad. 实际上；实施上', 52, 'word'),
  (@u, 'preach', 'vt/vi.布道／宣扬', 53, 'word'),
  (@u, 'precious', 'a. 珍贵的', 54, 'word'),
  (@u, 'precision', 'n. 精确度', 55, 'word'),
  (@u, 'predictably', 'ad. 可预测地', 56, 'word'),
  (@u, 'preface', 'n. 序言；引语', 57, 'word'),
  (@u, 'preference', 'n. 偏爱；优先权', 58, 'word'),
  (@u, 'prefrontal', 'a. 前额的', 59, 'word'),
  (@u, 'pregnant', 'a. 怀孕的', 60, 'word'),
  (@u, 'prehistoric', 'a. 史前的', 61, 'word'),
  (@u, 'prescribe', 'vt.指定；规定', 62, 'word'),
  (@u, 'prescription', 'n. 规定；处方', 63, 'word'),
  (@u, 'presumably', 'ad. 据推测', 64, 'word'),
  (@u, 'prevention', 'n. 预防', 65, 'word'),
  (@u, 'prey', 'n. 被捕食的动物vi. 捕食', 66, 'word'),
  (@u, 'prison', 'n. 监狱', 67, 'word'),
  (@u, 'professionalism', 'n. 专业性', 68, 'word'),
  (@u, 'profitability', 'n. 获利（状况）', 69, 'word'),
  (@u, 'prominent', 'a. 突出的；杰出的', 70, 'word'),
  (@u, 'propel', 'vt. 推进；推动', 71, 'word'),
  (@u, 'pull', 'v. 拉', 72, 'word'),
  (@u, 'punish', 'v. 惩罚', 73, 'word'),
  (@u, 'pupil', 'n. 学生；瞳孔', 74, 'word'),
  (@u, 'purist', 'n. 语言纯正癖者', 75, 'word'),
  (@u, 'pyramid', 'n. 金字塔', 76, 'word'),
  (@u, 'quarrel', 'n. 争吵vi. 争辩', 77, 'word'),
  (@u, 'queen', 'n. 女皇', 78, 'word'),
  (@u, 'query', 'n. 疑问vt. 质疑vi. 询问', 79, 'word'),
  (@u, 'rain', 'n. 雨；v. 下雨', 80, 'word'),
  (@u, 'rally', 'vt. 召集；vi. 聚集n. 集合', 81, 'word'),
  (@u, 'ratio', 'n. 比率', 82, 'word'),
  (@u, 'react', 'v. 对…做出反映', 83, 'word'),
  (@u, 'reactor', 'n. 反应堆', 84, 'word'),
  (@u, 'realise', 'v. 意识到；实现', 85, 'word'),
  (@u, 'reap', 'vt/vi 收割；获得', 86, 'word'),
  (@u, 'rebind', 'vt. 重新装订', 87, 'word'),
  (@u, 'recession', 'n. 经济衰退', 88, 'word'),
  (@u, 'recognition', 'n. 认识；识别', 89, 'word'),
  (@u, 'reconsider', 'v. 再次考虑', 90, 'word'),
  (@u, 'recur', 'vi. 再发生；复发', 91, 'word'),
  (@u, 'red', 'a. 红色的', 92, 'word'),
  (@u, 'redundancy', 'n. 过多；过剩', 93, 'word'),
  (@u, 'register', 'v. 注册；登记', 94, 'word'),
  (@u, 'regulate', 'vt. 调节；调整', 95, 'word'),
  (@u, 'reliability', 'n. 可靠性', 96, 'word');

-- ---------- Unit 24  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 24', 24);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'relief', 'n. 安慰；安心', 1, 'word'),
  (@u, 'remote', 'a. 偏远的', 2, 'word'),
  (@u, 'render', 'v. 致使；造成', 3, 'word'),
  (@u, 'renege', 'vi. 食言vt.否认', 4, 'word'),
  (@u, 'renew', 'vt. 重新开始vi. 重申', 5, 'word'),
  (@u, 'republican', 'a. 共和国的', 6, 'word'),
  (@u, 'reserve', 'n. 储备vt. 储备vi. 预定', 7, 'word'),
  (@u, 'reshape', 'v. 重塑', 8, 'word'),
  (@u, 'resistance', 'n. 抵抗；阻力：', 9, 'word'),
  (@u, 'respectively', 'ad. 各自地', 10, 'word'),
  (@u, 'restrict', 'vt. 限制；限定', 11, 'word'),
  (@u, 'resume', 'v. 重新开始n. 简历', 12, 'word'),
  (@u, 'retire', 'v. 退休', 13, 'word'),
  (@u, 'retirement', 'n. 退休', 14, 'word'),
  (@u, 'reverse', 'vt&vi 反转vi 倒退n 倒转', 15, 'word'),
  (@u, 'reviewer', 'n. 评论家；评论者', 16, 'word'),
  (@u, 'revive', 'vt. 使复活vi. 复苏', 17, 'word'),
  (@u, 'revolutionary', 'a. 革命的；n. 革命者', 18, 'word'),
  (@u, 'revolve', 'vt/vi 使旋转反复考虑vi. 旋转', 19, 'word'),
  (@u, 'rid', 'vt. 使摆脱', 20, 'word'),
  (@u, 'ritual', 'a. 例行公事的', 21, 'word'),
  (@u, 'river', 'n. 河流', 22, 'word'),
  (@u, 'robotic', 'a. 自动的；机器人的', 23, 'word'),
  (@u, 'room', 'n. 房间；空间vt. 租房', 24, 'word'),
  (@u, 'round', 'a. 圆形的，丰满的ad. 到处prep. 大约', 25, 'word'),
  (@u, 'route', 'n. 路vt 按照某路线发送', 26, 'word'),
  (@u, 'rude', 'a. 粗鲁的', 27, 'word'),
  (@u, 'rut', 'n. 车辙；vt. 犁', 28, 'word'),
  (@u, 'sad', 'a. 悲伤的', 29, 'word'),
  (@u, 'sake', 'n. 缘故；理由', 30, 'word'),
  (@u, 'sandal', 'n. 凉鞋', 31, 'word'),
  (@u, 'scatter', 'vt/vi 散开n. 散布', 32, 'word'),
  (@u, 'schism', 'n. 教会分立；分裂', 33, 'word'),
  (@u, 'scholarly', 'adj. 学术性的', 34, 'word'),
  (@u, 'scientifically', 'ad. 科学地', 35, 'word'),
  (@u, 'scrutiny', 'n. 细看；细阅', 36, 'word'),
  (@u, 'sedition', 'n. 煽动性言行', 37, 'word'),
  (@u, 'seed', 'n. 种子', 38, 'word'),
  (@u, 'self-doubt', '自我怀疑', 39, 'word'),
  (@u, 'self-examination', '自我检测', 40, 'word'),
  (@u, 'self-expression', '自我表达', 41, 'word'),
  (@u, 'self-help', '自立', 42, 'word'),
  (@u, 'self-interest', '利己主义', 43, 'word'),
  (@u, 'seller', 'n. 卖者', 44, 'word'),
  (@u, 'semiconductor', 'n. 半导体', 45, 'word'),
  (@u, 'sensory', 'a. 感觉的；感受的', 46, 'word'),
  (@u, 'sentiment', 'n. 感情；情绪', 47, 'word'),
  (@u, 'servant', 'n. 仆人；佣人', 48, 'word'),
  (@u, 'setting', 'n. 镶嵌；环境', 49, 'word'),
  (@u, 'settlement', 'n. 解决；结算', 50, 'word'),
  (@u, 'sexual', 'a. 性感的', 51, 'word'),
  (@u, 'shall', 'aux 应该', 52, 'word'),
  (@u, 'shark', 'n. 鲨鱼v. 骗取vi. 诈骗', 53, 'word'),
  (@u, 'sharp', 'a. 敏锐的，锋利的ad. 猛烈地', 54, 'word'),
  (@u, 'sharpen', 'vt/vi 使锐利', 55, 'word'),
  (@u, 'shelter', 'n. 居所vt. 掩蔽vi. 躲避', 56, 'word'),
  (@u, 'shield', 'n. 盾vt. 保护', 57, 'word'),
  (@u, 'shortly', 'ad. 立刻；马上', 58, 'word'),
  (@u, 'shoulder', 'n. 肩膀v. 承担', 59, 'word'),
  (@u, 'sick', 'a. 恶心的晕船的vt. 吐出', 60, 'word'),
  (@u, 'silicon', 'n. 硅', 61, 'word'),
  (@u, 'silt', 'n. 淤泥；泥沙vi. 被淤塞', 62, 'word'),
  (@u, 'silver', 'n. 银', 63, 'word'),
  (@u, 'similarity', 'n. 相似性', 64, 'word'),
  (@u, 'simplicity', 'n. 简单，朴素', 65, 'word'),
  (@u, 'simplify', 'v. 简化', 66, 'word'),
  (@u, 'sir', 'n. 先生', 67, 'word'),
  (@u, 'skepticism', 'n. 怀疑态度；怀疑论', 68, 'word'),
  (@u, 'sketch', 'n. 草图v. 草拟', 69, 'word'),
  (@u, 'slice', 'n. 一片', 70, 'word'),
  (@u, 'slight', 'a.微小的n. 蔑视vt. 轻蔑', 71, 'word'),
  (@u, 'slightly', 'ad. 轻微地', 72, 'word'),
  (@u, 'slip', 'vi. 滑n跌倒a 滑动的', 73, 'word'),
  (@u, 'slogan', 'n. 口号', 74, 'word'),
  (@u, 'slot', 'n. 位置vt. 跟踪', 75, 'word'),
  (@u, 'slow-growing', 'a. 生长缓慢的', 76, 'word'),
  (@u, 'small-minded', '眼光狭小的', 77, 'word'),
  (@u, 'smoker', 'n. 吸烟者', 78, 'word'),
  (@u, 'smoothly', 'ad. 平滑地', 79, 'word'),
  (@u, 'snow', 'n. 雪', 80, 'word'),
  (@u, 'socially', 'ad. 社会地；社交地', 81, 'word'),
  (@u, 'soft', 'a. 柔软的', 82, 'word'),
  (@u, 'soften', 'a. 软化', 83, 'word'),
  (@u, 'solid', 'a. 坚固的', 84, 'word'),
  (@u, 'somebody', 'n . 某人', 85, 'word'),
  (@u, 'someday', 'ad. 将来有一天', 86, 'word'),
  (@u, 'sow', 'vt/vi 播种vt. 灌输', 87, 'word'),
  (@u, 'spacious', 'a. 宽敞的；广阔的', 88, 'word'),
  (@u, 'span', 'n. 跨度', 89, 'word'),
  (@u, 'spare', 'vt. 节省a. 多余的', 90, 'word'),
  (@u, 'speaker', 'n. 发言者', 91, 'word'),
  (@u, 'spin', 'vi. 纺纱结网n. 旋转的行为', 92, 'word'),
  (@u, 'spiritual', 'a. 精神的；心灵的', 93, 'word'),
  (@u, 'splash', 'v. （使）溅起', 94, 'word'),
  (@u, 'spoil', 'vi.变质；vt. 宠溺', 95, 'word'),
  (@u, 'sponsor', 'n. 发起者vt. 赞助', 96, 'word');

-- ---------- Unit 25  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 25', 25);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'spur', 'n. 激励vt. 策马前进', 1, 'word'),
  (@u, 'spymaster', 'n. 间谍组织的首脑', 2, 'word'),
  (@u, 'squeeze', 'v 挤压', 3, 'word'),
  (@u, 'stability', 'n. 稳定性', 4, 'word'),
  (@u, 'stake', 'n. 桩；股份vt. 用桩支撑', 5, 'word'),
  (@u, 'stakeholder', 'n. 持股者', 6, 'word'),
  (@u, 'startle', 'vt. 使震惊vi. 惊吓', 7, 'word'),
  (@u, 'start-up', 'n. 启动a. (新企业或工程)开办阶段', 8, 'word'),
  (@u, 'statesman', 'n. 政治家', 9, 'word'),
  (@u, 'stationary', 'a. 不动的n. 不动的人', 10, 'word'),
  (@u, 'statistical', 'a. 统计的', 11, 'word'),
  (@u, 'stave', 'n. 梯级vt. 延缓vi. 破碎', 12, 'word'),
  (@u, 'stickiness', 'n. 粘性', 13, 'word'),
  (@u, 'stimulate', 'v. 刺激', 14, 'word'),
  (@u, 'straightforward', 'a/ad. 直截了当的', 15, 'word'),
  (@u, 'strategic', 'a. 战略上的', 16, 'word'),
  (@u, 'stretch', 'v. 伸展n. 伸展a 可伸缩的', 17, 'word'),
  (@u, 'strictly', 'ad. 严格地', 18, 'word'),
  (@u, 'string', 'n. 绳子；带子vt. 上弦', 19, 'word'),
  (@u, 'strip', 'vi. 剥光；拨出vt. 除去n. 长条', 20, 'word'),
  (@u, 'structural', 'a. 结构上的', 21, 'word'),
  (@u, 'subconscious', 'a. 潜意识的', 22, 'word'),
  (@u, 'substitute', 'vt/vi 代替，替换n. 代替者', 23, 'word'),
  (@u, 'successfully', 'ad. 成功地', 24, 'word'),
  (@u, 'succession', 'n. 继承人；继承权', 25, 'word'),
  (@u, 'sudden', 'a. 突如其来的', 26, 'word'),
  (@u, 'sue', 'vt/vi 控告／控诉', 27, 'word'),
  (@u, 'sufficiently', 'ad.充足地；充分地', 28, 'word'),
  (@u, 'suitable', 'a. 合适的', 29, 'word'),
  (@u, 'sum', 'n. 总数；算数', 30, 'word'),
  (@u, 'summer', 'n. 夏天', 31, 'word'),
  (@u, 'sun', 'n. 太阳', 32, 'word'),
  (@u, 'Sunday', 'n. 星期天', 33, 'word'),
  (@u, 'Superior', 'a.较高的n. 上级', 34, 'word'),
  (@u, 'Superstar', 'n. 巨星', 35, 'word'),
  (@u, 'supplier', 'n. 供应商', 36, 'word'),
  (@u, 'suppress', 'v. 镇压', 37, 'word'),
  (@u, 'surely', 'ad. 确定地；当然地', 38, 'word'),
  (@u, 'susceptible', 'a. 易受影响的', 39, 'word'),
  (@u, 'suspend', 'v. 暂停；延缓', 40, 'word'),
  (@u, 'suspension', 'n. 暂停', 41, 'word'),
  (@u, 'suspicious', 'a. 可疑的；猜疑的', 42, 'word'),
  (@u, 'sustainability', 'n. 可持续性', 43, 'word'),
  (@u, 'sweep', 'v. 打扫', 44, 'word'),
  (@u, 'swing', 'vt/vi （使）摇摆n. 摇摆vt. 使旋转', 45, 'word'),
  (@u, 'synthetic', 'a. 合成的；n. 合成物', 46, 'word'),
  (@u, 'table', 'n. 桌子，目录，表格vt. 制表', 47, 'word'),
  (@u, 'tactic', 'n. 手段；策略', 48, 'word'),
  (@u, 'taxpayer', 'n. 纳税人', 49, 'word'),
  (@u, 'teamster', 'n. 卡车驾驶员', 50, 'word'),
  (@u, 'tear', 'n. 眼泪v. 撕裂', 51, 'word'),
  (@u, 'teen', 'n. 青年人', 52, 'word'),
  (@u, 'telegraph', 'n. 电报vt. 打电报', 53, 'word'),
  (@u, 'temper', 'n. 性情；脾气vt. 调和vi. 使调和', 54, 'word'),
  (@u, 'template', 'n. 样板；模版', 55, 'word'),
  (@u, 'tentative', 'a. 试探性的n. 假设', 56, 'word'),
  (@u, 'territory', 'n. 领域', 57, 'word'),
  (@u, 'therapy', 'n. 治疗', 58, 'word'),
  (@u, 'thin', 'a. 瘦弱的', 59, 'word'),
  (@u, 'thinker', 'n. 思想家', 60, 'word'),
  (@u, 'thirty', 'n. 30', 61, 'word'),
  (@u, 'thoroughly', 'ad. 彻底地', 62, 'word'),
  (@u, 'thrift', 'n. 节约', 63, 'word'),
  (@u, 'thrill', 'vt. 使激动vi. 颤动', 64, 'word'),
  (@u, 'thrive', 'v. 繁荣；蓬勃发展', 65, 'word'),
  (@u, 'tide', 'n. 潮汐；潮流', 66, 'word'),
  (@u, 'tiger', 'n. 老虎', 67, 'word'),
  (@u, 'till', 'conj 直到…时vt. 耕种n. 钱柜', 68, 'word'),
  (@u, 'time-consuming', 'a. 消耗时间的', 69, 'word'),
  (@u, 'tooth', 'n. 牙齿', 70, 'word'),
  (@u, 'touch', 'v. 抚摸；感动', 71, 'word'),
  (@u, 'toxic', 'a. 有毒的', 72, 'word'),
  (@u, 'transition', 'n. 过渡；转变', 73, 'word'),
  (@u, 'transport', 'vt. 运送n.运输', 74, 'word'),
  (@u, 'trap', 'vt. 诱骗；n.圈套', 75, 'word'),
  (@u, 'tribe', 'n. 部落；部族', 76, 'word'),
  (@u, 'trigger', 'v 引起', 77, 'word'),
  (@u, 'truly', 'ad. 真正地', 78, 'word'),
  (@u, 'turbulent', 'a. 骚乱的；混乱的', 79, 'word'),
  (@u, 'two-step', '两步', 80, 'word'),
  (@u, 'unable', 'a. 没能力的', 81, 'word'),
  (@u, 'unattractive', 'a. 不吸引人的', 82, 'word'),
  (@u, 'unconsciously', 'ad. 无意识地', 83, 'word'),
  (@u, 'uncontrollable', 'a. 不可控的', 84, 'word'),
  (@u, 'underestimate', 'v. 低估', 85, 'word'),
  (@u, 'underground', 'a. 地下的ad. 在地下的', 86, 'word'),
  (@u, 'underline', 'vt. 在…下面划线n. 下划线', 87, 'word'),
  (@u, 'undertake', 'vt. 承担；从事', 88, 'word'),
  (@u, 'undesirable', 'a. 不受欢迎的', 89, 'word'),
  (@u, 'unexpected', 'a. 出乎意料的', 90, 'word'),
  (@u, 'unfairness', 'n. 不公平', 91, 'word'),
  (@u, 'unfold', 'v. 展开；打开', 92, 'word'),
  (@u, 'unfortunately', 'ad. 不幸地是', 93, 'word'),
  (@u, 'unification', 'n. 统一；联合', 94, 'word'),
  (@u, 'unionist', 'n. 工会会员', 95, 'word'),
  (@u, 'unity', 'n. 统一体', 96, 'word');

-- ---------- Unit 26  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 26', 26);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'unpredictability', 'n. 不可预知性', 1, 'word'),
  (@u, 'unrelated', 'a. 无关的', 2, 'word'),
  (@u, 'upside', 'n. 优点；好处', 3, 'word'),
  (@u, 'urban', 'a. 城市的', 4, 'word'),
  (@u, 'vaccine', 'n. 疫苗', 5, 'word'),
  (@u, 'vacuum', 'n. 真空', 6, 'word'),
  (@u, 'vague', 'a. 模糊的', 7, 'word'),
  (@u, 'vain', 'a. 徒劳的；自负的', 8, 'word'),
  (@u, 'vanity', 'n. 虚荣；浮华', 9, 'word'),
  (@u, 'verb', 'n. 动词', 10, 'word'),
  (@u, 'verbally', 'ad.言词上', 11, 'word'),
  (@u, 'via', 'prep. 经过；通过', 12, 'word'),
  (@u, 'victory', 'n. 胜利', 13, 'word'),
  (@u, 'vigorously', 'ad. 精神旺盛地', 14, 'word'),
  (@u, 'vineyard', 'n. 葡萄园', 15, 'word'),
  (@u, 'virtue', 'n. 美德；德行', 16, 'word'),
  (@u, 'visual', 'a. 可视的', 17, 'word'),
  (@u, 'vital', 'a. 至关重要的', 18, 'word'),
  (@u, 'vivid', 'a. 生动的', 19, 'word'),
  (@u, 'volunteer', 'n. 志愿者', 20, 'word'),
  (@u, 'wager', 'n. 赌注；赌金vt/vi 打赌', 21, 'word'),
  (@u, 'wasteful', 'a. 浪费的', 22, 'word'),
  (@u, 'wealthy', 'a. 富有的', 23, 'word'),
  (@u, 'weave', 'vt/vi 编；织vt. 编排n. 纺织物', 24, 'word'),
  (@u, 'weekly', 'ad. 一星期一次地', 25, 'word'),
  (@u, 'weird', 'a. 奇怪的', 26, 'word'),
  (@u, 'well-developed', '发展／发育良好的；丰满', 27, 'word'),
  (@u, 'well-educated', '受过良好教育的', 28, 'word'),
  (@u, 'well-known', '知名的', 29, 'word'),
  (@u, 'well-meaning', 'a.善意的；好心的', 30, 'word'),
  (@u, 'westerner', 'n. 西方人', 31, 'word'),
  (@u, 'wheel', 'n. 轮子vi. 转动vt. 推', 32, 'word'),
  (@u, 'whereby', 'ad. 通过', 33, 'word'),
  (@u, 'wholesaler', 'n. 批发商', 34, 'word'),
  (@u, 'withdraw', 'vt.撤走；拿走vi. 撤退', 35, 'word'),
  (@u, 'worldview', 'n. 视力；观点；目的', 36, 'word'),
  (@u, 'worthy', 'a. 值得的', 37, 'word'),
  (@u, 'yesterday', 'ad. 昨天', 38, 'word'),
  (@u, 'abnormality', 'n. 反常；变态', 39, 'word'),
  (@u, 'aboard', 'prep/ad. 在（船；飞机）上', 40, 'word'),
  (@u, 'abreast', 'ad/a. 并列的', 41, 'word'),
  (@u, 'abrupt', 'a. 突然的；意外的', 42, 'word'),
  (@u, 'absorption', 'n.吸收；专注', 43, 'word'),
  (@u, 'absurd', 'a. 荒谬的；荒唐的', 44, 'word'),
  (@u, 'abundance', 'n. 丰富；充裕', 45, 'word'),
  (@u, 'abundant', 'a. 丰富的', 46, 'word'),
  (@u, 'abundantly', 'ad. 丰富地', 47, 'word'),
  (@u, 'abuzz', 'a. 嗡嗡的', 48, 'word'),
  (@u, 'academia', 'a. 学术界', 49, 'word'),
  (@u, 'accidentally', 'ad. 偶然地／意外地', 50, 'word'),
  (@u, 'accident-free', '无事故的', 51, 'word'),
  (@u, 'accommodate', 'v 容纳；使适应', 52, 'word'),
  (@u, 'accommodation', 'n. 住处；适应', 53, 'word'),
  (@u, 'accord', 'n. 协议；条约vt. 给予vi.符合', 54, 'word'),
  (@u, 'accountant', 'n. 会计人员', 55, 'word'),
  (@u, 'accuracy', 'n. 准确性', 56, 'word'),
  (@u, 'accusation', 'n. 指责，谴责', 57, 'word'),
  (@u, 'accustom', 'vt. 使习惯', 58, 'word'),
  (@u, 'acquisitive', 'a. 渴望得到的', 59, 'word'),
  (@u, 'actively', 'ad. 活跃地；积极地', 60, 'word'),
  (@u, 'adaptable', 'a. 能适应的', 61, 'word'),
  (@u, 'adaptive', 'a. 适应的；适应能力强的', 62, 'word'),
  (@u, 'added-worker', '新增工人', 63, 'word'),
  (@u, 'adjoin', 'vt. ／vi 邻近', 64, 'word'),
  (@u, 'administer', 'vt. 管理；治理vi. 给予帮助', 65, 'word'),
  (@u, 'administrative', 'a. 管理的；行政的', 66, 'word'),
  (@u, 'admiration', 'n. 钦佩；赞美', 67, 'word'),
  (@u, 'adolescence', 'n. 青春期', 68, 'word'),
  (@u, 'adolescent', 'n. 青少年', 69, 'word'),
  (@u, 'adoption', 'n. 采用；收养', 70, 'word'),
  (@u, 'adoptive', 'a. 收养的', 71, 'word'),
  (@u, 'advent', 'n. 来临；到来', 72, 'word'),
  (@u, 'adventurous', 'a. 爱冒险的', 73, 'word'),
  (@u, 'advice', 'n. 建议', 74, 'word'),
  (@u, 'advisability', 'n. 明智', 75, 'word'),
  (@u, 'advisable', 'a.明智的；可取的', 76, 'word'),
  (@u, 'advise', 'vt/vi 通知；报告；建议', 77, 'word'),
  (@u, 'adviser', 'n. 顾问', 78, 'word'),
  (@u, 'aeronautics', 'n. 航空学', 79, 'word'),
  (@u, 'aeroplane', 'n. 飞机', 80, 'word'),
  (@u, 'affiliate', 'vt. 接纳…为成员vt/vi 加入', 81, 'word'),
  (@u, 'affiliation', 'n. 加入；附属', 82, 'word'),
  (@u, 'affinity', 'n. 密切关系', 83, 'word'),
  (@u, 'affirm', 'vt/vi 断言；肯定', 84, 'word'),
  (@u, 'affordable', 'a. 能支付得起的', 85, 'word'),
  (@u, 'afterward', 'ad. 以后', 86, 'word'),
  (@u, 'agony', 'n. 痛苦', 87, 'word'),
  (@u, 'agreeable', 'a. 令人愉快的', 88, 'word'),
  (@u, 'agriculture', 'n. 农业', 89, 'word'),
  (@u, 'aimless', 'a. 无目标的', 90, 'word'),
  (@u, 'aimlessly', 'ad. 无目标地', 91, 'word'),
  (@u, 'airplane', 'n. 飞机', 92, 'word'),
  (@u, 'akin', 'a. 同族的；相似的', 93, 'word'),
  (@u, 'alarm', 'n. 警报；vt. 使惊恐', 94, 'word'),
  (@u, 'allege', 'vt. 断言；宣称', 95, 'word'),
  (@u, 'alleviate', 'vt. 减轻；缓和', 96, 'word');

-- ---------- Unit 27  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 27', 27);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'alliance', 'n. 结盟；联盟', 1, 'word'),
  (@u, 'alteration', 'n. 变化；改变', 2, 'word'),
  (@u, 'alternatively', 'ad.要不然；或者', 3, 'word'),
  (@u, 'altogether', 'ad. 全部地／完全地', 4, 'word'),
  (@u, 'ambitious', 'a. 有雄心的', 5, 'word'),
  (@u, 'ambulance-chasing', '于事无补', 6, 'word'),
  (@u, 'amendment', 'n. 修正案', 7, 'word'),
  (@u, 'amiable', 'a.和蔼可亲的', 8, 'word'),
  (@u, 'amid', 'prep 在…中间', 9, 'word'),
  (@u, 'amongst', 'prep. 处在…之中', 10, 'word'),
  (@u, 'ample', 'a. 足够的；充足的', 11, 'word'),
  (@u, 'amuse', 'vt. 使人发笑；逗乐', 12, 'word'),
  (@u, 'analogous', 'a. 相似的，可比拟的', 13, 'word'),
  (@u, 'analytically', 'ad. 分析地', 14, 'word'),
  (@u, 'anatomy', 'n. 解剖；分解', 15, 'word'),
  (@u, 'ancient', 'a. 古老的', 16, 'word'),
  (@u, 'anecdotal', 'a. 奇闻逸事般的', 17, 'word'),
  (@u, 'anecdote', 'n. 奇闻逸事', 18, 'word'),
  (@u, 'anew', 'ad. 重新', 19, 'word'),
  (@u, 'anger', 'n. 愤怒', 20, 'word'),
  (@u, 'angle', 'n. 角；角度vt. 调整…的角度', 21, 'word'),
  (@u, 'angry', 'a. 生气的', 22, 'word'),
  (@u, 'announcement', 'n. 通告；布告', 23, 'word'),
  (@u, 'anonymous', 'a. 无名的', 24, 'word'),
  (@u, 'anthropological', 'a. 人类学的', 25, 'word'),
  (@u, 'anticipation', 'n. 期待；希望；预测', 26, 'word'),
  (@u, 'anti-colonial', 'a. 反殖民的', 27, 'word'),
  (@u, 'anti-competitive', 'a. 反竞争的', 28, 'word'),
  (@u, 'antigravity', 'n. 反重力', 29, 'word'),
  (@u, 'anti-intellectual', 'a. 反知识分子的', 30, 'word'),
  (@u, 'anti-patent', 'a. 反专利的', 31, 'word'),
  (@u, 'anxious', 'a. 焦虑的', 32, 'word'),
  (@u, 'anymore', 'ad.不再….', 33, 'word'),
  (@u, 'anytime', 'ad. 任何时候', 34, 'word'),
  (@u, 'appetite', 'n. 胃口', 35, 'word'),
  (@u, 'appliance', 'n. 器具；器械', 36, 'word'),
  (@u, 'applicable', 'a. 适当的；可用的', 37, 'word'),
  (@u, 'apprehension', 'n. 不安；忧虑', 38, 'word'),
  (@u, 'apprehensive', 'a. 有理解力的', 39, 'word'),
  (@u, 'April', 'n. 四月', 40, 'word'),
  (@u, 'archive', 'v. 存档n. 档案文件', 41, 'word'),
  (@u, 'arithmetic', 'n. 算数；计算', 42, 'word'),
  (@u, 'army', 'n. 军队', 43, 'word'),
  (@u, 'arrogant', 'a. 傲慢的', 44, 'word'),
  (@u, 'arthritis', 'n. 关节炎', 45, 'word'),
  (@u, 'articulately', 'ad. 口齿清楚地', 46, 'word'),
  (@u, 'art-loving', 'a. 爱艺术的', 47, 'word'),
  (@u, 'artwork', 'n. 艺术品', 48, 'word'),
  (@u, 'asleep', 'a. 睡着的ad. 熟睡地', 49, 'word'),
  (@u, 'aspiration', 'n. 强烈的愿望；吸气', 50, 'word'),
  (@u, 'assault', 'v. 袭击；攻击', 51, 'word'),
  (@u, 'assembly', 'n. 立法机构；议会', 52, 'word'),
  (@u, 'assessable', 'a.可估价的', 53, 'word'),
  (@u, 'assimilative', 'a. 同化的；同化力的', 54, 'word'),
  (@u, 'assurance', 'n. 确定', 55, 'word'),
  (@u, 'asteroid', 'n. 小行星', 56, 'word'),
  (@u, 'astonish', 'vt. 使惊讶', 57, 'word'),
  (@u, 'astray', 'ad. 迷路地', 58, 'word'),
  (@u, 'astrological', 'a. 占星的', 59, 'word'),
  (@u, 'astronomer', 'n. 天文学者', 60, 'word'),
  (@u, 'atmospheric', 'a. 大气的', 61, 'word'),
  (@u, 'atom', 'n. 原子', 62, 'word'),
  (@u, 'attendant', 'n. 服务人员a. 伴随的', 63, 'word'),
  (@u, 'attendee', 'n. (会议等的)出席者', 64, 'word'),
  (@u, 'attentive', 'a. 注意的；周到的', 65, 'word'),
  (@u, 'attorney', 'n. 律师', 66, 'word'),
  (@u, 'augment', 'vt. 增强；增加', 67, 'word'),
  (@u, 'automate', 'vt/vi 自动化', 68, 'word'),
  (@u, 'automotive-assembly', '汽车装配', 69, 'word'),
  (@u, 'autonomous', 'a. 自治的；有自主权的', 70, 'word'),
  (@u, 'auto-pilot', '自动舵', 71, 'word'),
  (@u, 'auxiliary', 'a. 辅助的；备用的n. 助动词', 72, 'word'),
  (@u, 'availability', 'n. 有效；有益', 73, 'word'),
  (@u, 'awake', 'a. 醒着的vt/vi 唤醒', 74, 'word'),
  (@u, 'awkwardly', 'ad. 笨拙地；困难地', 75, 'word'),
  (@u, 'baby-size', 'a. 很小的', 76, 'word'),
  (@u, 'bachelor', 'n. 学士；单身汉', 77, 'word'),
  (@u, 'back-and-forth', '来来回回', 78, 'word'),
  (@u, 'backbone', 'n. 脊椎；主干（语境意）', 79, 'word'),
  (@u, 'backload', 'n. 回载', 80, 'word'),
  (@u, 'back-up', '备份', 81, 'word'),
  (@u, 'backyard', 'n. 院子', 82, 'word'),
  (@u, 'bacterial', 'a. 细菌的', 83, 'word'),
  (@u, 'bait', 'n. 饵vt. 置诱饵于….', 84, 'word'),
  (@u, 'bakery', 'n. 面包店', 85, 'word'),
  (@u, 'ball', 'n. 球vt. 做成球状', 86, 'word'),
  (@u, 'ballet', 'n. 芭蕾舞', 87, 'word'),
  (@u, 'balloon-borne', 'a. 气球运载的', 88, 'word'),
  (@u, 'ballot', 'n. 投票；vi. 投票表决', 89, 'word'),
  (@u, 'banquet', 'n. 宴会；vt. 宴请vi. 参加宴会', 90, 'word'),
  (@u, 'bar', 'n. 棍；棒；酒吧；司法考试', 91, 'word'),
  (@u, 'barn', 'n. 谷仓', 92, 'word'),
  (@u, 'batman', 'n. 勤务兵', 93, 'word'),
  (@u, 'beam', 'vi. 发出光与热vt. 播送', 94, 'word'),
  (@u, 'bearable', 'a. 能够承受的', 95, 'word'),
  (@u, 'beautifully', 'ad. 美丽地', 96, 'word');

-- ---------- Unit 28  (96 词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 28', 28);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'beautify', 'v. 使美丽', 1, 'word'),
  (@u, 'beaver', 'n. 河狸；河狸毛皮；[印]海狸绒布；工作勤恳的人', 2, 'word'),
  (@u, 'bed', 'n. 床v. 铺床（语境意）', 3, 'word'),
  (@u, 'bedrock', 'n. 牢固基础', 4, 'word'),
  (@u, 'beginning', 'n. 开始', 5, 'word'),
  (@u, 'behave', 'v. 表现', 6, 'word'),
  (@u, 'bellyful', 'n. 一肚子；满肚子', 7, 'word'),
  (@u, 'belt-tightening', 'a. 节约的', 8, 'word'),
  (@u, 'beneficence', 'n. 善行', 9, 'word'),
  (@u, 'beneficial', 'a. 有利的；有益的', 10, 'word'),
  (@u, 'beside', 'prep. 除…以外', 11, 'word'),
  (@u, 'best-practice', '最佳做法', 12, 'word'),
  (@u, 'bestseller', 'n. 销冠', 13, 'word'),
  (@u, 'best-seller', 'n.畅销书或唱片；畅销书作者', 14, 'word'),
  (@u, 'betray', 'v. 背叛', 15, 'word'),
  (@u, 'better-behaved', '表现得更好', 16, 'word'),
  (@u, 'bewilder', 'vt. 使迷惑；使为难', 17, 'word'),
  (@u, 'bilingual', 'a. 双语的', 18, 'word'),
  (@u, 'billboard', 'n. 广告牌', 19, 'word'),
  (@u, 'bin', 'n. 箱子vt. 把…装进箱中', 20, 'word'),
  (@u, 'bio-economy', '生物经济', 21, 'word'),
  (@u, 'bioethics', 'n. 生物理论学', 22, 'word'),
  (@u, 'biographer', 'n. 传记作者', 23, 'word'),
  (@u, 'biologically', 'ad. 生物上地', 24, 'word'),
  (@u, 'biophilia', 'n. 热爱生命的天性', 25, 'word'),
  (@u, 'bipedal', 'a. 双脚的', 26, 'word'),
  (@u, 'birthday', 'n. 生日', 27, 'word'),
  (@u, 'birthplace', 'n. 出生地', 28, 'word'),
  (@u, 'bit', 'n. 一点；一块', 29, 'word'),
  (@u, 'bitter', 'a. 苦的，尖锐的n. 苦', 30, 'word'),
  (@u, 'bizarre', 'a. 离奇的', 31, 'word'),
  (@u, 'blacken', 'vt. 使变黑', 32, 'word'),
  (@u, 'blank', 'a. 空白的', 33, 'word'),
  (@u, 'blood', 'n. 血', 34, 'word'),
  (@u, 'blue', 'n. 蓝色', 35, 'word'),
  (@u, 'blunt', 'a. 钝的；不锋利的', 36, 'word'),
  (@u, 'boast', 'v. 吹嘘', 37, 'word'),
  (@u, 'boat', 'n. 船', 38, 'word'),
  (@u, 'bold', 'a. 大胆的', 39, 'word'),
  (@u, 'bombard', 'vt. 炮击；轰炸', 40, 'word'),
  (@u, 'bone', 'n. 骨头', 41, 'word'),
  (@u, 'bonus', 'n. 奖金', 42, 'word'),
  (@u, 'bookstore', 'n. 书店', 43, 'word'),
  (@u, 'boot', 'n. 长靴vi. 帮助或益处', 44, 'word'),
  (@u, 'booth', 'n. 售货棚', 45, 'word'),
  (@u, 'boundary', 'n. 边界', 46, 'word'),
  (@u, 'brainstorm', 'n. 头脑风暴', 47, 'word'),
  (@u, 'brake', 'n. 制动器vt/vi 刹车', 48, 'word'),
  (@u, 'bravely', 'ad. 勇敢地', 49, 'word'),
  (@u, 'bravery', 'n. 勇敢；勇气', 50, 'word'),
  (@u, 'breakout', 'n. 逃脱；越狱', 51, 'word'),
  (@u, 'breast', 'n. 乳腺', 52, 'word'),
  (@u, 'breed', 'vt. 产生vi 产仔n 种类', 53, 'word'),
  (@u, 'bridge', 'n. 桥梁', 54, 'word'),
  (@u, 'brighten', 'vt/vi （使）发亮', 55, 'word'),
  (@u, 'broaden', 'v. 使…变宽', 56, 'word'),
  (@u, 'brochure', 'n. 小册子', 57, 'word'),
  (@u, 'brown', 'a. 棕色的', 58, 'word'),
  (@u, 'bruise', 'n. 瘀伤vt. 使挫伤vi. 碰伤', 59, 'word'),
  (@u, 'buffalo', 'n. 水牛vt. 威胁', 60, 'word'),
  (@u, 'bulb', 'n. 块茎植物；电灯泡', 61, 'word'),
  (@u, 'bulletin', 'n. 公告；公报', 62, 'word'),
  (@u, 'bun', 'n. 酒宴', 63, 'word'),
  (@u, 'bunch', 'n. 束；串vt. 聚成一串', 64, 'word'),
  (@u, 'burden', 'n. 负担', 65, 'word'),
  (@u, 'burdensome', 'a. 有负担的', 66, 'word'),
  (@u, 'bureaucrat', 'n. 官僚；官僚主义', 67, 'word'),
  (@u, 'burst', 'vi. 爆裂vt. 使爆炸', 68, 'word'),
  (@u, 'bury', 'v. 埋葬', 69, 'word'),
  (@u, 'cabin', 'n. 小木屋；客舱vt. 把…关在小屋', 70, 'word'),
  (@u, 'cable', 'n. 缆绳vt. 发电报至', 71, 'word'),
  (@u, 'cake', 'n. 蛋糕', 72, 'word'),
  (@u, 'calendar', 'n. 日历', 73, 'word'),
  (@u, 'calorie', 'n. 卡路里', 74, 'word'),
  (@u, 'camera', 'n. 相机', 75, 'word'),
  (@u, 'canal', 'n. 运河；沟渠', 76, 'word'),
  (@u, 'canon', 'n. 标准；准则', 77, 'word'),
  (@u, 'cape', 'n. 斗篷；披肩', 78, 'word'),
  (@u, 'carbon', 'n. 碳', 79, 'word'),
  (@u, 'career-related', '职业相关的', 80, 'word'),
  (@u, 'carefree', 'a. 无忧无虑的', 81, 'word'),
  (@u, 'cartoon', 'n. 漫画', 82, 'word'),
  (@u, 'carve', 'vi. 切vt. 切片', 83, 'word'),
  (@u, 'cast', 'vt. 铸造n. 铸型vi. 投掷', 84, 'word'),
  (@u, 'casually', 'ad. 随意地', 85, 'word'),
  (@u, 'casualness', 'n. 随意', 86, 'word'),
  (@u, 'casualty', 'n. 伤亡（人数）', 87, 'word'),
  (@u, 'cat', 'n. 猫', 88, 'word'),
  (@u, 'cataract', 'n. 大瀑布', 89, 'word'),
  (@u, 'Catholic', 'a. 保罗万象的', 90, 'word'),
  (@u, 'causal', 'a. 具有因果关系的', 91, 'word'),
  (@u, 'cautiously', 'ad. 小心地', 92, 'word'),
  (@u, 'cellphone', 'n. 手机', 93, 'word'),
  (@u, 'cement', 'n. 水泥vt. 黏牢', 94, 'word'),
  (@u, 'centralization', 'n. 集中化', 95, 'word'),
  (@u, 'centralize', 'vt. 使集中', 96, 'word');

-- ---------- Unit 29  (19 词；NO20–96 原PDF留空，本单元仅19词) ----------
INSERT INTO unit (title, sequence) VALUES ('18中频词汇 Unit 29', 29);
SET @u = LAST_INSERT_ID();
INSERT INTO word (unit_id, english, chinese, seq, type) VALUES
  (@u, 'centuries-old', 'a. 悠久的', 1, 'word'),
  (@u, 'chat', 'vi. 聊天vt. 与….攀谈', 2, 'word'),
  (@u, 'chatter', 'vi. 唠叨n. 闲聊', 3, 'word'),
  (@u, 'cheap', 'a. 便宜的', 4, 'word'),
  (@u, 'cheat', 'v. 欺骗vi. 作弊', 5, 'word'),
  (@u, 'cheerfully', 'ad. 欢乐地', 6, 'word'),
  (@u, 'cheery', 'a. 喜气洋洋的', 7, 'word'),
  (@u, 'childbirth', 'n. 分娩；生产', 8, 'word'),
  (@u, 'childhood', 'n. 童年', 9, 'word'),
  (@u, 'chip', 'n. 碎片', 10, 'word'),
  (@u, 'Christian', 'n. 基督教徒', 11, 'word'),
  (@u, 'Christmas', 'n.圣诞节', 12, 'word'),
  (@u, 'Chromosome', 'n. 染色体', 13, 'word'),
  (@u, 'chronological', 'a. 按时间先后顺序排列的', 14, 'word'),
  (@u, 'chunk', 'n. 厚厚的一块', 15, 'word'),
  (@u, 'citizenship', 'n. 公民身份', 16, 'word'),
  (@u, 'civility', 'n. 礼貌；客气', 17, 'word'),
  (@u, 'civilization', 'n. 文明', 18, 'word'),
  (@u, 'clamp', 'v. 夹紧n. 钳子', 19, 'word');

COMMIT;